version = 1

test_patterns = [
  "src/main/java/**",
  "src/test/java/**",
  "packages/wingui-react/src/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"