TreeGridLoaded ({ /* JSONP header, to be possible to load from xxx_Jsonp data source */

   // Basic grid configuration
   "Cfg" : {
      "DefaultsVersion": "160001",

      "AutoVersion": "1", "SuppressCfg": "0", "DefaultCfg": "3", "DefaultCfgMenu": "1",

      "Locked": "", "LockedValues": ";layout,sheet;layout,sheet,style,formula;layout,sheet,style,formula,edit,save",
      "Editing": "1", "EditHtml": "0", "Adding": "1", "Deleting": "1", "ShowDeleted": "1", "Copying": "1", "Resizing": "1", "AutoBool": "1",
      "DynamicEditing": "0", "DynamicSpan": "0", "DynamicBorder": "0", "SpannedBorder": "3", "BorderOut": "3,black", "BorderIn": "1,black", "DefaultBorder": "1", "WordWrap": "1",
      "Selecting": "1", "SelectingCells": "0", "ClearSelected": "4", "SelectAllType": "0", "SelectHidden": "0",
      "Dragging": "1", "Dropping": "1", "ShowDrag": "1", "DragObject": "1", "ExpandOnDrag": "1", "DropFixed": "2", "ScrollOnDrag": "50", "ScrollColOnDrag": "100", "TouchDragFocused": "2", "TouchDragFocusedDependency": "2",
      "ScrollOnButton": "20", "ScrollOnBody": "200", "ScrollColOnButton": "10", "ScrollColOnBody": "100", "NoScrollAfterExpand": "1", "TouchScroll": "3", "MomentumScroll": "7", "WheelFixed": "5",
      "ColResizing": "1", "ColMoving": "1", "SectionResizing": "1", "ColAdding": "0", "ColCopying": "7", "ColTree": "0", "ColTreeLast": "1", "MaxColLevel": "10",
      "Sorting": "1", "Sorted": "1", "AutoSort": "0", "SortIcons": "1", "MaxSort": "3", "DefaultSort": "1",
      "Grouping": "1", "Grouped": "1", "MaxGroupLength": "0", "GroupChangeMoved": "1", "GroupMoveFree": "1", "GroupHideCols": "1",
      "Filtering": "1", "Filtered": "1", "FilterEmpty": "1",
      "Searching": "1", "Searched": "1", "SearchFocused": "3", "SearchNotFound": "800", "SearchExpand": "1", "SearchMaxMark": "3",
      "Calculated": "1", "FormulaEditing": "0", "FormulaNames": "0", "FormulaType": "0", "FormulaResults": "15", "FormulaCircular": "1", "FormulaMaxIterations": "1000", "FormulaTip": "1", "FormulaTimeout": "10000",
      "RowIndexType": "0", "ColIndexType": "0",
      "EditErrors": "2", "EditErrorsMessageMax": "10", "EditErrorsMessageTime": "2000",
      "DetailOn": "1", "DetailRowsVisible": "3", "NestedFocusedActions": "1",
      "PivotUpdate": "3", "PivotMaxCols": "100",
      "CopyPasteTree": "0", "CopyPasteInternal": "0", "CopyPasteFormulas": "1",
      "CopySelected": "1", "CopyFocused": "1", "CopyCols": "1", "CopyEdit": "1", "CopyTime": "", "CopyFormulas": "1",
      "Pasting": "1", "PasteSelected": "1", "PasteFocused": "8", "PasteCols": "4", "PasteTree": "2", "PasteErrors": "1",
      "RoundNumbers": "0", "RoundNumbersDigits": "5",
      "AutoFillType": "3", "MoveFocusType": "3", "RotateStepsLeft": "270,300,315,330,-1", "RotateStepsRight": "90,60,45,30,-2",
      "MaxAvailability": "100000",
      "UndoMerge": "|Focus,Select,Scroll|ColsVisibility|Filter",
      "UpdateHeightsTimeout": "0", "MediaChange": "1",
      "LongClick": "500",

      "PageTime": "200", "RemoveUnusedPages": "2", "RemoveUnusedFixed": "3",
      "Paging": "0", "PageLength": "20", "PageLengthDiv": "1", "AllPages": "1", "MaxPages": "20",
      "ColPaging": "0", "ColPageLength": "10", "ColPageMin": "10", "MaxColPages": "10",
      "ChildPaging": "2", "RemoveCollapsed": "0", "RemoveChanged": "0", "ChildPageLength": "0", "ChildPageDiff": "0",
      "ChildParts": "", "ChildPartLength": "20", "ChildPartMin": "3", "MaxChildParts": "0",

      "LastId": "", "IdPrefix": "", "IdPostfix": "", "IdChars": "_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", "SetIds": "1", "CaseSensitiveId": "1", "AutoIdPrefix": "AR", "GroupIdPrefix": "GR", "ChildIdPrefix": "CR",
      "TestIdSeparator": "-",
      "AutoUpdate": "0",
      "ReloadChanged": "5",
      "CacheTimeout": "10",
      "ChangesUpdate": "1",
      "ExportCols": "2", "ExportFormat": "xlsx", "ExportType": "Expanded,Outline,ForceBorder,TextType,Strings", "ExportImages": "Img,Html,Space", "ExportLinks": "Link,Html,Other,Underline", "ExportFontSize": "15", "ExportFontFace": "Calibri", "ExportWidthRatio": "1.1", "ExportRowHeight": "20", "ExportBool": "||X|?", "ExportEmptyDecimals": "1", "JSZip": "1",
      "CSVValueSeparator": ";", "CSVRowSeparator": "\u000A", "CSVQuote": "\"", "CSVLevel": "#", "CSVDateFormat": "1", "CSVNumberFormat": "1",
      "ExportOptions": "{HeaderStyle:'bold',HeaderColor:'#F5F5F5',SelectedRowsColor:'#FFFFA6',SelectedColsColor:'#FFFFA6',SelectedCellsColor:'#F0F0A0',AddedColor:'#D7FFD7',DeletedColor:'#FFE5E4',ChangedColor:'#EBEBFF',ChangedCellColor:'#DADAEE',MovedColor:'#DAF3F2',AlternateColor:'#FAFAFA',LinkColor:'#0563C1',TableBorder:'1,black',HeaderBorder:'1,gray',HeadBorder:'1,gray',FootBorder:'1,gray',LeftBorder:'1,gray',RightBorder:'1,gray'}",
      "PrintCols": "2", "PrintRows": "50", "PrintFiltered": "0", "PrintExpanded": "0", "PrintIcons": "1", "PrintPrint": "1", "PrintGanttSplit": "1", "PrintGanttSplitMin": "100", "PrintGanttBackground": "1", "PrintVarHeight": "1", "PrintPageRootMin": "10", "PrintZoomFit": "1", "PrintSplitRowSpan": "1", "ShowPrintPageBreaks": "0", "PrintOnlyData": "0",
      "PrintPageWidth": "643", "PrintPageHeight": "971", "PrintPageSize": "8", "PrintPageOrientation": "0", "PrintDPI": "96", "PrintDefaultDPI": "96", "PrintMinDPI": "96", "PrintMarginWidth": "40", "PrintMarginHeight": "40", "PrintPaddingWidth": "0", "PrintPaddingHeight": "0", "PrintMarginDiv": "1",
      "ExportPDFCols": "2", "PDFFitPage": "0", "PDFText": "1", "PDFFormat": "pdf",
      "ImportAction": "3", "ImportWidths": "1", "ImportImg": "Rotate", "ImportLimitCols": "52", "ImportLimitRows": "1000", "ImportLimitCells": "1000000",
      "DropFiles": "1", "InsertImg": "drop,open,text,float,more", "InsertImgMaxWidth": "300", "InsertImgMaxHeight": "200",
      "EditImg": "Move,Shift,Resize,Rotate,Delete,Copy,Crop,Assign,Opacity,Float,Name", "AssignImg": "Left,Top", "RestoreImg": "Size,Rotation,Position,Crop", "DragImgAngle": "5", "DragImgMinWidth": "5", "DragImgMinHeight": "5",
      "DragImg": "Move,Shift,Resize,Rotate", "DragImgCtrl": "Copy,Shift", "DragImgRight": "MoveXY,Shift", "DragImgCtrlRight": "CopyXY,Shift", "DragImgShift": "Resize", "DragImgShiftRight": "Crop", "DragImgAlt": "Rotate", "DragImgAltRight": "ResizeFree",
      "ExpandAllLoaded": "0", "ExpandAllLevels": "3",

      "SuppressAnimations": "0", "AnimateRows": "3", "AnimateCells": "1", "AnimateCols": "1", "AnimateDialogs": "2", "AnimateRowsMax": "10", "AnimateRowsColorMax": "10", "AnimateColsMax": "10", "AnimateCellsMax": "200", "AnimateUndo": "1",

      "AbsoluteCursors": "", "BorderCursors": "1",
      "FocusWholeRow": "0", "FocusRect": "0", "TabStop": "1", "ExternalFocusMaxRows": "200", "ExternalFocusMaxCols": "70", "ShowFocused": "1",
      "Hover": "2", "ShiftHint": "1",
      "ExactSize": "1", "ExactWidth": "2", "ConstWidth": "6",
      "ColorState": "63",

      "NoActionEscape": "1",
      "StoreOriginalValues": "1",
      "SynchroCount": "100",
      "MessageWidth": "140", "PageMessageWidth": "110", "DeleteMessage": "1",
      "HideMenuUnused": "1", "MaxMenuAllCells": "5000", "MaxMenuAllCellsValue": "1000",
      "NoTreeLines": "0", "HideRootTree": "0", "HideEmptyTree": "0",
      "TipStart": "500",
      "Silent": "1",
      "BoolChars": " X?",
      "DefaultsAlphabetWhite": " !\"#$%&'()*+,-./:;<=>?@[\\]^_{|}",
      "ScrollLeftLap": "1", "ScrollTopLap": "1",
      "LeftCanResize": "1", "RightCanResize": "1",
      "FastPanel": "1", "FastColumns": "1", "FastMerge": "1", "Alternate": "0",
      "LineHeightRatio": "1.333333333",
      "OverlayImg": "1",

      "Style": "Standard", "GanttStyle": "White", "Size": "Normal", "DefaultSize": "Normal", "Scale": "", "Contrast": "Default", "StyleLap": "1", "SizeLap": "0", "ScaleLap": "0",
      "Styles": "{BT:{Name:'Basic',CSS:'*Styles/BasicGrid.css'},TS:{Name:'Standard',CSS:'*Styles/StandardGrid.css'},TW:{Name:'White',CSS:'*Styles/WhiteGrid.css'},TB:{Name:'Black',CSS:'*Styles/BlackGrid.css'},TM:{Name:'Material',CSS:'*Styles/MaterialGrid.css'},TT:{Name:'Turq',CSS:'*Styles/TurqGrid.css'},CF:{Name:'Relief',CSS:'Compatible/Relief',Compatible:1},CL:{Name:'Light',CSS:'Compatible/Light',Compatible:1},CO:{Name:'Office',CSS:'Compatible/Office',Compatible:1},CG:{Name:'Gradient',CSS:'Compatible/Gradient',Compatible:2},CB:{Name:'Borders',CSS:'Compatible/Borders',Compatible:1},CQ:{Name:'Query',CSS:'Compatible/Query',Compatible:1},CE:{Name:'ExtJS',CSS:'Compatible/ExtJS',Compatible:1},CS:{Name:'Sharp',CSS:'Compatible/Sharp',Compatible:1},CR:{Name:'Round',CSS:'Compatible/Round',Compatible:1},CP:{Name:'Plain',CSS:'Compatible/Plain',Compatible:1},CC:{Name:'Colors',CSS:'Compatible/Colors',Compatible:1}}",
      "GanttStyles": "{BG:{Name:'Basic',CSS:'*Styles/BasicGantt.css'},GS:{Name:'Standard',CSS:'*Styles/StandardGantt.css'},GW:{Name:'White',CSS:'*Styles/WhiteGantt.css'},GB:{Name:'Black',CSS:'*Styles/BlackGantt.css'},GM:{Name:'Material',CSS:'*Styles/MaterialGantt.css'},GT:{Name:'Turq',CSS:'*Styles/TurqGantt.css'},MG:{Name:'Mp',CSS:'*Styles/MpGantt.css'}}",
      "Sizes": "{Tiny:'Tiny,Mini,Small,Low',Mini:'Mini,Small,Low',Small:'Small,Low',Low:'Low',Normal:'Normal',Wide:'Wide',High:'High,Wide',Big:'Big,High,Wide',Giant:'Giant,Big,High,Wide'}",
      "Contrasts": "{Bright:'Bright,Vivid',Vivid:'Vivid',Default:'Default',Soft:'Soft',Dim:'Dim,Soft'}",
      "Scales": "{'50%':0.5,'60%':0.60,'75%':0.75,'90%':0.9,'100%':1,'110%':1.1,'125%':1.25,'150%':1.5,'200%':2}",
      "ShrinkStyle": "3", "ShrinkStyleType": "31", "MinBodyRows": "5", "MinLeftWidth": "100", "MinMidWidth": "100", "MinRightWidth": "100", "ShrinkStyleWidth": "Low,Normal,Wide,High,Big", "LimitScroll": "0", "StyleDependencyModifier": "1",
      "Language": "", "SyncLanguage": "1", "UseLanguages": "EN,GB,DE,FR,CA,IT,ES,PT,BR,CS,HR,RU,JP,CN,FA,KR"
   },

   // SpreadSheet configuration
   "Cfg_2" : {
      "TextColor": "#F00", "TextColors": "|#F00|red|#080|green|#00F|blue|#A33|brown|#800|maroon|#888|gray||none",
      "DefaultColor": "#FF0", "DefaultColors": "|#FF0|yellow|#0F0|lime|#0FF|aqua|#FCC|pink|#FA0|orange|#CCC|silver||none",
      "TextSize": "14", "TextSizes": "||<span style='font-size:9px;color:silver;'>size</span>|8|8|9|9|10.5|10|12|12|14|14|17|17|22|22|30|30",
      "TextFont": "'Times New Roman',serif", "TextFonts": "|'Microsoft Sans Serif',Tahoma,'Trebuchet MS',sans-serif|<span style=\"font-family:'Microsoft Sans Serif',Tahoma,'Trebuchet MS',sans-serif\">Abcdefghijk1234</span>|'Times New Roman',serif|<span style=\"font-family:'Times New Roman',serif\">Abcdefghijk1234</span>|'Courier New',monospace|<span style=\"font-family:'Courier New',monospace\">Abcdefghijk1234</span>||default",
      "TextShadow": "1", "TextShadows": "|0|<span style='text-shadow:0px 0px 5px red'>Abcde1234</span>|1|<span style='text-shadow:-1px -1px 0px red'>Abcde1234</span>|2|<span style='text-shadow:-1px -1px 0px red, -3px -3px 0px silver'>Abcde1234</span>|3|<span style='text-shadow:-1px -1px 0px red, 0px 0px 5px red'>Abcde1234</span>|4|<span style='text-shadow:-1px -1px 0px red, 0px 0px 10px red'>Abcde1234</span>|5|<span style='text-shadow:-2px -2px 0px red'>Abcde1234</span>|6|<span style='text-shadow:-3px -3px 0px red, -1px -1px 0px silver'>Abcde1234</span>|7|<span style='text-shadow:0px 0px 3px red,0px 0px 3px black,0px 0px 3px black'>Abcde1234</span>|8|<span style='text-shadow:0px 0px 5px red, -1px -1px 0px'>Abcde1234</span>|9|<span style='text-shadow:0px 0px 10px red'>Abcde1234</span>",
      "TextShadowColor": "maroon", "TextShadowColors": "|black||red||green||blue||brown||maroon||gray||yellow||lime||aqua||pink||orange||silver|||none",
      "TextLine": "1", "TextLines": "|0|solid|1|double|2|dotted|3|wavy|4|red solid|5|red double|6|red dotted|7|red wavy|8|#0DD solid|9|#0DD double|10|#0DD dotted|11|#0DD wavy|12|black solid|13|black double|14|black dotted|15|black wavy",
      "BorderColors": "|black||red||green||blue||brown||maroon||gray||yellow||lime||aqua||pink||orange||silver",
      "Indent": "1", "Indents": "||<span style='font-size:9px;color:silver;'>indent</span>|0|0|1|1|2|2|3|3|4|4|5|5|6|6|7|7|8|8|9|9|10|10|15|15|20|20|25|25|30|30|35|35|40|40|45|45|50|50",
      "Format": "1234.50", "TextFormat": "text", "NumberFormat": "general", "DateFormat": "12/31/2000",
      "Formats": {Items:[
            {Name:'general',Text:'General number or text',Type:'Float',Format:''},
            {Name:'-'},
            {Name:'@Enter',Text:'Enter custom format ...'},
            {Name:'@Custom',Text:'Custom formats',Menu:'1',Items:[
                  {Name:'-'},
                  {Name:'@Refresh',Text:'Remove unused formats'}
               ]},
            {Name:'-'},
            {Name:'text',Text:'Not formatted text',Type:'Text',Format:'@'},
            {Name:'boolean',Text:'Boolean true / false',Type:'Int',Format:'!'},
            {Name:'-'},
            {Name:'integer',Text:'Integer number',Type:'Int',Format:'0'},
            {Name:'1234.50',Text:'Float number 1234.50',Type:'Float',Format:'f'},
            {Name:'1,234.50',Text:'Float number 1,234.50',Type:'Float',Format:',0.00'},
            {Name:'float',Text:'Next float numbers',Menu:'1',Items:[
                  {Name:'1234.56',Text:'Float number 1234.5',Type:'Float',Format:'0.##'},
                  {Name:'1,234.56',Text:'Float number 1,234.5',Type:'Float',Format:',0.##'},
                  {Name:'1234.5_',Text:'Float number 1234.5_',Type:'Float',Format:'0.??'},
                  {Name:'1,234.5_',Text:'Float number 1,234.5_',Type:'Float',Format:',0.??'},
                  {Name:'<em>-1,234.50</em>',Text:'Float number <em>-1,234.50</em>',Type:'Float',Format:',0.00;[red],-0.00'},
                  {Name:'(1,234.50)',Text:'Float number (1,234.50)',Type:'Float',Format:',0.00;,(0.00)'},
                  {Name:'<em>(1,234.50)</em>',Text:'Float number <em>(1,234.50)</em>',Type:'Float',Format:',0.00;[red],(0.00)'},
                  {Name:'-'},
                  {Name:'1234.5000',Text:'Float number 1234.5678',Type:'Float',Format:'r'},
                  {Name:'1234.5678',Text:'Float number 1234.5',Type:'Float',Format:'g'},
                  {Name:'1234.5___',Text:'Float number 1234.5___',Type:'Float',Format:'0.????'},
                  {Name:'-'},
                  {Name:'$1,234.50',Text:'Currency number $1,234.50',Type:'Float',Format:'c'},
                  {Name:'$1,234.50',Text:'Currency number -$1,234.50',Type:'Float',Format:'*ncm'},
                  {Name:'<em>-$1,234.50</em>',Text:'Currency number <em>-$1,234.50</em>',Type:'Float',Format:'*ncmr'},
                  {Name:'$(1,234.50)',Text:'Currency number ($1,234.50)',Type:'Float',Format:'*ncp'},
                  {Name:'<em>($1,234.50)</em>',Text:'Currency number <em>($1,234.50)</em>',Type:'Float',Format:'*ncpr'},
                  {Name:'-'},
                  {Name:'percent',Text:'Float percent number',Type:'Float',Format:'p'},
                  {Name:'percent int',Text:'Integer percent number',Type:'Float',Format:',0%'}
               ]},
            {Name:'-'},
            {Name:'12/31/2000',Text:'Short full date (12/31/2000)',Type:'Date',Format:'d'},
            {Name:'12/31',Text:'Short partial date (12/31)',Type:'Date',Format:'m'},
            {Name:'14:30:30',Text:'Long time (14:30:30)',Type:'Date',Format:'T'},
            {Name:'14:30',Text:'Short time (14:30)',Type:'Date',Format:'t'},
            {Name:'12/31/2000 14:30',Text:'Short date and time (12/31/2000 14:30)',Type:'Date',Format:'h'},
            {Name:'date',Text:'Next date times',Menu:'1',Items:[
                  {Name:'12/2000',Text:'Short month and year (12/2000)',Type:'Date',Format:'y'},
                  {Name:'12th December 2000',Text:'Long full date (12th December 2000)',Type:'Date',Format:'D'},
                  {Name:'12th December',Text:'Long partial date (12th December)',Type:'Date',Format:'M'},
                  {Name:'December 2000',Text:'Long month and year (December 2000)',Type:'Date',Format:'Y'},
                  {Name:'2:30:30pm',Text:'Long time am/pm (2:30:30pm)',Type:'Date',Format:'I'},
                  {Name:'2:30pm',Text:'Short time am/pm (2:30pm)',Type:'Date',Format:'i'},
                  {Name:'12/31/2000 14:30:30',Text:'Short date and long time (12/31/2000 14:30:30)',Type:'Date',Format:'H'},
                  {Name:'12/31/2000 2:30pm',Text:'Short date and time am/pm (12/31/2000 2:30pm)',Type:'Date',Format:'j'},
                  {Name:'12/31/2000 2:30:30pm',Text:'Short date and long time am/pm (12/31/2000 2:30:30pm)',Type:'Date',Format:'J'},
                  {Name:'12th December 2000 14:30',Text:'Long date and time (12th December 2000 14:30)',Type:'Date',Format:'l'},
                  {Name:'12th December 14:30:30',Text:'Long date and long time (12th December 14:30:30)',Type:'Date',Format:'L'},
                  {Name:'12th December 2000 2:30pm',Text:'Long date and time am/pm (12th December 2000 2:30pm)',Type:'Date',Format:'k'},
                  {Name:'12th December 2:30:30pm',Text:'Long date and long time am/pm (12th December 2:30:30pm)',Type:'Date',Format:'K'}
               ]}
         ]},
      "Pattern": "1",
      "Patterns": ["|0|",
         "|1|linear-gradient(to bottom,%1,%2)",
         "|2|linear-gradient(to bottom,%1,%2 50%,%1)",
         "|3|linear-gradient(to right,%1,%2)",
         "|4|linear-gradient(to right,%1,%2 50%,%1)",
         "|5|linear-gradient(to bottom right,%1,%2)",
         "|6|linear-gradient(to bottom right,%1,%2 50%,%1)",
         "|7|linear-gradient(to bottom left,%1,%2)",
         "|8|linear-gradient(to bottom left,%1,%2 50%,%1)",
         "|21|radial-gradient(at top left,%1,%2)",
         "|22|radial-gradient(at top right,%1,%2)",
         "|23|radial-gradient(at bottom left,%1,%2)",
         "|24|radial-gradient(at bottom right,%1,%2)",
         "|25|radial-gradient(%1,%2)",
         "|41|radial-gradient(circle at 1px 1px,%1 2px,transparent 2px),radial-gradient(circle at 1px 1px,%1 2px,transparent 2px);4px 4px;0px 0px,2px 2px",
         "|42|repeating-linear-gradient(45deg,transparent 0px,transparent 1.06px,%1 1.06px,%1 2.12px)",
         "|43|radial-gradient(circle at left top,%1 1px,transparent 1px),radial-gradient(circle at left top,%1 1px,transparent 1px);4px 2px;1px 0px,3px 1px",
         "|44|radial-gradient(circle at left top,%1 1px,transparent 1px),radial-gradient(circle at left top,%1 1px,transparent 1px);4px 4px;3px 0px,1px 2px",
         "|45|radial-gradient(circle at left top,%1 1px,transparent 1px),radial-gradient(circle at left top,%1 1px,transparent 1px);8px 4px;3px 2px,7px 0px",
         "|46|repeating-linear-gradient(to bottom,transparent 0px,transparent 2px,%1 2px,%1 4px)",
         "|47|repeating-linear-gradient(to right,transparent 0px,transparent 2px,%1 2px,%1 4px)",
         "|48|repeating-linear-gradient(45deg,transparent 0px,transparent 2.12px,%1 2.12px,%1 4.24px)",
         "|49|repeating-linear-gradient(135deg,transparent 0px,transparent 2.12px,%1 2.12px,%1 4.24px)",
         "|50|radial-gradient(circle at 0.5px 0.5px,%1 2px,transparent 2px),radial-gradient(circle at 0.5px 0.5px,%1 2px,transparent 2px);4px 4px;0px 0px,2px 2px",
         "|51|repeating-linear-gradient(to bottom,transparent 0px,transparent 1px,%1 1px,%1 2px),radial-gradient(circle at left top,%1 2px,transparent 2px),radial-gradient(circle at left top,%1 2px,transparent 2px);4px 4px;0px 0px,0px 0px,2px 2px",
         "|52|repeating-linear-gradient(to bottom,transparent 0px,transparent 3px,%1 3px,%1 4px)",
         "|53|repeating-linear-gradient(to right,transparent 0px,transparent 3px,%1 3px,%1 4px)",
         "|54|repeating-linear-gradient(45deg,transparent 0px,transparent 3.18px,%1 3.18px,%1 4.24px)",
         "|55|repeating-linear-gradient(135deg,transparent 0px,transparent 3.18px,%1 3.18px,%1 4.24px)",
         "|56|repeating-linear-gradient(to bottom,transparent 0px,transparent 3px,%1 3px,%1 4px),repeating-linear-gradient(to right,transparent 0px,transparent 3px,%1 3px,%1 4px)",
         "|57|repeating-linear-gradient(45deg,transparent 0px,transparent 3.18px,%1 3.18px,%1 4.24px),repeating-linear-gradient(135deg,transparent 0px,transparent 3.18px,%1 3.18px,%1 4.24px)",
         "|71|linear-gradient(to top left,transparent 0%,transparent calc(50% - 0.3px),%1 50%,transparent calc(50% + 0.3px),transparent 100%)",
         "|72|linear-gradient(to top left,transparent 0%,transparent calc(50% - 0.85px),%1 50%,transparent calc(50% + 0.85px),transparent 100%)",
         "|73|linear-gradient(to top left,transparent 0%,transparent calc(50% - 1.7px),%1 50%,transparent calc(50% + 1.7px),transparent 100%)",
         "|74|linear-gradient(to top left,transparent 0%,transparent calc(50% - 2.55px),%1 50%,transparent calc(50% + 2.55px),transparent 100%)",
         "|81|linear-gradient(to top right,transparent 0%,transparent calc(50% - 0.3px),%1 50%,transparent calc(50% + 0.3px),transparent 100%)",
         "|82|linear-gradient(to top right,transparent 0%,transparent calc(50% - 0.85px),%1 50%,transparent calc(50% + 0.85px),transparent 100%)",
         "|83|linear-gradient(to top right,transparent 0%,transparent calc(50% - 1.7px),%1 50%,transparent calc(50% + 1.7px),transparent 100%)",
         "|84|linear-gradient(to top right,transparent 0%,transparent calc(50% - 2.55px),%1 50%,transparent calc(50% + 2.55px),transparent 100%)",
         "|91|linear-gradient(to top left,transparent 0%,transparent calc(50% - 0.3px),%1 50%,transparent calc(50% + 0.3px),transparent 100%),linear-gradient(to top right,transparent 0%,transparent calc(50% - 0.3px),%1 50%,transparent calc(50% + 0.3px),transparent 100%)",
         "|92|linear-gradient(to top left,transparent 0%,transparent calc(50% - 0.85px),%1 50%,transparent calc(50% + 0.85px),transparent 100%),linear-gradient(to top right,transparent 0%,transparent calc(50% - 0.85px),%1 50%,transparent calc(50% + 0.85px),transparent 100%)",
         "|93|linear-gradient(to top left,transparent 0%,transparent calc(50% - 1.7px),%1 50%,transparent calc(50% + 1.7px),transparent 100%),linear-gradient(to top right,transparent 0%,transparent calc(50% - 1.7px),%1 50%,transparent calc(50% + 1.7px),transparent 100%)",
         "|94|linear-gradient(to top left,transparent 0%,transparent calc(50% - 2.55px),%1 50%,transparent calc(50% + 2.55px),transparent 100%),linear-gradient(to top right,transparent 0%,transparent calc(50% - 2.55px),%1 50%,transparent calc(50% + 2.55px),transparent 100%)"],

      "PatternColor": "gray", "PatternColors": "|black||red||green||blue||brown||maroon||gray||yellow||lime||aqua||pink||orange||silver|"
   },

   // Prefetch all SVG icons for Microsoft IE / Edge
   "Cfg_3" : {
      "IESvg": ["CustScroll1Right,CustScroll1Left,CustScroll1Down,CustScroll1Up,",
         "LevelButton,SpaceSelectInner,ButtonClose,PopupLeft,TabHtmlBase PopupLeft,CellImg,TagDelete,",
         "PanelMove,PanelSelect,PanelSelectOn,PanelDelete,PanelCopy,CellHeaderPanel PanelSelect,CellHeaderPanel PanelSelectOn,CellHeaderPanel PanelCopy,FastPanel,",
         "Width1,Width2,Width3,Width4,Width1T,Width2T,Width3T,Width4T,",
         "1E,1C,TreeRev 1E,TreeRev 1C,E,C,TreeRev E,TreeRev C,D0,D1,D2,D3,D4,NE,Rtl NE,NC,NTreeRev.NC,ND0,ND0R,ND1,ND1R,ND2,ND2R,ND3,ND3R,ND4,ND4R,",
         "ExpandLeft,HeaderRow ExpandLeft,ExpandTreeLeft,ExpandColLeft,ExpandColTreeLeft,CollapseLeft,HeaderRow CollapseLeft,CollapseRevLeft,CollapseTreeLeft,CollapseTreeRevLeft,CollapseColLeft,CollapseColRevLeft,",
         "DateLeft,DefaultsLeft,EnumLeft,FileLeft,ClearLeft,EnumHeaderLeft,Check0Left,Check1Left,Check2Left,",
         "Filter0,Filter1,Radio0Left,Radio1Left,Radio2Left,Radio3Left,Bool0,Bool1,BoolX,Bool2,Bool3,Bool0Space,Bool1Space,BoolXSpace,Bool2Space,Bool3Space,",
         "Filter0Left,Filter1Left,Filter2Left,Filter3Left,Filter4Left,Filter5Left,Filter6Left,Filter7Left,Filter8Left,Filter9Left,Filter10Left,Filter11Left,Filter12Left,",
         "Sort0Left,Sort1Left,Sort2Left,Sort3Left,Sort4Left,Sort5Left,Sort6Left,",
         "DragColInsideTop,DragColOutsideTop,DragColInsideBottom,DragColOutsideBottom,DragRowLeft,DragRowRight,",
         "MenuItemBorder,MenuItemBorderAll,MenuItemBorderO15,MenuItemBorderI3,MenuItemBorderI2,MenuItemBorderI1,MenuItemBorderO1,MenuItemBorderO2,MenuItemBorderO4,MenuItemBorderO8,MenuItemBorderO5,MenuItemBorderO10,",
         "MenuClose,MenuCheckedIconLeft,MenuUncheckedIconLeft,MenuCheckedRadioLeft,MenuUncheckedRadioLeft,",
         "MenuExpandedIcon,MenuCollapsedIcon,MenuNextIcon,MenuNextIconRtl,MenuNextIconDown,MenuEnum,MenuEnumHeaderLeft,EnumControl,",
         "PickMYDown,PickMYUp,PickBL,PickBR,PickEmpty,Pick2BL,Pick2BR,",
         "ChartPoint1,ChartPoint2,ChartPoint3,ChartPoint4,ChartPoint5,ChartPoint6,ChartPoint7,ChartPoint8"],
      "IESvgTool": ["Save,Reload,Repaint,Repaint1,Print,ExportPDF,Export,Import,Undo,Redo,Add,AddChild,AddCol,Join,Split,Outdent,Indent,Sort,Sort1,Calc,Calc1,WinScroll,WinScroll1,",
         "ExpandAll,CollapseAll,Columns,Cfg,Lock0,Lock1,Lock2,Lock3,Help,Debug,ResizeGrid,ResizeGridRtl,",
         "PagerFirst,PagerNext,PagerPrev,PagerLast,Correct,Correct1,ZoomIn,ZoomOut,ZoomFit,",
         "AddImage,SetLink,Left,Left1,Center,Center1,Right,Right1,Top,Top1,Middle,Middle,Bottom,Bottom1,Bold,Bold1,Italic,Italic1,Underline,Underline1,Strike,Strike1,",
         "RotateLeft,RotateLeft1,NoRotate,NoRotate1,RotateRight,RotateRight1,WrapText,WrapText1,ClearStyle,ColorText,ColorBackground,ColorShadow,",
         "Border,BorderAll,BorderO15,BorderI3,BorderI2,BorderI1,BorderO1,BorderO2,BorderO4,BorderO8,BorderO5,BorderO10"],
      "IESvgGantt": ["DepArrow00LeftHover,DepArrow10LeftHover,DepArrow20LeftHover,DepArrow30LeftHover,DepArrow00RightHover,DepArrow10RightHover,DepArrow20RightHover,DepArrow30RightHover,",
         "NbspOut,JoinLeft div,JoinLeft.JoinRight div,JoinLeftNbsp div,JoinLeftNbsp.JoinRightNbsp div,JoinLeft.JoinRightNbsp div,JoinLeftNbsp.JoinRight div,",
         "RedIn0Crit,RedIn0Err,LockedIn,LockedIn CompleteGauge,InDisabled,OutLeft,OutRight,InLeft,InRight,ManualStart,ManualEnd,Flag,FlagHover,DragPointer,",
         "Point1Hover,Point2,Point3,Point4,Point5,Point6,Point7,Point8,",
         "MinStart,MaxStart,MinEnd,MaxEnd,MinStartHover,MaxStartHover,MinEndHover,MaxEndHover"],
      "IESvgFGantt": "Nbsp,JoinLeft,JoinLeft.JoinRight,JoinLeftNbsp,JoinLeftNbsp.JoinRightNbsp,JoinLeft.JoinRightNbsp,JoinLeftNbsp.JoinRight",
      "IESvgGanttArrow": "Left,Right",
      "IESvgGanttMilestone": ["*,Sel*,*Hover,Sel*Hover,Run*,RunSel*,Run*Hover,RunSel*Hover,*Error,Sel*Error,*ErrorHover,Sel*ErrorHover,",
         "*0,Sel*0,*0Hover,Sel*0Hover,*100,Sel*100,*100Hover,Sel*100Hover,*0Crit,Sel*0Crit,*0CritHover,Sel*0CritHover,*0Err,Sel*0Err,*0ErrHover,Sel*0ErrHover,",
         "Stop*,StopSel*,Stop*Hover,StopSel*Hover,*Disabled,Sel*Disabled,*DisabledHover,Sel*DisabledHover,",
         "Group*,GroupSel*,Group*Hover,GroupSel*Hover,Group*0,GroupSel*0,Group*0Hover,GroupSel*0Hover,",
         "Group*0Crit,GroupSel*0Crit,Group*0CritHover,GroupSel*0CritHover,Group*0Err,GroupSel*0Err,Group*0ErrHover,GroupSel*0ErrHover,",
         "Black*,Red*,Blue*,Green*,Fuchsia*,Yellow*,Aqua*,Silver*,Orange*,Lime*,",
         "BlackSel*,RedSel*,BlueSel*,GreenSel*,FuchsiaSel*,YellowSel*,AquaSel*,SilverSel*,OrangeSel*,LimeSel*"]
   },

   // Colors and other settings for exporting Gantt chart to xlsx
   "GanttExport" : {
      "Shape": "roundRect", "MilestoneShape": "diamond",
      "Main": "8ACCCB", "Disabled": "D7D7D7", "Empty": "", "DisabledBorder": "404040,1,sysDot",
      "Border": "F6F6F6", "EmptyBorder": "", "SelectedBorder": "0000FF,1.5,dash",
      "Box": "8ACCCB", "Solid": "EDD933", "Fixed": "C7C7C7", "Left": "C7C7C7", "Right": "C7C7C7", "BoundStart": "FACCAE", "Bound": "FACCAE", "EndStart": "FACCAE", "End": "FACCAE",
      "Unknown": "000000", "Nbsp": "EAEAEA", "Error": "FF6959", "ErrorOpacity": "0.5", "Milestone": "0087BD", "Stop": "545859", "None": "EEEEEE", "Html": "EEEEEE", "Void": "EEEEEE",
      "ContainerL1": "9ECB7F", "ContainerL2": "D7CCBC", "ContainerL3": "AAAAF7", "ContainerL1Shape": "rect", "ContainerL2Shape": "rect", "ContainerL3Shape": "rect",
      "Bar0": "82D0F4", "Err0": "FF4444", "Crit0": "FFCC2B", "Bar50": "8ACCCA", "Err50": "CC2222", "Crit50": "F9B256", "BarGauge": "739B79", "Bar100": "B6D867",
      "Group": "666666", "Group0": "666666", "GroupErr0": "AA4444", "GroupCrit0": "AA8844", "Group50": "AAAAAA", "GroupErr50": "AA4444", "GroupCrit50": "AA8844", "GroupGauge": "888888", "Group100": "CCCCCC",
      "Red": "CC0000", "Red0": "FF8888", "Blue": "3399FF", "Blue0": "55CCFF", "Green": "009900", "Green0": "66DD66", "Fuchsia": "CC00CC", "Fuchsia0": "EE66EE", "Aqua": "33CCCC", "Aqua0": "88FFFF", "Lime": "66FF00", "Lime0": "CCFFCC",
      "Maroon": "800000", "Maroon0": "CC8888", "Navy": "000080", "Navy0": "8888CC", "Olive": "808000", "Olive0": "CCCC88", "Orange": "FF9900", "Orange0": "FFCC88", "Purple": "00080", "Purple0": "CC88CC",
      "Silver": "CCCCCC", "Silver0": "E0E0E0", "Teal": "008080", "Teal0": "88CCCC", "Yellow": "CCCC00", "Yellow0": "EEEE88", "Black": "000000", "Black0": "666666", "Gray": "999999", "Gray0": "BBBBBB", "White": "E0E0E0", "White0": "F0F0F0",
      "RedText": "FFFFFF", "GreenText": "FFFFFF", "BlueText": "FFFFFF", "FuchsiaText": "FFFFFF", "NavyText": "FFFFFF", "OliveText": "FFFFFF", "MaroonText": "FFFFFF", "PurpleText": "FFFFFF", "TealText": "FFFFFF", "BlackText": "FFFFFF",
      "Flag": "8F8D8E", "FlagHeight": "11", "FlagWidth": "12", "FlagTop": "2", "FlagText": "FEF0C2", "FlagSpace": "7",
      "FlagShape": "<a:prstGeom prst=\"wedgeEllipseCallout\"><a:avLst><a:gd name=\"adj1\" fmla=\"val 595\"/><a:gd name=\"adj2\" fmla=\"val 150000\"/></a:avLst></a:prstGeom>",
      "PointHeight": "11", "PointTop": "4", "PointCustomTop": "1", "PointShape": "ellipse", "Point1": "000000", "Point2": "CC0000", "Point3": "3399FF", "Point4": "009900", "Point5": "CC00CC", "Point6": "CCCC00", "Point7": "33CCCC", "Point8": "CCCCCC",
      "MinStart": "8F8D8E", "MinStartShape": "<a:xfrm flipH=\"1\"/><a:prstGeom prst=\"flowChartDelay\"/>", "MinStartWidth": "6", "MinStartTop": "3",
      "MaxStart": "8F8D8E", "MaxStartShape": "<a:xfrm flipH=\"1\"/><a:prstGeom prst=\"chevron\"/>", "MaxStartWidth": "7", "MaxStartTop": "3",
      "MaxEnd": "8F8D8E", "MaxEndShape": "flowChartDelay", "MaxEndWidth": "6", "MaxEndTop": "3",
      "MinEnd": "8F8D8E", "MinEndShape": "chevron", "MinEndWidth": "7", "MinEndTop": "3",
      "Mark": "888800", "Mark1": "FF0000", "Mark2": "00FF00", "Mark3": "FFFF00", "Mark4": "000000", "Mark5": "AAAAAA", "Mark15": "FF00FF", "MarkA": "", "MarkB": "", "MarkC": "", "MarkD": "",
      "Mark6": "FF88FF", "Mark7": "00FF00", "Mark8": "AAAAAA", "Mark9": "FF88FF", "Mark10": "00FF00", "Mark11": "AAAAAA", "Mark12": "FF88FF", "Mark13": "00FF00", "Mark14": "AAAAAA", "Mark16": "FF88FF", "Mark17": "00FF00", "Mark18": "AAAAAA",
      "MarkShape": "rect", "MarkBorder": "0", "Mark15Border": "FF00FF", "MarkHeight": "19",
      "MarkLineShape": "line", "MarkLineBorder": "FF00FF,1.5",
      "BackShape": "rect", "BackBorder": "0",
      "Exclude": "000000", "ExcludeOpacity": "0.04", "ExcludeHidden": "000000", "ExcludeHiddenOpacity": "0.04",
      "BackRow": "FFFFFF", "Back0": "FFFFFF", "Back1": "E8E8E8", "Back2": "D0D0D0", "Back3": "B8B8B8", "Back4": "A0A0A0", "Back5": "888888", "Back6": "707070", "Back7": "585858", "Back8": "404040", "Back9": "282828", "Back10": "101010",
      "BackBase": "FF9900", "BackBaseWidth": "2", "BackBaseAuto": "FF9900", "BackBaseAutoWidth": "1", "BackFinish": "FF9900", "BackFinishWidth": "2", "BackFinishAuto": "FF9900", "BackFinishAutoWidth": "1", "BackWidth": "1",
      "BackAqua": "00FFFF", "BackBlack": "000000", "BackBlue": "0000FF", "BackFuchsia": "FF00FF", "BackGray": "808080", "BackGreen": "008000", "BackLime": "00FF00", "BackMaroon": "800000", "BackNavy": "000080",
      "BackOlive": "808000", "BackOrange": "FFA500", "BackPurple": "800080", "BackRed": "FF0000", "BackSilver": "C0C0C0", "BackTeal": "008080", "BackWhite": "FFFFFF", "BackYellow": "FFFF00",
      "Dep0": "2155A1", "Dep1": "88DD88", "Dep2": "FFCC88", "Dep3": "AAAAAA", "Dep4": "FFBBFF", "Dep5": "BBFFFF", "Dep6": "BBFFBB", "Dep7": "CCCC00", "Dep8": "DDDDDD", "Dep9": "CC0000",
      "DepShape0": "", "DepShape1": "", "DepShape2": "dbl", "DepShape3": "dbl",
      "DepWidth0": "1.25", "DepWidth1": "2", "DepWidth2": "2.5", "DepWidth3": "3.5",
      "DepArrow0": "triangle,med,med", "DepArrow1": "triangle,med,lg", "DepArrow2": "arrow,sm,med", "DepArrow3": "stealth,med,med",
      "DepArrowWidth0": "16", "DepArrowWidth1": "22", "DepArrowWidth2": "22", "DepArrowWidth3": "22",
      "DepStub0": "oval,sm,sm", "DepStub1": "oval,sm,sm", "DepStub2": "oval,sm,sm", "DepStub3": "oval,sm,sm",
      "DepLag0": "sysDot", "DepLag1": "sysDot", "DepLag2": "sysDot", "DepLag3": "sysDot",
      "DepSpace0": "0", "DepSpace1": "-1", "DepSpace2": "-2", "DepSpace3": "-2",
      "Avail": "46C3BD", "AvailBorder": "26A39D", "AvailOpacity": "0.7", "AvailNeg": "FF9999", "AvailNegBorder": "FF0000", "AvailNegOpacity": "0.7", "AvailAxis": "000000", "AvailAxisBorder": "0", "AvailAxisOpacity": "0.2",
      "AvailRed": "FF522A", "AvailRedBorder": "F84926", "AvailMaroon": "BB7777", "AvailMaroonBorder": "AA6666", "AvailOrange": "FFDD88", "AvailOrangeBorder": "EECC77", "AvailYellow": "DDDDAA", "AvailYellowBorder": "CCCC88",
      "AvailOlive": "CCCC88", "AvailOliveBorder": "BBBB77", "AvailLime": "88FF88", "AvailLimeBorder": "77EE77", "AvailGreen": "09D26A", "AvailGreenBorder": "03B45C", "AvailAqua": "88FFFF", "AvailAquaBorder": "88DDDD",
      "AvailTeal": "66CCCC", "AvailTealBorder": "55BBBB", "AvailBlue": "9999FF", "AvailBlueBorder": "8888EE", "AvailNavy": "6666CC", "AvailNavyBorder": "5555BB", "AvailFuchsia": "FF88FF", "AvailFuchsiaBorder": "EE77EE",
      "AvailPurple": "CC66CC", "AvailPurpleBorder": "BB55BB", "AvailBlack": "000000", "AvailBlackBorder": "AAAAAA", "AvailGray": "AAAAAA", "AvailGrayBorder": "999999", "AvailSilver": "DDDDDD", "AvailSilverBorder": "CCCCCC",
      "AvailWhite": "F8F8F8", "AvailWhiteBorder": "CCCCCC",
      "AvailTextText": "005555", "AvailTextBorder": "0", "AvailTextTextSize": "9", "AvailTextTextEffects": "<a:glow rad=\"63500\"><a:srgbClr val=\"FFFFFF\"><a:lumMod val=\"95000\"/><a:alpha val=\"80000\"/></a:srgbClr></a:glow>",
      "AvailTextNegText": "FF0000", "AvailTextNegBorder": "0", "AvailTextNegTextSize": "9", "AvailTextTextNegEffects": "<a:glow rad=\"63500\"><a:srgbClr val=\"FFFFFF\"><a:lumMod val=\"95000\"/><a:alpha val=\"80000\"/></a:srgbClr></a:glow>",
      "AvailTextRedText": "F84926", "AvailTextMaroonText": "800000", "AvailTextOrangeText": "FFA500", "AvailTextYellowText": "888800", "AvailTextOliveText": "808000", "AvailTextLimeText": "00DD00",
      "AvailTextGreenText": "03B45C", "AvailTextAquaText": "88DDDD", "AvailTextTealText": "008080", "AvailTextBlueText": "0000FF", "AvailTextNavyText": "000080", "AvailTextFuchsiaText": "FF00FF",
      "AvailTextPurpleText": "800080", "AvailTextBlackText": "AAAAAA", "AvailTextGrayText": "808080", "AvailTextSilverText": "C0C0C0", "AvailTextWhiteText": "CCCCCC",
      "Padding": "0,4,0,4", "TextSize": "11", "Text": "000000",
      "Span": "3"
   },

   // Keys and mouse actions
   "Actions" : {
      "OnDragOverCell": "CursorDrag",
      "OnMouseOverContent": "ShowHint", "OnMouseOverCaption": "ShowHint",
      "OnMouseOverHeaderLeft": "CursorResize", "OnMouseOverHeaderRight": "CursorResize", "OnMouseOverPagerHeaderLeft": "CursorResize", "OnMouseOverPagerHeaderRight": "CursorResize",
      "OnMouseOverHScrollLeft": "CursorResize", "OnMouseOverHScrollRight": "CursorResize",
      "OnMouseOverLeftSplitter": "CursorResize", "OnMouseOverRightSplitter": "CursorResize",
      "OnMouseOverHeaderTop": "CursorResizeRow", "OnMouseOverHeaderBottom": "CursorResizeRow",
      "OnMouseOverButton": "CursorPointer",
      "OnMouseOverButtonEmpty": "CursorDefault",
      "OnMouseOverPanel": "CursorPointer",
      "OnMouseOverSide": "CursorPointer",
      "OnMouseOverSideDefaults": "CursorPointer",
      "OnMouseOverSideFile": "CursorPointer",
      "OnMouseOverSideClear": "CursorPointer",
      "OnMouseOverPanelMove": "CursorMove", "OnMouseOverPanelMoveAll": "CursorMove", "OnMouseOverPanelColMove": "CursorMove", "OnMouseOverPanelColMoveAll": "CursorMove",
      "OnMouseOverPanelOff": "CursorDefault",
      "OnMouseOverSpaceOff": "CursorDefault",
      "OnMouseOverEditable": "CursorText",
      "OnMouseOverEditBool": "CursorPointer", "OnMouseOverEditEnum": "CursorPointer", "OnMouseOverEditRadio": "CursorPointer",
      "OnMouseOverSort": "CursorPointer", "OnMouseOverSortUp": "CursorPointer", "OnMouseOverSortDown": "CursorPointer",
      "OnMouseOverExpand": "CursorPointer", "OnMouseOverTree": "CursorDefault",
      "OnMouseOverNoFocus": "CursorDefault", "OnMouseOverReadOnly": "CursorDefault", "OnMouseOverNothing": "CursorDefault",
      "OnMouseOverResize": "CursorResizeGrid",

      "OnMouseDownButton": "ButtonDown", "OnMouseUpButton": "ButtonUp",

      "OnClickCell": "CancelLinkEdit OR ShowLinkA,FocusEdit",
      "OnDblClickCell": "CancelLinkEdit,Focus AND StartEdit",
      "OnClickNoFocus": "AcceptEdit,ChangeFocusRow OR ChangeFocusCol,0",
      "OnClickEmpty": "AcceptEdit",
      "OnRightClick": "ShowPopupMenu",
      "OnRightClickCell": "100",
      "OnCtrlClickCell": "ChooseCellInsert OR ShowLink OR DeselectCell OR SelectCell OR DeselectRow OR SelectRow,1",
      "OnShiftClickCell": "ChooseCellReplaceAll OR FocusCellRange OR InvertCellRangeFirst OR InvertRowRangeFirst,1",
      "OnCtrlClickNoFocus": "ChooseCellInsert OR ShowLink",
      "OnShiftClickNoFocus": "ChooseCellReplaceAll",
      "OnClickNothing": "CloseDialog", "OnClickOther": "CloseDialog,AcceptEdit,0",

      "OnClickSort": "SortAsc OR SortDesc", "OnClickSortUp": "SortAsc", "OnClickSortDown": "SortDesc",
      "OnCtrlClickSort": "SortAscAdd OR SortDescAdd", "OnCtrlClickSortUp": "SortAscAdd", "OnCtrlClickSortDown": "SortDescAdd",

      "OnClickButtonSave": "Validate AND Save",
      "OnClickButtonReload": "Reload",
      "OnClickButtonRepaint": "RenderPages",
      "OnClickButtonWinScroll": "ChangeWinScroll",
      "OnClickButtonDefSort": "DefaultSort",
      "OnClickButtonCalc": "CalcOn OR CalcOff",
      "OnClickButtonSort": "SortOn OR SortOff",
      "OnClickButtonPrint": "Print",
      "OnClickButtonExport": "Export",
      "OnClickButtonImport": "Import",
      "OnClickButtonExportPDF": "ExportPDF",
      "OnClickButtonExpandAll": "ExpandAll",
      "OnClickButtonCollapseAll": "CollapseAll",
      "OnClickButtonUndo": "Undo",
      "OnClickButtonRedo": "Redo",
      "OnClickButtonAdd": "ShowMenu OR AddRow OR AddRowEnd",
      "OnClickButtonAddChild": "ShowMenu OR AddChildEnd",
      "OnClickButtonAddCol": "ShowMenu OR AddCol OR AddColEnd",
      "OnClickButtonJoin": "Span OR AutoSpan",
      "OnClickButtonSplit": "Split",
      "OnClickButtonOutdent": "Outdent",
      "OnClickButtonIndent": "Indent",

      "OnClickButtonAddImage": "OpenImage",
      "OnClickButtonSetLink": "SetLink",
      "OnClickButtonLeft": "AlignLeft OR NoAlign",
      "OnClickButtonCenter": "AlignCenter OR NoAlign",
      "OnClickButtonRight": "AlignRight OR NoAlign",
      "OnClickButtonTop": "VertAlignTop OR NoVertAlign",
      "OnClickButtonMiddle": "VertAlignMiddle OR NoVertAlign",
      "OnClickButtonBottom": "VertAlignBottom OR NoVertAlign",
      "OnClickButtonBold": "BoldOff OR BoldOn",
      "OnClickButtonItalic": "ItalicOff OR ItalicOn",
      "OnClickButtonUnderline": "UnderlineOff OR UnderlineOn",
      "OnClickButtonStrike": "StrikeOff OR StrikeOn",
      "OnClickButtonRotateLeft": "RotateLeft",
      "OnClickButtonNoRotate": "NoRotate",
      "OnClickButtonRotateRight": "RotateRight",
      "OnClickButtonWrapText": "WrapOn OR WrapOff",
      "OnClickButtonClearStyle": "ClearStyle",
      "OnClickButtonColorText": "SetTextColor",
      "OnClickButtonColorShadow": "SetTextShadowColor",
      "OnClickButtonColorBackground": "SetColor",
      "OnClickButtonBorder": "SetBorder",

      "OnClickButtonCfg": "ShowCfg",
      "OnClickButtonColumns": "ShowColumns",
      "OnClickButtonLock": "Lock",
      "OnClickButtonHelp": "ShowHelp",
      "OnClickButtonDebug": "ShowDebug",
      "OnClickButton": "Button",
      "OnDblClickResize": "GridResizeDefault",

      "OnClickButtonCorrect": "CorrectAllDependencies",
      "OnClickButtonZoomFit": "ZoomFit",
      "OnClickButtonZoomIn": "ZoomIn",
      "OnClickButtonZoomOut": "ZoomOut",

      "OnClickSideDefaults": "Focus,ShowDefaults",
      "OnClickSideFile": "Focus,ShowFile",
      "OnClickSideClear": "Focus,ClearValue",
      "OnClickSideDate": "Focus,ShowCalendar",
      "OnClickSideDates": "Focus,ShowDates",
      "OnClickSideFilter": "Focus,ShowFilterMenu",
      "OnClickSideCheck": "Focus,SetChecked",
      "OnDblClickSideCheck": "SetChecked",
      "OnClickSideExpand": "Focus,ExpandCell",
      "OnDblClickSideExpand": "1",
      "OnClickExpand": "Focus,Expand OR Collapse",
      "OnDblClickExpand": "1",
      "OnClickLevels": "ShowTreeLevel",
      "OnClickSideLevel": "ShowColTreeLevel",
      "OnDblClickButton": "Focus AND StartEdit",
      "OnCtrlClickButton": "DeleteTab",
      "OnClickClose": "DeleteTab",
      "OnDblClickImg": "RestoreImage",
      "OnClickTagDelete": "DeleteTag",

      "OnClickPanelSelect": "DeselectRow OR SelectRow",
      "OnClickPanelSelectAll": "DeselectAll OR SelectAll",
      "OnCtrlClickPanelSelectAll": "InvertAll",
      "OnClickPanelDelete": "DeleteRow OR UndeleteRow",
      "OnClickPanelDeleteAll": "UndeleteSelected OR DeleteSelected",
      "OnClickPanelCopy": "ShowMenu",
      "OnClickPanelCopyAll": "ShowMenu OR AddRow OR AddRowEnd",
      "OnClickPanelColSelect": "DeselectCol OR SelectCol OR DeselectColCells OR SelectColCells",
      "OnClickPanelColSelectAll": "DeselectAllCols OR SelectAllCols",
      "OnClickPanelColDelete": "DeleteCol OR UndeleteCol",
      "OnClickPanelColDeleteAll": "UndeleteSelectedCols OR DeleteSelectedCols",
      "OnClickPanelColCopy": "ShowMenu",
      "OnClickPanelColCopyAll": "ShowMenu OR AddCol OR AddColEnd",
      "OnClickSideIcon": "IconClick",
      "OnClickSideButton": "ButtonClick",
      "OnClickSidePopup": "ButtonClick",
      "OnClickPanelGrouped": "GroupOn OR GroupOff",
      "OnClickPanelFiltered": "FilterOn OR FilterOff",
      "OnClickPanelSearched": "SearchOn OR SearchOff",

      "OnClickEditEnum": "Focus AND StartEdit",
      "OnClickEditBool": "Focus,Grid.EditMode?1:ChangeBool",
      "OnClickEditRadio": "Focus,Grid.EditMode?1:ChangeRadio",

      "OnClickOutside": "Blur",
      "OnClickPagerPage": "ShowPage",

      "OnDragHeaderLeft": "ColResize",
      "OnDragHeaderRight": "ColResize",
      "OnDragPagerHeaderLeft": "ColResize",
      "OnDragPagerHeaderRight": "ColResize",
      "OnDragHeaderTop": "RowResize",
      "OnDragHeaderBottom": "RowResize",
      "OnDragHeader": "ColMoveSelected OR ColMove",
      "OnCtrlDragHeader": "ColCopySelected OR ColCopy",
      "OnDragDropCol": "DropColMove",
      "OnDragButton": "TabMove",
      "OnRightDragButton": "TabCopy",
      "OnCtrlDragButton": "TabCopy",
      "OnDragPanelMove": "DragRow",
      "OnRightDragPanelMove": "DragCopy",
      "OnCtrlRightDragPanelMove": "DragCopyChildren",
      "OnDragPanelSelect": "InvertOddRows",
      "OnDragPanelColSelect": "InvertOddCols",
      "OnDragRow": "ChooseCellsReplaceAll OR FocusCells OR DragSelected OR DragRow OR InvertCellsFirst OR InvertRowsFirst",
      "OnRightDragRow": "Scroll",
      "OnDragImg": "DragImage",
      "OnDragResize": "GridResize",
      "OnCtrlDragRow": "ChooseCellsInsert OR InvertCellsFirst OR DragSelectedCopy OR DragCopy OR InvertRowsFirst",
      "OnShiftDragRow": "FillCells",
      "OnDragCorner": "FocusFillRowCol",
      "OnDragHScrollLeft": "SectionResize",
      "OnDragHScrollRight": "SectionResize",
      "OnDragLeftSplitter": "SectionResize",
      "OnDragRightSplitter": "SectionResize",

      "OnDragGantt": "ResizeGanttMain OR ResizeGanttRun OR MoveGanttMainFirst OR MoveGanttRun OR MoveGanttFlag OR MoveGanttPoint OR MoveGanttConstraint OR MoveGanttLine OR CreateGanttBar OR DragGanttDependency OR 1",
      "OnRightDragGantt": "SelectGanttRunRect OR ResizeGanttRun OR MoveGanttRun OR MoveGanttMain OR Scroll OR 1",
      "OnCtrlClickGantt": "DeleteGanttConstraint OR DeleteGanttFlag OR DeleteGanttPoint OR DeleteGanttMain OR DeleteGanttRun OR DeleteGanttRunContainerOnly OR DeleteGanttDependency OR DeleteGanttBase OR DeleteGanttFinish OR 1",
      "OnDblClickGantt": "SelectGanttRun OR SelectGanttRunContainer OR EditGanttFlag OR EditGanttResource OR EditGanttText OR EditGanttRun OR EditGanttRunTip OR EditGanttDependencyLag OR NewGanttMilestone OR NewGanttFlag OR NewGanttPoint",
      "OnShiftClickGantt": "SplitGanttMain OR SplitGanttRun",
      "OnCtrlRightClickGantt": "SetGanttPercent OR SetGanttRunPercent",
      "OnShiftRightClickGantt": "EditGanttPercent OR EditGanttRunPercent",
      "OnRightClickGantt": "GanttMenu,1",
      "OnDragGanttHeader": "ZoomGantt,1", "OnClickGanttHeader": "ZoomHeader OR ZoomIn", "OnRightClickGanttHeader": "UndoZoom OR ZoomOut,1", "OnRightDragGanttHeader": "SelectGanttRunRange,1",

      "OnClick1Cell": "HoverGantt,CancelLinkEdit OR ShowLink,FocusEdit",
      "OnClick2Cell": "ShowPopupMenu OR Focus AND StartEdit",
      "OnClick2Resize": "GridResizeDefault",
      "OnLongClick1": "ShowPopupMenu OR ShowHintStatic",
      "OnLongClick1Img": "Focus,ShowPopupMenu",
      "OnClick1Img": "Focus,ShowPopupMenu",
      "OnDrag1Row": "ChooseCellsReplaceAll OR FocusCells OR DragSelected OR DragRow", "OnDrag2Row": "0", "OnDrag3Row": "0",
      "OnDrag2Grid": "0",
      "OnDrag2PanelMove": "DragCopy",
      "OnDrag3PanelMove": "DragCopyChildren",
      "OnDrag2Pager": "ScrollPager",

      "OnDrag1Gantt": "ResizeGanttMain OR ResizeGanttRun OR MoveGanttMainFirst OR MoveGanttRun OR MoveGanttFlag OR MoveGanttPoint OR MoveGanttConstraint OR MoveGanttLine OR CreateGanttBar OR DragGanttDependency",
      "OnDrag2Gantt": "0",
      "OnDrag3Gantt": "0",
      "OnClick1Gantt": "GanttMenu",
      "OnClick2Gantt": "0",
      "OnClick3Gantt": "0",
      "OnDrag1GanttHeader": "100", "OnDrag2GanttHeader": "PinchZoomGantt,1", "OnClick1GanttHeader": "GanttMenu", "OnLongClick1GanttHeader": "UndoZoom OR ZoomOut,1", "OnMouseDown2GanttHeader": "1",

      "OnKey": "!StartEditEmpty", "OnBackspace": "!StartEditEmptyDeleteTag",

      "OnCtrlEnter": "Expand OR Collapse",
      "OnEnter": "ChangeBool OR ChangeRadioRightCycle OR StartEdit OR ShowLink OR ShowDefaults OR ShowFile OR ShowCalendar OR EditGanttResource",
      "OnF2": "StartEdit",

      "OnTab": "TabRight?1:!Grid.TabStop", "OnShiftTab": "TabLeft?1:!Grid.TabStop",
      "OnUp": "GoUp,1", "OnDown": "GoDown,1", "OnLeft": "GoLeft,1", "OnRight": "GoRight,1",
      "OnShiftUp": "FocusUp,1", "OnShiftDown": "FocusDown,1", "OnShiftLeft": "FocusLeft,1", "OnShiftRight": "FocusRight,1",
      "OnHome": "GoFirst,1", "OnEnd": "GoLast,1", "OnPageUp": "PageUp,1", "OnPageDown": "PageDown,1",

      "OnTabEnum": "TabRightEdit AND StartEdit?1:!Grid.TabStop", "OnShiftTabEnum": "TabLeftEdit AND StartEdit?1:!Grid.TabStop",
      "OnTabEdit": "TabRightEdit AND StartEdit?1:!Grid.TabStop", "OnShiftTabEdit": "TabLeftEdit AND StartEdit?1:!Grid.TabStop",
      "OnUpEdit": "GoUpEdit AND StartEdit,1", "OnDownEdit": "GoDownEdit AND StartEdit,1",
      "OnCtrlLeft": "ChangeRadioLeft", "OnCtrlRight": "ChangeRadioRight",
      "OnEnterEdit": "AcceptEdit,1", "OnEscEdit": "CancelEdit",
      "OnCtrlEnterEdit": "AcceptEdit", "OnAltEnterEdit": "AcceptEdit", "OnShiftEnterEdit": "AcceptEdit",
      "OnSpaceEdit": "ChangeBool",
      "OnF4Edit": "SwitchRowColAbsolute",

      "OnCtrlBEdit": "BoldOn", "OnCtrlIEdit": "ItalicOn", "OnCtrlUEdit": "UnderlineOn",
      "OnCtrlRightBracketEdit": "VertAlignBottom", "OnCtrlLeftBracketEdit": "VertAlignTop",
      "OnCtrlCommaEdit": "DecreaseTextSize", "OnCtrlPointEdit": "IncreateTextSize",
      "OnCtrlShiftA": "UpperCase", "OnCtrlShiftK": "LowerCase",

      "OnSpace": "SelectRow OR DeselectRow", "OnCtrlSpace": "SelectAll OR DeselectAll",
      "OnDel": "DeleteRow OR UndeleteRow,1", "OnCtrlDel": "UndeleteSelected OR DeleteSelected,1",
      "OnIns": "AddRow", "OnCtrlIns": "AddChildEnd", "OnShiftIns": "CopyRow", "OnShiftCtrlIns": "CopyTree",
      "OnCtrlDown": "ShowDefaults OR ShowFile OR ShowFilterMenu OR ShowCalendar OR ButtonClick",
      "OnCtrlZ": "Undo", "OnCtrlY": "Redo",
      "OnCtrlC": "Copy,0", "OnCtrlX": "Exclude,0", "OnCtrlV": "Paste,0",
      "OnMetaZ": "Undo", "OnMetaY": "Redo",
      "OnMetaC": "Copy,0", "OnMetaX": "Exclude,0", "OnMetaV": "Paste,0",
      "OnCtrlAltD": "DebugUndo",

      "KeyCodes1": "Space=32,Enter=13,Esc=27,Backspace=8,Tab=9",
      "KeyCodes2": "Tilde=192,Minus=189,Equal=187,Backslash=220,LeftBracket=219,RightBracket=221",
      "KeyCodes3": "Semicolon=186,Apostrophe=222,Comma=188,Point=190,Slash=191",
      "KeyCodes4": "F1=112,F2=113,F3=114,F4=115,F5=116,F6=117,F7=118,F8=119,F9=120,F10=121,F11=122,F12=123",
      "KeyCodes5": "Ins=45,Del=46,Home=36,End=35,PageUp=33,PageDown=34,Up=38,Down=40,Left=37,Right=39,Pause=19",
      "KeyCodes6": "NumDivide=111,NumStar=106,NumMinus=109,NumPlus=107,NumPoint=110",
      "KeyCodes7": "Num0=96,Num1=97,Num2=98,Num3=99,Num4=100,Num5=101,Num6=102,Num7=103,Num8=104,Num9=105",
      "KeyCodes8": "CapsLock=20,ScrollLock=145,NumLock=144",

      "EdgeSize": "5", "RowSize": "5", "GanttSize": "5", "GanttSizeOnly": "10", "DragSize": "5", "ClickSize": "5", "GridSize": "", "GanttSizeOver": "0", "ScrollColSize": "10",
      "EdgeSizeTouch": "20", "RowSizeTouch": "10", "GanttSizeTouch": "20", "GanttSizeOnlyTouch": "1000", "DragSizeTouch": "5", "ClickSizeTouch": "20", "GridSizeTouch": "", "GanttSizeOverTouch": "3", "GanttSizeOverTouchFocused": "10", "ScrollColSizeTouch": "20",

      "LeftPrefix": "", "RightPrefix": "Right", "MiddlePrefix": "Middle", "CtrlPrefix": "Ctrl", "AltPrefix": "Alt", "ShiftPrefix": "Shift", "MetaPrefix": "Ctrl"
   },

   // Default rows
   "Def" : [

      // Default row for all rows except Space and Header
      { "Name": "R", "Kind": "Data", "CDef": "R", "AddDefChildren": "1",
         "CanFocus": "1", "CanEdit": "1", "CanDelete": "1", "CanSelect": "1", "CanResize": "1", "CanHide": "1", "CanFix": "1",
         "CanDrag": "1", "AcceptChild": "1", "CanExpand": "1",
         "CanFilter": "1", "CanGroup": "1", "CanSort": "1",
         "CanCopy": "1", "CanCopyPaste": "1", "CanExport": "1", "CanPrint": "1",
         "HoverCell": "Border,Color", "HoverRow": "Border,Background", 	"FocusCell": "Border,Color,Class", "FocusRow": "Border,Background",
         "Deleted": "0", "Selected": "0", "Changed": "0", "Added": "0", "Moved": "0",
         "Visible": "1", "Expanded": "1",
         "Calculated": "0", 	"Recalc": "3", "FormulaCanUse": "1",
         "MaxChildren": "10000", "MaxChildrenDiff": "20",
         "NoBorder": "0", "NoStyle": "0", "NoFormat": "0", "NoData": "0"
      },

      // Default row for fixed rows
      { "Name": "Fixed", "Def": "R",
         "CanDelete": "0", "CanSelect": "0", "CanDrag": "0", "CanFilter": "0", "CanCopy": "0", 	"AcceptChild": "0", "CanHide": "1", "InsertImg": ""
      },

      // Default row for filter rows
      { "Name": "Filter", "Def": "Fixed",
         "FormulaCanUse": "0", "FormulaCanEdit": "0", "CanHide": "1", "CanFix": "0", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1"
      },

      // Default row for column panel rows
      { "Name": "Panel", "Def": "Fixed", "CanFix": "0",
         "Buttons": "ColSelect,ColDelete,ColCopy", "CanFocus": "0", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1", "CanPrint": "0", "CanExport": "0", "CanHide": "1",
         "PanelColCopyMenu": "CopyCol,CopyCols@FC,CopySelectedCols@SC,-,AddCol,AddCols@2",
         "PanelColCopyAllMenu": "CopyCol,CopyCols@2,CopySelectedCols,-,AddCol,AddCols@2,AddColEnd"
      },

      // Default row created when grouping
      { "Name": "Group", "Def": "R", "Group": "1",
         "CanEdit": "0", 	"CanFilter": "0", "CanDrag": "0", "CanCopy": "0", "CanDelete": "0",
         "Expanded": "0", "NoUpload": "1"
      },

      // Default row for all space rows
      { "Name": "Solid", "Def": "",
         "Visible": "1",
         "CalcOrder": "",
         "CanFocus": "1", "CanDelete": "0", "CanSelect": "0", "CanDrag": "0", "CanFilter": "0", "CanCopy": "0", "CanPrint": "1", "CanResize": "1", "FormulaCanUse": "0", "CanHide": "1", "CanFix": "0", "InsertImg": "",
         "AcceptDef": "",
         "HoverCell": "Color", "HoverRow": "", "FocusCell": "Border,Color,Class", "FocusRow": ""
      },

      // Default header row
      { "Name": "Header", "Def": "",
         "Visible": "1", "Wrap": "0", "CanHide": "1", "CanFix": "0", "InsertImg": "",
         "CanDelete": "0", "CanEdit": "0", "CanFocus": "0", "CanFilter": "0", "AcceptChild": "0", "CanExport": "1", "CanCopyPaste": "3", "CanPrint": "2", "FormulaCanUse": "1", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1",
         "Deleted": "0", "Selected": "0", "Changed": "0", "Added": "0", "Moved": "0",
         "Expanded": "0", "Calculated": "0",
         "HoverCell": "Color", "HoverRow": "Background", "FocusCell": "Border,Color,Class", "FocusRow": ""
      },

      // Default row created to show column tree when imported from xlsx or created by Level attribute
      { "Name": "ColTree", "Def": "R", "Kind": "ColTree", "MenuName": "", "InsertImg": "", "FormulaCanUse": "0",
         "CanFix": "0", "CanSelect": "0", "CanExport": "0", "NoIndex": "1", "CanFocus": "0", "Spanned": "1", "PanelVisible": "0", "HoverCell": "", "HoverRow": "", "CanHide": "0", "PanelHoverCell": "", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1"   },

      // Default CPage (MaxChildren)
      { "Name": "CPage", "Def": ""   },

      // Default SPage (ChildPageLength)
      { "Name": "SPage", "Def": "", "Expanded": "3", "CanExpand": "3", "Visible": "0", "AggChildren": "1"   }

   ],

   // Default columns
   "DefCols" : [

      // Default column
      { "Name": "C",
         "Visible": "1", "Type": "Text", "AcceptNaN": "1",
         "CanResize": "1", "CanMove": "2", "CanCopy": "2", "CanFilter": "1", "CanSort": "1", "CanHide": "1", "CanSelect": "1", "CanDelete": "1", "FormulaCanUse": "1",
         "CanCopyPaste": "1", "CanExport": "1", "CanPrint": "1", "CanGroup": "1", "CanSearch": "1", "CanDrag": "1", "CanFix": "1",
         "GroupEmpty": "2", "GroupSingle": "1", "GroupSole": "1", "GroupDeleted": "1",
         "CaseSensitive": "1",
         "ShowHint": "4",
         "EmptyValue": "",
         "NoBorder": "0", "NoStyle": "0", "NoFormat": "0", "NoData": "0"
      },

      // Auto generated column by AutoCols
      { "Name": "Auto", "Def": "C", "CanMove": "1", "CanCopy": "1"   },

      // Auto generated column for RowIndex
      { "Name": "Index", "Def": "", "Visible": "1", "Type": "Text", "HoverCell": "Color", "Width": "60", "CanDrag": "1", "CanPrint": "1", "CanExport": "1", "CanHide": "1",
         "CanSort": "0", "CanEdit": "0", "CanFocus": "0", "CanSelect": "0", "CanDelete": "0", "CanMove": "0", "CanCopy": "0", "CanCopyPaste": "0", "CanEmpty": "1", "CanSearch": "0", "FormulaCanUse": "0", "CanFix": "0",
         "NoIndex": "1", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1"
      },

      // Auto generated column for ConstWidth
      { "Name": "ConstWidth", "Def": "", "CanSelect": "0", "Type": "Html",
         "ConstWidth": "1", "NoIndex": "1", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1", "WidthPad": "0", "CanFix": "0"
      },

      // Column settings used for space cells
      { "Name": "Space", "Def": "", "Type": "Text", "AcceptNaN": "1", "EmptyValue": "", "ShowHint": "4"   },

      // Default column for type Gantt
      { "Name": "Gantt", "Def": "", "Visible": "1", "Type": "Gantt", "MenuName": "Gantt chart", "CanPrint": "1",
         "CanSort": "0", "CanEdit": "0", "CanResize": "0", "CanFilter": "0", "CanCopyPaste": "0", "CanGroup": "0", "CanSearch": "0", "CanExport": "1", "WidthPad": "", "ShowHint": "0", "CanDrag": "0", "CanSelect": "0", "CanDelete": "0", "NoUpload": "1", "FormulaCanUse": "0", "CanFix": "0",
         "GanttOrder": "Chart,Availability,Constraints,Run,Main,Mark,Dependency,Flags,Points", "GanttHeaderCount": "6", "GanttMilestoneTopMin": "0",
         "GanttCount": "1", "GanttFlagsType": "1", "GanttFlagsMove": "1", "GanttShift": "3", "GanttFormatObject": "Last",
         "GanttSize": "", "GanttWidth": "22", "GanttUnits": "d", "GanttLeft": "0", "GanttRight": "0", "GanttRoundUnits": "0", "GanttPagingFixed": "6", "GanttPageWidth": "200%",
         "GanttDataUnits": "d", "GanttLastUnit": "", "GanttResourcesAssign": "4", "GanttAvailabilityFormat": "0.##", "GanttAvailabilityTransparent": "1", "GanttAvailabilityJoin": "1", "GanttAvailabilityShow": "3", "GanttAvailabilityTextRepeat": "500",
         "GanttHover": "1", "GanttEdit": "All", "GanttResizeDelete": "1", "GanttResizeBeforeMove": "2", "GanttUseConstraints": "2", "GanttShowConstraints": "1", "GanttShowHtml": "1", "GanttDragLine": "1",
         "GanttSmoothZoom": "1", "GanttZoomUndo": "1", "GanttHideExclude": "0", "GanttChangeExclude": "0", "GanttMaxExclude": "10000000", "GanttBase": "", "GanttBaseCanEdit": "1", "GanttFinish": "", "GanttFinishCanEdit": "1", "GanttFitVisible": "0",
         "GanttCheck": "4", "GanttCheckTime": "2000", "GanttCheckExclude": "1", "GanttStrict": "1", "GanttBasePreferred": "0", "GanttFinishPreferred": "0", "GanttEditStartMove": "1", "GanttMinSlack": "0", "GanttErrSlack": "0", "GanttSeparateSlack": "0", "GanttManualChange": "2", "GanttManualSide": "2",
         "GanttDependencyIcons": "3", "GanttAllDependencies": "2", "GanttDragDependenciesMove": "1", "GanttDragDependenciesMore": "1", "GanttCheckDependencies": "2",
         "GanttDirection": "0", "GanttCorrectDependencies": "2", "GanttIncorrectDependencies": "1", "GanttCorrectDependenciesFixed": "0", "GanttCorrectDependenciesCreate": "2", "GanttFixComplete": "0", "GanttMaxCorrectingLoops": "40", "GanttRunMaxCorrectingLoops": "5", "GanttCorrectDependenciesButtons": "Yes,No,Always,Never",
         "GanttMarkIncorrectDependencies": "2", "GanttColorIncorrectDependencies": "9", "GanttMarkDisabledDependencies": "2", "GanttColorDisabledDependencies": "8", "GanttAssignDependencies": "0", "GanttDependencyColor": "0", "GanttAdjacentDependencies": "1",
         "GanttRunResize": "Resize", "GanttRunMove": "Slide", "GanttRunAdjust": "Shift", "GanttRunAdjustStart": "Slip", "GanttRunAdjustCorrect": "Slip", "GanttRunError": "Sort", "GanttRunErrors": "1", "GanttRunJoined": "0", "GanttRunJoinedNbsp": "255", "GanttRunSelect": "0", "GanttRunTip": "*Text*",
         "GanttRunNew": "0.0001,Box", "GanttRunNewStart": "0.0001,Box", "GanttRunGroupHover": "1", "GanttRunStates": "2", "GanttRunCorrectFixed": "1", "GanttRunMilestones": "1", "GanttRunBoxMinType": "1",
         "GanttRunIds": "1", "GanttRunIdPrefix": "new", "GanttRunIdPostfix": "", "GanttRunLastId": "", "GanttRunDragObject": "2", "GanttRunContainersResize": "1", "GanttRunContainersDelete": "1",
         "GanttExportDependency": "1", "GanttExportBackground": "7",
         "GanttMenu": "SplitGanttConstraint,ChangeGanttConstraint,EditGanttFlag,ChooseGanttFlagIcon,SetGanttMilestone,LockGanttMain,DisableGanttMain,SplitGanttMain,SetGanttPercent,EditGanttPercent,EditGanttText,SelectGanttRunPart,LockGanttRun,LockGanttRunContainer,DisableGanttRun,DisableGanttRunContainer,EnableGanttRunContainer,SplitGanttRun,EditGanttRun,EditGanttRunTip,ChooseGanttRunType,ChooseGanttRunContainer,AddGanttRunContainer,-,SelectGanttRun,UnselectGanttRun,SelectGanttRunContainer,UnselectGanttRunContainer,JoinGanttRunSelected,SplitGanttRunJoined,JoinGanttRunAdjacent,SplitGanttRunAdjacent,ChooseGanttRunSelectedType,ChooseGanttRunGroupType,ChooseGanttRunGroupAllType,ChooseGanttRunContainerType,ChooseGanttRunRowType,-,SetGanttRunMilestone,SetGanttRunPercent,EditGanttRunPercent,EditGanttRunText,-,EditGanttResource,GanttDepLagChange,-,DelGanttDep,DelGanttConstraint,DelGanttFlag,DelGanttPoint,DelGanttMilestone,DelGanttMainPart,DelGanttMain,DelGanttRunPart,DelGanttRunContainerOnly,-,DelAllGanttDep,DelGanttMainAll,DelGanttMainBar,DelGanttRunSelected,DelGanttRunGroup,DelGanttRunGroupAll,DelGanttRunContainer,DelGanttRun,DelGanttFlags,DelGanttPoints,DelGanttConstraints,DelGanttAll,-,NewGanttFlag,NewGanttPoint,NewGanttConstraint,NewGanttMilestone,NewGanttEndMilestone,NewGanttRunStop,-,SetGanttBase,DelGanttBase,SetGanttFinish,DelGanttFinish,CorrectRelatedDependencies,CorrectAllDependencies,-,ZoomBar,ZoomAll,ZoomHeader,ZoomUndo,ZoomIn,ZoomOut,ZoomFit"
      }
   ],

   // First Header row = column captions
   "Header" : { "Kind": "Header", "Def": "Header", "id": "Header",
      "CanDrag": "0", "CanCopy": "1", "CanSelect": "1", "CanDelete": "1", "CanExport": "1"
   },

   // Root settings
   "Root" : {
      "CDef": "R",
      "CanSort": "1",
      "FocusCell": "Border", "FocusRow": "Border,Background",
      "AddParent": "0"
   },

   // Row left panel
   "Panel" : {
      "Def": "", "Visible": "1", "Move": "0", "Select": "1", "Delete": "1", "Copy": "0", "Prepared": "1",
      "CanHide": "1", "CanResize": "0", "CanMove": "0", "CanDrag": "1", "CanExport": "0", "CanCopyPaste": "0", "CanSelect": "0", "CanPrint": "0", "NoUpload": "1", "FormulaCanUse": "0", "NoBorder": "3", "NoStyle": "2", "NoFormat": "2", "NoData": "1",
      "HoverCell": "Color",
      "PanelCopyMenu": "CopyRow,CopyRows@F,CopyTree,CopyRowsTree@F,CopySelected@S,CopySelectedTree@S,CopySelectedChildEnd,CopySelectedTreeChildEnd,-,AddRow,AddRows@2,CopyEmpty,CopyRowsEmpty@2,CopySelectedEmpty,-,AddChildEnd,CopySelectedEmptyChildEnd",
      "PanelCopyAllMenu": "CopyRow,CopyRows@2,CopyTree,CopyRowsTree@2,CopySelected,CopySelectedTree,CopySelectedChildEnd,CopySelectedTreeChildEnd,-,AddRow,AddRows@2,CopyEmpty,CopyRowsEmpty@2,CopySelectedEmpty,-,AddChildEnd,CopySelectedEmptyChildEnd,AddRowEnd"
   },

   // Right side pager
   "Pager" : {
      "Visible": "1", "Width": "100", "MinWidth": "35", "CanResize": "1", "CanHide": "1", "Hover": "1", "Name": "Pager"
   },

   // Row displayed when no variable rows are visible
   // To not show it define Html="" for it in Text.xml
   "Solid" : [
      { "id": "NoData", "Panel": "0", "Space": "2", "Kind": "NoData", "Visible": "0", "CanPrint": "5", "CanHide": "0"   }
   ],

   // Bottom toolbar
   "Toolbar" : { "id": "Toolbar", "CanPrint": "0", "Space": "4", "Tag": "", "Visible": "1", "CanHide": "0", "LastVisible": "Lock",

      "Cells20Data": "Import,Save,Reload,Repaint,Print,ExportPDF,Export",
      "SaveButton": "Class", "SaveOnEnter": "Validate AND Save", "SaveVisibleFormula": "(Grid.Source.Upload.Url||Grid.Source.Upload.Tag||Grid.Source.Upload.Data||Grid.Source.Upload.Script)&&!Grid.Detail?1:0",
      "ReloadButton": "Class", "ReloadOnEnter": "Reload", "ReloadVisibleFormula": "!Grid.Detail",
      "RepaintButton": "Class", "RepaintOnEnter": "RenderPages", "RepaintVisibleFormula": "(Grid.Paging==1||Grid.Paging==2)&&Grid.AllPages&&!Grid.AutoPages||Grid.ColPaging&&!Grid.AutoColPages||Grid.ChildParts&&Grid.ChildPaging!=3&&!Grid.AutoPages", "RepaintFormula": "Grid.Paging==2||Grid.ColPaging==2||Grid.ChildParts==2?0:1",
      "PrintButton": "Class", "PrintOnEnter": "Print",
      "ExportPDFButton": "Class", "ExportPDFOnEnter": "ExportPDF", "ExportPDFVisibleFormula": "!!(Grid.Source.ExportPDF.Url||Grid.Source.ExportPDF.Script)",
      "ExportButton": "Class", "ExportOnEnter": "Export", "ExportVisibleFormula": "Grid.ExportFormat && (!Grid.Source.Export.Type || Grid.Source.Export.Url || Grid.Source.Export.Script) ? 1 : 0",
      "ImportButton": "Class", "ImportOnEnter": "Import", "ImportVisibleFormula": "Grid.ImportAction&1 && window.FileReader ? 1 : 0",

      "Cells30Manipulate": "Undo,Redo,Add,AddChild,AddCol,Join,Split,Outdent,Indent,ExpandAll,CollapseAll",
      "UndoButton": "Class", "UndoVisibleFormula": "Grid.Undo?1:0", "UndoFormula": "Grid.CanUndo()", "UndoOnEnter": "Undo",
      "RedoButton": "Class", "RedoVisibleFormula": "Grid.Undo?1:0", "RedoFormula": "Grid.CanRedo()", "RedoOnEnter": "Redo",
      "AddButton": "Class", "AddOnEnter": "ShowMenu OR AddRows OR AddRowEnd", "AddVisibleFormula": "Grid.Adding",
      "AddMenu": "CopyRow,CopyRows@2,CopyTree,CopyRowsTree@2,CopySelected,CopySelectedTree,CopySelectedEnd,CopySelectedTreeEnd,-,AddRow,AddRows@2,CopyEmpty,CopyRowsEmpty@2,CopySelectedEmpty,CopySelectedEmptyEnd,-,AddRowEnd",
      "AddChildButton": "Class", "AddChildOnEnter": "ShowMenu OR AddChildEnd", "AddChildVisibleFormula": "Grid.Adding && !!Grid.MainCol",
      "AddChildMenu": "CopySelectedChildEnd,CopySelectedTreeChildEnd,CopySelectedEmptyChildEnd,AddChildEnd",
      "AddColButton": "Class", "AddColOnEnter": "ShowMenu OR AddCol OR AddColEnd", "AddColVisibleFormula": "Grid.ColAdding",
      "AddColMenu": "CopyCol,CopyCols@2,CopySelectedCols,-,AddCol,AddCols@2,AddColEnd",
      "JoinButton": "Class", "JoinOnEnter": "Span OR AutoSpan", "JoinDisabledFormula": "!Grid.ActionSpan(3,1)", "JoinVisibleFormula": "(Grid.SelectingCells || Grid.FocusRect) && Grid.DynamicSpan",
      "SplitButton": "Class", "SplitOnEnter": "Split", "SplitDisabledFormula": "!Grid.ActionSplit(3,1)", "SplitVisibleFormula": "(Grid.SelectingCells || Grid.FocusRect) && Grid.DynamicSpan",
      "OutdentButton": "Class", "OutdentOnEnter": "OutdentSelectedF OR OutdentF", "OutdentVisibleFormula": "!!Grid.MainCol && !!Grid.Dragging",
      "IndentButton": "Class", "IndentOnEnter": "IndentSelectedF OR IndentF", "IndentVisibleFormula": "!!Grid.MainCol && !!Grid.Dragging",
      "ExpandAllButton": "Class", "ExpandAllOnEnter": "ExpandAllLoaded", "ExpandAllVisibleFormula": "!!Grid.MainCol",
      "CollapseAllButton": "Class", "CollapseAllOnEnter": "CollapseAll", "CollapseAllVisibleFormula": "!!Grid.MainCol",

      "Cells40Sheet": "AddImage,SetLink,Left,Center,Right,TextIndent,Top,Middle,Bottom,Bold,Italic,Underline,Strike,RotateLeft,NoRotate,RotateRight,WrapText,ClearStyle,Size,ColorText,ColorShadow,ColorBackground,Border,TextFormat",
      "AddImageButton": "Class", "AddImageOnEnter": "OpenImageF", "AddImageDisabledFormula": "!Grid.ActionOpenImage(3,1)", "AddImageVisibleFormula": "!!Grid.DynamicStyle",
      "SetLinkButton": "Class", "SetLinkOnEnter": "SetLink", "SetLinkDisabledFormula": "!Grid.ActionSetLink(3,1)", "SetLinkVisibleFormula": "!!Grid.DynamicStyle",
      "LeftButton": "Class", "LeftSwitch": "1", "LeftOnEnter": "AlignLeft OR NoAlign", "LeftDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "LeftVisibleFormula": "!!Grid.DynamicStyle", "LeftFormula": "(Grid.GetAttribute(Grid.FRow,Grid.FCol,'Align')+'').toLowerCase()=='left'?1:0",
      "CenterButton": "Class", "CenterSwitch": "1", "CenterOnEnter": "AlignCenter OR NoAlign", "CenterDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "CenterVisibleFormula": "!!Grid.DynamicStyle", "CenterFormula": "(Grid.GetAttribute(Grid.FRow,Grid.FCol,'Align')+'').toLowerCase()=='center'?1:0",
      "RightButton": "Class", "RightSwitch": "1", "RightOnEnter": "AlignRight OR NoAlign", "RightDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "RightVisibleFormula": "!!Grid.DynamicStyle", "RightFormula": "(Grid.GetAttribute(Grid.FRow,Grid.FCol,'Align')+'').toLowerCase()=='right'?1:0",
      "TextIndentType": "Enum", "TextIndentCanFocus": "2", "TextIndentWidth": "58", "TextIndentIconAlign": "Right", "TextIndentOnClick": "Grid.CanEditStyle() AND (!Grid.EditMode OR Row==Grid.ERow AND Col==Grid.ECol) ? StartEditCellAccept||1 : 1", "TextIndentOnDblClick": "1", "TextIndentVisibleFormula": "!!Grid.DynamicStyle",
      "TextIndentOnChange": "Grid.Indent=Value;return SetIndent", "TextIndentOnSame": "SetIndent",
      "TextIndentFormula": "var v=Grid.GetAttribute(Grid.FRow,Grid.FCol,'Indent');return v>50?50:v>10?Math.round(v/5)*5:v||v=='0'?v:'';", "TextIndentCanEdit": "1",
      "TextIndentEnumFormula": "var s=Grid.Indents,c=s.charAt(0);s=s.slice(1).split(c),o=[];for(var i=1;i<s.length;i+=2)o[o.length]=s[i];return c+o.join(c)",
      "TextIndentEnumKeysFormula": "var s=Grid.Indents,c=s.charAt(0);s=s.slice(1).split(c),o=[];for(var i=0;i<s.length;i+=2)o[o.length]=s[i];return c+o.join(c)",
      "TopButton": "Class", "TopSwitch": "1", "TopOnEnter": "VertAlignTop OR NoVertAlign", "TopDisabledFormula": "!Grid.CanEditStyle()", "TopVisibleFormula": "!!Grid.DynamicStyle", "TopFormula": "(Grid.GetAttribute(Grid.FRow,Grid.FCol,'VertAlign')+'').toLowerCase()=='top'?1:0",
      "MiddleButton": "Class", "MiddleSwitch": "1", "MiddleOnEnter": "VertAlignMiddle OR NoVertAlign", "MiddleDisabledFormula": "!Grid.CanEditStyle()", "MiddleVisibleFormula": "!!Grid.DynamicStyle", "MiddleFormula": "(Grid.GetAttribute(Grid.FRow,Grid.FCol,'VertAlign')+'').toLowerCase()=='middle'?1:0",
      "BottomButton": "Class", "BottomSwitch": "1", "BottomOnEnter": "VertAlignBottom OR NoVertAlign", "BottomDisabledFormula": "!Grid.CanEditStyle()", "BottomVisibleFormula": "!!Grid.DynamicStyle", "BottomFormula": "(Grid.GetAttribute(Grid.FRow,Grid.FCol,'VertAlign')+'').toLowerCase()=='bottom'?1:0",
      "BoldButton": "Class", "BoldSwitch": "1", "BoldOnEnter": "BoldOff OR BoldOn", "BoldDisabledFormula": "!Grid.CanEditStyle()", "BoldVisibleFormula": "!!Grid.DynamicStyle", "BoldFormula": "Grid.GetAttribute(Grid.FRow,Grid.FCol,'TextStyle')&1?1:0",
      "ItalicButton": "Class", "ItalicSwitch": "1", "ItalicOnEnter": "ItalicOff OR ItalicOn", "ItalicDisabledFormula": "!Grid.CanEditStyle()", "ItalicVisibleFormula": "!!Grid.DynamicStyle", "ItalicFormula": "Grid.GetAttribute(Grid.FRow,Grid.FCol,'TextStyle')&2?1:0",
      "UnderlineButton": "Class", "UnderlineSwitch": "1", "UnderlineOnEnter": "UnderlineOff OR UnderlineOn", "UnderlineDisabledFormula": "!Grid.CanEditStyle()", "UnderlineVisibleFormula": "!!Grid.DynamicStyle", "UnderlineFormula": "Grid.GetAttribute(Grid.FRow,Grid.FCol,'TextStyle')&4?1:0",
      "StrikeButton": "Class", "StrikeSwitch": "1", "StrikeOnEnter": "StrikeOff OR StrikeOn", "StrikeDisabledFormula": "!Grid.CanEditStyle()", "StrikeVisibleFormula": "!!Grid.DynamicStyle", "StrikeFormula": "Grid.GetAttribute(Grid.FRow,Grid.FCol,'TextStyle')&8?1:0",
      "RotateLeftButton": "Class", "RotateLeftSwitch": "1", "RotateLeftOnEnter": "RotateLeft", "RotateLeftDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "RotateLeftVisibleFormula": "!!Grid.DynamicStyle", "RotateLeftFormula": "var v=Grid.GetAttribute(Grid.FRow,Grid.FCol,'Rotate');return v==1||v==-1||v>=270?1:0",
      "NoRotateButton": "Class", "NoRotateSwitch": "1", "NoRotateOnEnter": "NoRotate", "NoRotateDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "NoRotateVisibleFormula": "!!Grid.DynamicStyle", "NoRotateFormula": "Grid.FRow?!Grid.GetAttribute(Grid.FRow,Grid.FCol,'Rotate'):0",
      "RotateRightButton": "Class", "RotateRightSwitch": "1", "RotateRightOnEnter": "RotateRight", "RotateRightDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "RotateRightVisibleFormula": "!!Grid.DynamicStyle", "RotateRightFormula": "var v=Grid.GetAttribute(Grid.FRow,Grid.FCol,'Rotate');return v==2||v==-2||v>3&&v<=90?1:0",
      "WrapTextButton": "Class", "WrapTextSwitch": "1", "WrapTextOnEnter": "WrapOn OR WrapOff", "WrapTextDisabledFormula": "!!Grid.EditMode||!Grid.CanEditStyle()", "WrapTextVisibleFormula": "!!Grid.DynamicStyle", "WrapTextFormula": "Grid.GetAttribute(Grid.FRow,Grid.FCol,'Wrap')?1:0",
      "ClearStyleButton": "Class", "ClearStyleOnEnter": "ClearStyle", "ClearStyleDisabledFormula": "!Grid.CanEditStyle()", "ClearStyleVisibleFormula": "!!Grid.DynamicStyle",
      "SizeType": "Html", "SizeCanFocus": "0", "SizeWidth": "33", "SizeButton": "Enum", "SizeOnClick": "Grid.CanEditStyle()?ShowDefaults:0", "SizeVisibleFormula": "!!Grid.DynamicStyle",
      "SizeOnChange": "Grid.TextSize=Value;return SetTextSize", "SizeOnSame": "var v=Grid.GetAttribute(Grid.FRow,Grid.FCol,'TextSize');Grid.TextSize=v?v:'';SetTextSize",
      "SizeDefaultsFormula": "var s=Grid.TextSizes,c=s.charAt(0);s=s.slice(1).split(c),o=[];for(var i=1;i<s.length;i+=2)o[o.length]=s[i];return c+o.join(c)",
      "SizeFormatFormula": "var s=Grid.TextSizes,c=s.charAt(0);s=s.slice(1).split(c),o=[];for(var i=0;i<s.length;i+=2)o[o.length]='\"'+s[i]+'\":\"'+s[i+1]+'\"';return '{'+o.join(',')+'}';",
      "SizeEditFormatFormula": "var s=Grid.TextSizes,c=s.charAt(0);s=s.slice(1).split(c),o=[];for(var i=0;i<s.length;i+=2)o[o.length]='\"'+s[i]+'\":\"'+s[i+1]+'\"';return '{'+o.join(',')+'}';",
      "SizeFormula": "var v=Grid.GetAttribute(Grid.FRow,Grid.FCol,'TextSize');return v?v:'';", "SizeCanEdit": "0",
      "ColorTextButton": "Class", "ColorTextOnEnter": "SetTextColor", "ColorTextDisabledFormula": "!Grid.CanEditStyle()", "ColorTextVisibleFormula": "!!Grid.DynamicStyle", "ColorTextUnderlineFormula": "Grid.TextColor?Grid.TextColor:''",
      "ColorTextLeft": "1", "ColorTextLeftVisibleFormula": "!!Grid.DynamicStyle",
      "ColorTextSwitch": "1", "ColorTextPopupIcon": "3", "ColorTextOnClickPopup": "ChooseTextColor OR 1",
      "ColorShadowButton": "Class", "ColorShadowOnEnter": "SetTextShadowColor", "ColorShadowDisabledFormula": "!Grid.CanEditStyle()", "ColorShadowVisibleFormula": "!!Grid.DynamicStyle", "ColorShadowUnderlineFormula": "Grid.TextShadowColor?Grid.TextShadowColor:''",
      "ColorShadowSwitch": "1", "ColorShadowPopupIcon": "3", "ColorShadowOnClickPopup": "ChooseTextShadowColor OR 1",
      "ColorBackgroundButton": "Class", "ColorBackgroundOnEnter": "SetColor", "ColorBackgroundDisabledFormula": "!Grid.CanEditStyle()", "ColorBackgroundVisibleFormula": "!!Grid.DynamicStyle", "ColorBackgroundUnderlineFormula": "Grid.DefaultColor?Grid.DefaultColor:''",
      "ColorBackgroundSwitch": "1", "ColorBackgroundPopupIcon": "3", "ColorBackgroundOnClickPopup": "ChooseColor OR 1",
      "BorderButton": "Class", "BorderOnEnter": "AlignLeftF", "BorderDisabledFormula": "!Grid.CanEditBorder()", "BorderVisibleFormula": "!!Grid.DynamicBorder", "BorderSwitch": "1", "BorderPopupIcon": "3",
      "BorderButtonClassFormula": "var o=Grid.BorderOut?(Grid.BorderOut+'').split(','):null,i=Grid.BorderIn?(Grid.BorderIn+'').split(','):null;return 'Border,Border'+(o?(i?'All':'O'+(o[3]?o[3]:15)):(i?'I'+(i[3]?(i[3]&5?1:0)+(i[3]&10?2:0):3):''))",
      "BorderUnderlineFormula": "var o=Grid.BorderOut?Grid.BorderOut:Grid.BorderIn;if(o)o=(o+'').split(',')[1];return o?o:''",
      "BorderUnderlineStyleFormula": "var o=Grid.BorderOut?Grid.BorderOut:Grid.BorderIn;if(o)o=(o+'').split(',')[0];return o?o:'Empty'",
      "BorderOnClickPopup": "ChooseBorder OR 1",
      "TextFormatType": "Html", "TextFormatCanEdit": "1", "TextFormatCanFocus": "2", "TextFormatWrap": "0", "TextFormatWidth": "92", "TextFormatIcon": "Enum", "TextFormatIconAlign": "Right", "TextFormatCursor": "Pointer", "TextFormatVisibleFormula": "!!Grid.DynamicFormat", "TextFormatOnClick": "!!Grid.EditMode?1:ShowDefaults||1", "TextFormatOnDblClick": "1",
      "TextFormatFormula": "Grid.FindFormat(Grid.FRow,Grid.FCol,Grid.Formats,'<span style=\\'font-size:9px;color:silver;\\'>format</span>')", "TextFormatDefaultsFormula": "return Grid.Formats", "TextFormatTip": "1",
      "TextFormatOnChange": "Grid.Format=Value;return SetFormat", "TextFormatOnSame": "SetFormat",

      "Cells10Gantt": "Correct",
      "Cells50GanttZoom": "ZoomIn,ZoomOut,ZoomFit",
      "CorrectButton": "Class", "CorrectVisibleFormula": "Grid.HasDependencies()", "CorrectFormula": "Grid.HasDependencies()?(ganttdependencyerrors()?1:0):0", "CorrectOnEnter": "CorrectAllDependencies",
      "ZoomInButton": "Class", "ZoomInVisibleFormula": "Grid.HasGantt()", "ZoomInFormula": "Grid.CanZoomIn()", "ZoomInOnEnter": "ZoomIn",
      "ZoomOutButton": "Class", "ZoomOutVisibleFormula": "Grid.HasGantt()", "ZoomOutFormula": "Grid.CanZoomOut()", "ZoomOutOnEnter": "ZoomOut",
      "ZoomFitButton": "Class", "ZoomFitVisibleFormula": "Grid.HasGantt()", "ZoomFitOnEnter": "ZoomFitAll",

      "Cells60Cfg": "DefSort,Sort,Calc,WinScroll,Columns,Cfg,Lock,Help,Debug",
      "DefSortButton": "Class", "DefSortButtonClass": "Sort", "DefSortOnEnter": "DefaultSort", "DefSortVisibleFormula": "Grid.Sorting && Grid.DefaultSort", "DefSortFormula": "1",
      "SortButton": "Class", "SortOnEnter": "SortOn OR SortOff", "SortVisibleFormula": "Grid.Sorting && (Grid.Paging==3||Grid.ChildPaging==3||Grid.Paging==1 && Grid.LoadedCount>300) && !Grid.DefaultSort", "SortFormula": "Grid.Sorted?1:0",
      "CalcButton": "Class", "CalcOnEnter": "CalcOn OR CalcOff", "CalcVisibleFormula": "Grid.Calculating && !Grid.Gantt", "CalcFormula": "Grid.Calculated?1:0",
      "WinScrollButton": "Class", "WinScrollOnEnter": "ChangeWinScroll", "WinScrollFormula": "Grid.NoVScroll && Grid.NoHScroll?1:0", "WinScrollDisabledFormula": "!Grid.CanChangeWinScroll()",
      "ColumnsButton": "Class", "ColumnsOnEnter": "ShowColumns",
      "CfgButton": "Class", "CfgOnEnter": "ShowCfg",
      "LockButton": "Class", "LockOnEnter": "Lock", "LockVisibleFormula": "Grid.LockedValues?1:0", "LockFormula": "Grid.GetLockIndex()", "LockSwitch": "2",
      "HelpButton": "Class", "HelpOnEnter": "ShowHelp",
      "DebugButton": "Class", "DebugOnEnter": "ShowDebug", "DebugVisibleFormula": "!!Grid.DebugFlags.length",

      "Cells70Styles": "Languages,Styles,GanttStyles,Sizes,Scales,Contrasts",
      "LanguagesType": "Languages", "Languages": "2", "LanguagesVisibleFormula": "Grid.Language?1:0",
      "StylesType": "Styles", "Styles": "2",
      "GanttStylesType": "GanttStyles", "GanttStyles": "2",
      "SizesType": "Sizes", "Sizes": "2",
      "ScalesType": "Scales", "Scales": "2",
      "ContrastsType": "Contrasts", "Contrasts": "2",

      "Cells80Right": "Empty,Formula,Resize",
      "EmptyRelWidth": "1", "EmptyNoColor": "1",
      "FormulaWidth": "-2", "FormulaNoColor": "1", "FormulaCanFocus": "0", "FormulaType": "Html", "FormulaWrap": "0",
      "ResizeWidth": "1", "ResizeVisibleFormula": "!!Grid.ResizingMain", "ResizeCanFocus": "0", "ResizeVertAlign": ""
   },

   // Configuration menus
   "MenuCfg" : {
      "Items": "GanttCaption,GanttCfg,SheetCaption,SheetCfg,CfgCaption,Cfg,StylesCaption,Styles,LanguageCaption,Language", "Attribute": "CanHide", "HideUnused": "1"
   },
   "MenuColumns" : {
      "Items": "Cols,-,Pagers,-,Head,-,Foot,-,Space", "Attribute": "CanHide", "HideUnused": "1"
   },
   "MenuPrint" : {
      "Items": "ColsCaption,Cols,SpaceCaption,Space,RowsCaption,Head,Foot,OptionsCaption,Options,SizeCaption,Size", "Attribute": "CanPrint", "HideUnused": "1"
   },
   "MenuExport" : {
      "Items": "ColsCaption,Cols,RowsCaption,Head,Foot,OptionsCaption,Options", "Attribute": "CanExport", "HideUnused": "1"
   },

   // Animations
   "Animations" : {
      "Show": "#AnimateCenterTop, #ZoomInH 500ms", "Hide": "#AnimateCenterTop, #ZoomOutH 500ms", "ShowFilter": "@#AnimateCenterTop, #ZoomInH 500ms, #HighlightAdd 500ms", "HideFilter": "@#HighlightDelete 500ms, #AnimateCenterTop, #ZoomOutH 500ms",
      "Add": "#ZoomIn 500ms",
      "CopyTo": "#ZoomIn 500ms", "CopyFrom": "@#Mark 500ms", "CopyRowsFrom": "@#Mark,500", "CopyToOutside": "#ZoomIn 500ms", "CopyFromOutside": "@#Highlight 500ms",
      "MoveTo": "#ZoomIn 250ms", "MoveFrom": "#ZoomOut 250ms", "MoveToOutside": "#ZoomIn 500ms", "MoveFromOutside": "#ZoomOut 500ms",
      "Delete": "#ZoomOut 500ms, #AnimateCenterTop, #AnimateTransparent, #ZoomOutH 200ms", "DeleteVisible": "#ZoomOut 500ms", "Undelete": "#ZoomIn 500ms",
      "Select": "#RotateX90 300ms", "Deselect": "#RotateX90 300ms",
      "ExpandChildren": "#AnimateCenterTop, #ZoomInH 200ms", "CollapseChildren": "#AnimateCenterTop, #ZoomOutH 200ms",

      "UndoShow": "@#Highlight 500ms, #ZoomOut 500ms", "RedoShow": "@#ZoomIn 500ms, #Highlight 500ms", "UndoHide": "@#ZoomIn 500ms, #Highlight 500ms", "RedoHide": "@#Highlight 500ms,#ZoomOut 500ms",
      "UndoAdd": "@#HighlightDelete 500ms, #ZoomOut 500ms", "RedoAdd": "@#ZoomIn 500ms, #HighlightAdd 500ms",
      "UndoMove": "@#ZoomIn 500ms, #HighlightMove 500ms", "RedoMove": "@#ZoomIn 500ms, #HighlightMove 500ms",
      "UndoDelete": "@#ZoomIn 500ms, #HighlightAdd 500ms", "RedoDelete": "@#HighlightDelete 500ms, #ZoomOut 500ms", "UndoUndelete": "@#HighlightDelete 500ms, #ZoomOut 500ms", "RedoUndelete": "@#ZoomIn 500ms, #HighlightAdd 500ms",
      "UndoSelect": "#RotateX90 300ms", "RedoSelect": "#RotateX90 300ms", "UndoDeselect": "#RotateX90 300ms", "RedoDeselect": "#RotateX90 300ms",
      "UndoResize": "@#Highlight 500ms", "RedoResize": "@#Highlight 500ms",

      "Added": "@#ZoomIn 500ms, #HighlightAdd 500ms",
      "Moved": "@#ZoomIn 500ms, #HighlightMove 500ms",
      "Deleted": "@#HighlightDelete 500ms, #ZoomOut 500ms",
      "Selected": "@#HighlightSelect 500ms,#ColorSelected,#RotateX90 500ms", "Deselected": "@#HighlightDeselect 500ms,#RotateX90 500ms",
      "Expanded": "@#Highlight 500ms", "ExpandedChildren": "#AnimateHidden, 500, #AnimateVisible, #AnimateCenterTop, #ZoomInH 500ms", "Collapsed": "@#Highlight 500ms", "CollapsedChildren": "500, #AnimateCenterTop, #ZoomOutH 500ms",
      "ChangedFrom": "#HighlightChange 500ms, #RotateX90To 200ms", "ChangedTo": "#RotateX90From 200ms",

      "ShowCol": "#ZoomInX 500ms", "HideCol": "#ZoomOutX 500ms",
      "AddCol": "#ZoomIn 500ms",
      "CopyColTo": "#ZoomIn 500ms", "CopyColFrom": "#Mark 500ms", "CopyColsFrom": "#Mark,500",
      "MoveColTo": "#ZoomIn 250ms", "MoveColFrom": "#ZoomOut 250ms",
      "DeleteCol": "#ZoomOut 500ms", "UndeleteCol": "#ZoomIn 500ms",
      "SelectCol": "#RotateY90 300ms", "DeselectCol": "#RotateY90 300ms",

      "UndoShowCol": "#Highlight 500ms, #ZoomOutX 500ms", "RedoShowCol": "#ZoomInX 500ms, #Highlight 500ms", "UndoHideCol": "#ZoomInX 500ms, #Highlight 500ms", "RedoHideCol": "#Highlight 500ms,#ZoomOutX 500ms",
      "UndoAddCol": "#HighlightDelete 500ms, #ZoomOut 500ms", "RedoAddCol": "#ZoomIn 500ms, #HighlightAdd 500ms",
      "UndoMoveCol": "@#ZoomIn 500ms, #HighlightMove 500ms", "RedoMoveCol": "@#ZoomIn 500ms, #HighlightMove 500ms",
      "UndoDeleteCol": "#ZoomIn 500ms, #HighlightAdd 500ms", "RedoDeleteCol": "#HighlightDelete 500ms, #ZoomOut 500ms", "UndoUndeleteCol": "#HighlightDelete 500ms, #ZoomOut 500ms", "RedoUndeleteCol": "#ZoomIn 500ms, #HighlightAdd 500ms",
      "UndoSelectCol": "#RotateY90 300ms", "RedoSelectCol": "#RotateY90 300ms", "UndoDeselectCol": "#RotateY90 300ms", "RedoDeselectCol": "#RotateY90 300ms",
      "UndoResizeCol": "#Highlight 500ms", "RedoResizeCol": "#Highlight 500ms",

      "Focus": "#Focus 200ms", "FocusGantt": "", "FocusLines": "",
      "Find": "#HighlightSelect 500ms",
      "Copy": "#AnimateLeftCenter,#Copy 200ms",
      "EditFrom": "#RotateX90To 200ms", "EditTo": "#RotateX90From 200ms", "EditBoolFrom": "#RotateY90To 200ms", "EditBoolTo": "#RotateY90From 200ms",
      "CalculateFrom": "#RotateX90To 200ms", "CalculateTo": "#RotateX90From 200ms",
      "ChangeFrom": "#RotateX90To 200ms", "ChangeTo": "#RotateX90From 200ms",
      "FillFrom": "#RotateX90To 200ms", "FillTo": "#RotateX90From 200ms",
      "PasteFrom": "#RotateX90To 200ms", "PasteTo": "#RotateX90From 200ms",
      "MarkFrom": "#RotateX90To 200ms", "MarkTo": "#RotateX90From 200ms",
      "ClearFrom": "#RotateX90To 200ms", "ClearTo": "",

      "UndoChangeFrom": "#RotateX90To 200ms", "UndoChangeTo": "#RotateX90From 200ms", "RedoChangeFrom": "#RotateX90To 200ms", "RedoChangeTo": "#RotateX90From 200ms",
      "UndoBorder": "#Highlight 500ms", "RedoBorder": "#Highlight 500ms",
      "UndoStyle": "#Highlight 500ms", "RedoStyle": "#Highlight 500ms",

      "ShowMenu": "#AnimateCenterTop, #ZoomInY 200ms", "ShowMenuUp": "#AnimateCenterBottom, #ZoomInY 200ms", "HideMenu": "#AnimateCenterTop, #ZoomOutY 200ms", "HideMenuUp": "#AnimateCenterBottom, #ZoomOutY 200ms",
      "ShowPopup": "#AnimateLeftTop, #ZoomIn 200ms", "ShowPopupUp": "#AnimateLeftBottom, #ZoomIn 200ms", "HidePopup": "#AnimateLeftTop, #ZoomOut 200ms", "HidePopupUp": "#AnimateLeftBottom, #ZoomOut 200ms",
      "ShowPopupRight": "#AnimateRightTop, #ZoomIn 200ms", "ShowPopupRightUp": "#AnimateRightBottom, #ZoomIn 200ms", "HidePopupRight": "#AnimateRightTop, #ZoomOut 200ms", "HidePopupRightUp": "#AnimateRightBottom, #ZoomOut 200ms",
      "ShowCfg": "#ZoomIn 200ms", "HideCfg": "#ZoomOut 200ms",
      "ShowTip": "#AnimateLeftTop, #ZoomIn 200ms", "ShowTipRight": "#AnimateRightTop, #ZoomIn 200ms", "HideTip": "#AnimateLeftTop, #ZoomOut 200ms", "HideTipRight": "#AnimateRightTop, #ZoomOut 200ms",
      "ShowHint": "#Show 200ms", "HideHint": "#Hide 200ms", "ShowHintVert": "#Show 200ms", "HideHintVert": "#Hide 200ms",
      "ShowMessage": "#ZoomIn 200ms", "HideMessage": "#ZoomOut 200ms",
      "ShowCalendar": "#AnimateLeftTop, #ZoomIn 200ms", "ShowCalendarUp": "#AnimateLeftBottom, #ZoomIn 200ms", "HideCalendar": "#AnimateLeftTop, #ZoomOut 200ms", "HideCalendarUp": "#AnimateLeftBottom, #ZoomOut 200ms",
      "ShowCalendarRight": "#AnimateRightTop, #ZoomIn 200ms", "ShowCalendarRightUp": "#AnimateRightBottom, #ZoomIn 200ms", "HideCalendarRight": "#AnimateRightTop, #ZoomOut 200ms", "HideCalendarRightUp": "#AnimateRightBottom, #ZoomOut 200ms",
      "CalendarDaysFrom": "#RotateX90To 200ms", "CalendarDaysTo": "#RotateX90From 200ms", "CalendarMonthsFrom": "#RotateX90To 200ms", "CalendarMonthsTo": "#RotateX90From 200ms",
      "CalendarMonthFrom": "#RotateY90To 200ms", "CalendarMonthTo": "#RotateY90From 200ms", "CalendarYearFrom": "", "CalendarYearTo": "",

      "Wait": "100"
   },

   // Languages definition
   "Languages" : {
      "EN" : { "Name": "English", "Text_Url": "Text.js", "Text_Static": "Text", "Tip": "US English, base TreeGrid language"   },
      "GB" : { "Name": "English", "Text_Url": "Languages/TextGB.js", "Text_Static": "TextGB", "Tip": "UK English, differs from US only in date and currency formats"   },
      "DE" : { "Name": "Deutsch", "Text_Url": "Languages/TextDE.js", "Text_Static": "TextDE", "Tip": "German, fully translated"   },
      "NL" : { "Name": "Nederlands", "Text_Url": "Languages/TextNL.js", "Text_Static": "TextNL", "Tip": "Dutch, not yet translated"   },
      "FR" : { "Name": "Fran\u00E7ais", "Text_Url": "Languages/TextFR.js", "Text_Static": "TextFR", "Tip": "French French, fully translated"   },
      "CA" : { "Name": "Fran\u00E7ais", "Text_Url": "Languages/TextCA.js", "Text_Static": "TextCA", "Tip": "Canadian French, differs from French mainly in date formats; fully translated"   },
      "IT" : { "Name": "Italiano", "Text_Url": "Languages/TextIT.js", "Text_Static": "TextIT", "Tip": "Italian, translated only TreeGrid, not the example"   },
      "ES" : { "Name": "Espa\u00F1ol", "Text_Url": "Languages/TextES.js", "Text_Static": "TextES", "Tip": "Spanish, translated only TreeGrid, not the example"   },
      "PT" : { "Name": "Portugu\u00EAs", "Text_Url": "Languages/TextPT.js", "Text_Static": "TextPT", "Tip": "Portugal Portuguese, translated only TreeGrid, not the example"   },
      "BR" : { "Name": "Portugu\u00EAs", "Text_Url": "Languages/TextBR.js", "Text_Static": "TextBR", "Tip": "Brazilian Portuguese, fully translated"   },
      "CS" : { "Name": "\u010Cesky", "Text_Url": "Languages/TextCS.js", "Text_Static": "TextCS", "Tip": "Czech, fully translated"   },
      "HR" : { "Name": "Hrvatski", "Text_Url": "Languages/TextHR.js", "Text_Static": "TextHR", "Tip": "Croatian, fully translated except Gantt example"   },
      "RU" : { "Name": "\u041F\u043E-\u0440\u0443\u0441\u0441\u043A\u0438", "Text_Url": "Languages/TextRU.js", "Text_Static": "TextRU", "Tip": "Russian, fully translated"   },
      "KR" : { "Name": "\uD55C\uAD6D\uC5B4", "Text_Url": "Languages/TextKR.js", "Text_Static": "TextKR", "Tip": "Korean, not yet translated"   },
      "JP" : { "Name": "\u65E5\u672C\u8A9E", "Text_Url": "Languages/TextJP.js", "Text_Static": "TextJP", "Tip": "Japanese, fully translated"   },
      "CN" : { "Name": "\u4E2D\u6587", "Text_Url": "Languages/TextCN.js", "Text_Static": "TextCN", "Tip": "Chinese, fully translated"   },
      "FA" : { "Name": "\u0641\u0627\u0631\u0633\u06CC", "Text_Url": "Languages/TextFA.js", "Text_Static": "TextFA", "Tip": "Persian / Farsi, fully translated"   },
      "XX" : { "Name": "XX Test", "Text_Url": "Languages/TextXX.js", "Text_Static": "TextXX", "Tip": "Test language to translate"   }
   },

   // Format configuration the same for all languages
   "Lang" : {
      "Format" : {
         "StrictNumbers": "0", "StrictDates": "15", "GMT": "0", "DateFormatLowercase": "1", "EditFormats": "", "ExactNumbers": "0", "BaseSeparators": "0", "Unsupported": "\\?",
         "Colors": ",#000,#FFF,#F00,#0F0,#00F,#FF0,#F0F,#0FF,#800,#080,#008,#880,#808,#088,#CCC,#888,#99F,#936,#FFC,#CFF,#606,#F88,#06C,#CCF,#008,#F0F,#FF0,#0FF,#808,#800,#088,#00F,#0CF,#CFF,#CFC,#FF9,#9CF,#F9C,#C9F,#FC9,#36F,#3CC,#9C0,#FC0,#F90,#F60,#669,#999,#036,#396,#030,#330,#930,#936,#339,#333",
         "ExportFilters": ",= ,\u2260 ,< ,\u2264 ,> ,\u2265 ,|* ,|- ,*| ,-| ,*|* ,-|- ", "ExportFiltersHtml": "<span style='color:red;'>%1</span>"
      },
      "MenuExport" : { "ExportFormats": "XLSX,XLS,CSV"   },
      "MenuPrint" : { "PDFFormats": "PDF"   }
   },

   // Configuration preset per CSS style
   "Media" : [
      { "Style": "TT",
         "Cfg" : { "Alternate": "2", "AlternateType": "3", "ColorPanel": "1"   }
      },
      { "Style": "CB,CC,CE,CG,CL,CS,CO,CP,CQ,CR,CF",
         "Cfg" : { "ShrinkStyleType": "0"   },
         "Rows" : [
            { "id": "Toolbar", "SizesVisible": "0", "SizesLabelVisible": "0", "GanttStylesVisible": "0", "GanttStylesLabelVisible": "0", "ContrastsVisible": "0", "ContrastsLabelVisible": "0"   }
         ],
      },
   ],
}) /* End of JSONP header */
