TreeGridLoaded ({ /* JSONP header, to be possible to load from xxx_Jsonp data source */ 
   "Cfg" : { "TextVersion": "160001"   }, 



/* 
In Alert section place CR/LF as "&#x0a;"
In HTML sections place CR/LF as "&lt;br>"
In HTML sections use HTML tags &lt;em> (error - red), &lt;s> (disabled - gray), &lt;i> (highlight - blue), &lt;b> (strong highlight - blue+bold)
Some texts can place dynamic information, e.g. count or id; some text replace "%d", some other texts replace %1, %2, ... 
*/


"Lang" : { 
      
// All alert / confirm non HTML texts 
      
"Alert" : { 
         
"V3_1": "", 
   "CanReloadStart": "This command ", 
   "CanReloadChanges": "updates all changes to server", 
   "CanCancelChanges": "cancels all changes", 
   "And": " and ", 
   "CanReloadSelect": "clears all selection", 
   "CanReloadEnd": "! Do you want to continue?", 
"V3_2": "", 
   "ErrTimeout": "Cannot download data, timeout expired", 
   "AskTimeout": "Cannot download data, server timeout!\u000ADo you want to repeat request?", 
   "UploadTimeout": "Cannot upload data, timeout expired", 
   "AskUploadTimeout": "Cannot upload data, server timeout!\u000ADo you want to send data again?", 
"V3_5": "", 
   "ErrHide": "You cannot hide all variable columns!", 
   "ErrHideExt": "Width of all fixed columns is too wide!", 
"V4_2": "", 
   "ErrPrintOpen": "The print window could not be opened\u000A\u000A Permit popup windows to let print the grid", 
   "ErrPrint": "The document was not successfully printed", 
"V4_4_3": "", 
   "ErrCheck": "Synchronizing with server failed!\u000ADo you want to temporary disable the checking for updates?", 
"V4_7": "", 
   "SearchHelp": "Enter string to search for like in Google\u000A\u000Aindividual keywords separate by space\u000Aphrases place into double quotes\u000Avariants separate by uppercase OR keyword\u000Aexceptions precede by \"-\" (minus)\u000A\u000AOr enter expression to search by\u000A\u000Aspecify columns caption to compare\u000Ause operators < <= > >= = <> ( ) + - * /\u000Ause AND OR keywords to join expressions\u000Ause special keywords STARTS ENDS CONTAINS\u000A   for comparing strings (NOT to negate)\u000Aexample: customer starts martin and date <= 1/1/2019", 
   "NotFound": "Nothing found", 
   "SearchStart": "Nothing found\u000ADo you want to continue from beginning?", 
   "SearchError": "The search expression is invalid!", 
"V5_3": "", 
   "Invalid": "Invalid value", 
"V6_0": "", 
   "DelRow": "Are you sure to delete row '%d'?", 
   "DelSelected": "Are you sure to delete %d rows?", 
   "StyleErr": "Cannot load TreeGrid CSS style!", 
   "ExportDownload": "Download", 
"V7_0": "", 
   "FoundResults": "Found %d results", 
   "PrintPrepared": "Grid is ready to print", 
"V7_1": "", 
   "PrintReady": "Grid is ready to print\u000AChoose Print Preview option in menu to update page size\u000AOr choose Print option or press Ctrl+P to print directly", 
   "PrintCloseWindow": "\u000AAfter print is finished, you can close this page", 
   "PrintCloseTag": "\u000AAfter print is finished, you can click to the grid to return", 
"V9_2": "", 
   "PivotReload": "Do you want to re-create the pivot grid?", 
"V12_0": "", 
   "FormulaCircularAsk": "Formula contains circular cell reference\u000ADo you want to permit it?", 
   "DelCol": "Are you sure to delete column '%d'?", 
   "DelSelectedCols": "Are you sure to delete %d columns?", 
   "SearchEnd": "Nothing found\u000ADo you want to continue from end?", 
"V12_1": "", 
   "ExportIE": "Not available in IE 9 and older", 
   "ExportError": "Export failed!", 
"V13_0": "", 
   "DefaultSheet": "Sheet", 
   "NewSheet": "Sheet%1", 
   "LoadSheetErrorMissingModule": "Loading data failed because of missing TreeGrid module %1", 
   "StripHtml": "The change will strip formatting from the text!\u000ADo you want to save the change?", 
"V14_0": "", 
   "DownloadSync": "This action requires to download all data to client.\u000AIt can take longer time!\u000ADo you want to proceed?", 
"V15_0": "", 
   "ImgData": "image", 
   "ImgWidth": "W", 
   "ImgHeight": "H", 
   "ImgX": "X", 
   "ImgY": "Y", 
   "ImgUrl": "URL", 
   "ImgSrc": "SRC", 
   "LinkUrl": "URL", 
   "LinkText": "TEXT", 
   "ReplaceDefinedName": "The name '%1' already exists with value '%2'!\u000ADo you want to replace it?", 
   "DeleteDefinedName": "Do you want to delete name '%1' with value '%2'?"  
    }, 
    
    
    
// All message HTML texts     

"Text" : { 
      
"V2_0": "", 
   "DelSelected": "Deleting rows ...", 
   "ExtentErr": "Too small space for the grid", 
   "Sort": "Sorting rows ...", 
   "SelectAll": "Changing selection of all rows ...", 
   "DoFilter": "Filtering rows ...", 
"V2_3": "", 
   "UpdateGrid": "Updating view ...", 
   "CollapseAll": "Collapsing all rows ...", 
   "ExpandAll": "Expanding all rows ...", 
"V2_6": "", 
   "Render": "Rendering ...", 
   "Page": "Page", 
   "NoPages": "Empty", 
   "UpdateCfg": "Updating settings ...", 
   "StartErr": "Fatal error! <br/>TreeGrid cannot render", 
"V3_0": "", 
   "Calculate": "Calculating cells ...", 
   "UpdateValues": "Updating values ...", 
   "UpdateTree": "Updating tree ...", 
"V3_1": "", 
   "PageErr": "Cannot download this data part!", 
"V3_2": "", 
   "Layout": "Loading layout ...", 
   "Load": "Loading data ...", 
"V3_5": "", 
   "ColumnsCaption": "Select columns to display", 
   "ColUpdate": "Updating columns ...", 
"V4_3": "", 
   "Picture": "Picture", 	
   "DefaultsDate": "Select date ...", 
   "DefaultsButton": "Select ...", 
"V4_5": "", 
   "GroupCustom": "To group by, drag column caption here ...", 
   "Group": "Grouping rows ...", 
   "DefaultsFilterOff": "(All)", 
   "Items": "Items %d - %d", 
   "Print": "<h2><center>Please wait while generating report for printing ...</center></h2>", 
"V4_7": "", 
   "SearchMethodList": "|Automatic|Search&#160;like&#160;Google|Search&#160;by&#160;expression", 
   "Contains": "contains,has", 
   "Starts": "starts,starts with,starts by,begins,begins with,begins by", 
   "Ends": "ends,ends by, ends with", 
   "And": "and", 
   "Or": "or", 
   "Not": "not", 
   "SearchSearch": "Search", 
   "SearchFilter": "Filter", 
   "SearchSelect": "Select", 
   "SearchMark": "Mark", 
   "SearchFind": "Find", 
   "SearchClear": "Clear", 
   "SearchHelp": "Help", 
   "Search": "Searching ...", 
"V5_0_1": "", 
   "Printed": "Please switch to window containing the report to print it", 
"V5_6": "", 
   "DoUndo": "Performing undo ...", 
   "DoRedo": "Performing redo ...", 
"V5_9": "", 
   "GanttUpdate": "Updating Gantt ...", 
"V6_0": "", 
   "GanttCreate": "Creating Gantt ...", 
   "LoadStyles": "Loading style ...", 
   "SetStyle": "Updating style ...", 
   "LoadPage": "Loading", 
   "RenderPage": "Rendering", 
   "ColWidth": "Changing width of column '%d'", 
   "ColMove": "Moving column '%d'", 
   "Password": "***", 
   "DefaultsNone": "Clear all", 
   "RadioFilterOff": "<i>off</i>", 
   "DragObjectMove": "moving row <b>%d</b>", 
   "DragObjectCopy": "copying row <b>%d</b>", 
   "DragObjectMoreMove": "moving <b'>%d</b> rows", 
   "DragObjectMoreCopy": "copying <b>%d</b> rows", 
   "ExportFinished": "<center><b>Report generated</b><br/><br/>Click button for download<br/></center><br/>", 
   "RenderProgressText": "Finished %d pages from %d", 
   "RenderProgressCancel": "Render on background", 
   "PrintProgressCaption": "Generating report", 
   "PrintProgressText": "Finished %d rows from %d", 
   "PrintProgressCancel": "Cancel report", 
   "ExportProgressCaption": "Generating report", 
   "ExportProgressText": "Finished %d%", 
   "ExportProgressCancel": "Cancel report", 
   "ExpandProgressCaption": "Expanding all rows", 
   "ExpandProgressText": "Finished %d rows from %d", 
   "ExpandProgressCancel": "Stop expanding", 
   "ExportCaption": "Select columns to export", 
   "PrintCaption": "Select columns to print", 
   "DefaultsAll": "Select all", 
"V6_1": "", 
   "DefaultsAlphabet": "%d ...", 
"V7_0": "", 
   "RemoveUnused": "Clearing unused pages ...", 
   "ErrorSave": "Saving changes on server failed!", 
   "DatesRepeat": "Repeat", 
   "DatesStart": "Start", 
   "DatesEndTime": "End", 
   "DatesValue": "Value", 
   "DatesRepeatEnum": "||Weekly|Daily|Hourly", 
   "DatesRepeatKeys": "||w|d|h", 
   "RenderProgressCaptionRows": "Rendering row pages", 
   "RenderProgressCaptionCols": "Rendering column pages", 
   "RenderProgressCaptionChildren": "Rendering tree pages", 
"V8_0": "", 
   "CalendarNone": "<s>None</s>", 
   "CalendarEmpty": "<s>Default</s>", 
   "CalendarEdit": "<i>Edit ...</i>", 
"V9_2": "", 
   "ExpandCols": "Expanding columns ...", 
   "CollapseCols": "Collapsing columns ...", 
"V9_3": "", 
   "PagingUpdate": "Creating pages ...", 
   "CopySlow": "The copy action took too long time (%d ms), please press the Ctrl+C again to finish the action", 
   "CopyOk": "The copy action finished successfuly", 
"V10_0": "", 
   "LevelsTip": "Expand rows up to %d level", 
"V12_0": "", 
   "FileIE": "Not available in IE<=9", 
   "Paste": "Pasting data from clipboard ...", 
   "FormulaError1": "Formula <b>%1</b> cannot be parsed", 
   "FormulaError2": "Incorrect cell reference in formula <b>%1</b>", 
   "FormulaError3": "Incorrect item <b>%2</b> in formula <b>%1</b>", 
   "FormulaError4": "Incorrect formula <b>%1</b> with error <i>%2</i>", 
   "FormulaError5": "Formula cannot be calculated with error <i>%2</i>", 
   "FormulaError6": "Formula <b>%1</b> returned <b>null</b> result", 
   "FormulaError7": "Formula <b>%1</b> returned <b>NaN</b> result", 
   "NotInList": "The value <b>%1</b> is not in the item list", 
   "EmptyValue": "empty", 
   "CannotEdit": "Not editable value", 
   "NoStyle": "Style cannot be changed", 
   "NoFormat": "Format cannot be changed", 
   "NoNumber": "Cell value is not a number", 
   "EditMaskError": "The value <b>%1</b> contains restricted characters", 
   "FormulaRestrict": "Formula <b>%1</b> is restricted with error <i>%2</i>", 
   "SizeChanged": "The value <b>%1</b> changed due size limit", 
   "ResultText": "The value <b>%1</b> is invalid", 
   "EditErrorsMessage": "%1", 
   "EditChangesMessage": "%1", 
   "EditErrorsMessageCell": "%1 in cell <b>%2</b><br>", 
   "EditChangesMessageCell": "%1 in cell <b>%2</b><br>", 
   "EditErrorsMessageMore": "There are <b>%1</b> more problems ...", 
   "FormulaCircular": "Formula contains circular cell reference", 
   "FormulaCircularAlert": "Formula contains circular cell reference", 
   "ErrAdd": "Cannot add new row to parent %1", 
   "ErrAddRoot": "Cannot add new row to root", 
   "DelSelectedCols": "Deleting columns ...", 
   "SearchFindPrev": "Prev", 
   "NoMenu": "No action available", 
   "SetStyleSame": "No cell was changed", 
   "SetStyleError": "No cell was changed due edit restrictions", 
   "SetStyleErrors": "There were not changed %1 cells due edit restrictions", 
"V13_0": "", 
   "PagerSep1": "\u00A0|\u00A0", 
   "PagerSep2": "\u00A0=>\u00A0", 
   "PagerSep3": ",\u00A0", 
   "PagerNone": "...", 
   "LoadSheet": "Reading sheet ...", 
   "DiscardSheet": "Do you want to discard all your data and load the data from file <b>%1</b>?", 
   "AddSheet": "Do you want to add the data from file <b>%1</b> to actual data?", 
   "OpenSheet": "Do you want to add the data from file <b>%1</b> to actual data<br>or discard all your data and load the data from file <b>%1</b>?", 
   "LoadSheetError": "Loading data from <b>%1</b> failed with error <b>%2</b>", 
   "ParseSheetError": "Parsing data from <b>%1</b> failed", 
   "SheetsUnsupported": "Opening files is not supported in your browser", 
   "DeleteSheet": "Do you want delete sheet <b>%1</b>?", 
   "DeleteTab": "Do you want delete tab <b>%1</b>?", 
   "OnlyXlsx": "Cannot open <b>%1</b>. Only <b>xlsx</b> files are supported", 
   "CompatibleStyles": "Compatible", 
   "ShrinkStyle": "Too large style, shrinking style size", 
   "SetSize": "Changing style size ...", 
   "UniqueSheet": " (%1)", 
   "ShrinkSize": "There is not enough space to display the grid fully<br>Do you want to shrink the grid style size?", 
   "EnterFormat": "Enter format string like in MS Excel", 
   "FormulaError8": "External reference to unknown sheet <b>%2</b> in formula <b>%1</b>", 
   "FormulaError9": "Not supported function <b>%2</b> in formula <b>%1</b>", 
   "FormulaError10": "Not supported reference to external file <b>%2</b> in formula <b>%1</b>", 
   "FormulaError11": "Not yet implemented array formula or unexpected cell range <b>%2</b> in formula <b>%1</b>", 
"V13_1": "", 
   "MoveRows": "Moving %d rows ...", 
"V13_3": "", 
   "NaNContinue": "The entered value is incorrect, please change it", 
   "NaNRejected": "The entered incorrect value has been ignored", 
   "NaNAccepted": "The entered incorrect value has been changed", 
   "NaNAsk": "The entered value is incorrect, do you want to save it anyway?", 
   "NaNAskReject": "The entered value is incorrect, do you want to discard it?", 
"V14_0": "", 
   "DownloadSyncComplete": "Download completed!", 
   "PasteError": "The value <b>%1</b> cannot be pasted", 
   "PasteChanged": "The value <b>%1</b> was changed to empty to paste", 
"V15_0": "", 
   "EnterLink": "Enter the hyperlink URL", 
   "ExternalFocus": "%1", 
   "ExternalFocusRect": "%1 => %2 : %3", 
   "ExternalFocusWait": "Focusing ...", 
   "EnterImageOpacity": "Enter image opacity (0 - transparent, 100 - opaque)", 
   "EnterImageName": "Enter image name", 
   "SetContrast": "Changing style contrast ...", 
   "FormulaErrorTimeout": "<span style='color:red;'>Calculation timeout expired! Not all formulas were calculated!</span><br><br>", 
   "PageRows": "%1 - %2", 
   "FormulaError12": "Incorrect name <b>%2</b> in formula <b>%1</b>", 
   "EnterDefinedName": "Enter name for %1", 
   "EnterDefinedValue": "Enter value for name %1", 
   "GlobalName": "%1", 
   "GlobalNameDup": "%1 (global)", 
   "LocalName": "%1", 
   "LocalNameDup": "%1 (local)"  
    }, 



// Gantt texts 

"Gantt" : { 

"V6_0": "", 
   "ErrGanttDep": "Cannot connect dependency here", 
   "ErrGanttPercentEdit": "Wrong input, the value must be in range 0 - 100", 
   "DelAllGanttDep": "Disconnect all dependencies", 
   "DelGanttMilestone": "Delete milestone", 
   "EditGanttPercent": "Enter completed status", 
   "DelGanttFlow": "Delete real flow", 
   "DelGanttFlowPart": "Delete the real flow bar", 
   "DelGanttFlags": "Delete all flags", 
   "DelGanttFlag": "Delete the flag", 
   "EditGanttFlag": "Enter the flag text", 
   "DelGanttAll": "Clear the gantt cell", 
   "NewGanttFlag": "Add new flag to selected point", 
   "EditGanttResource": "Change resources", 
   "AssignGanttResource": "Assign resources", 
   "CorrectAllDependencies": "Correct all dependencies in chart", 
   "CorrectRelatedDependencies": "Correct related dependencies", 
   "CorrectDep": "Moving %d bars ...", 
   "GanttFlagEdit": "Enter text for the flag", 
   "GanttPercentEdit": "Enter new completed status in percent", 
   "GanttResourceEdit": "Enter the resource text", 
   "GanttDepLagEdit": "Enter the lag for the dependency", 
"V6_1": "", 
   "GanttResizeDelete": "Are you sure to delete the item?", 
   "DelGanttRunPart": "Delete the box", 
   "EditGanttRun": "Change the box text", 
   "EditGanttRunTip": "Change the box information", 
   "GanttRunEdit": "Enter the box text", 
   "GanttRunEditTip": "Enter the box information", 
   "ChooseGanttFlagIcon": "Select the flag icon", 
"V6_3": "", 
   "GanttCorrectDependencies": "There are also <b>%d</b> dependent tasks that should be updated. <br>Do you want to move them?", 
   "GanttCorrectDependency": "There is also one dependent task that should be updated. Do you want to move it?", 
   "GanttCorrectTask": "The task violates its constraints, do you want to move it?", 
   "GanttDeleteDependencies": "There are %d dependencies, do you want to delete them?", 
   "GanttCircularDependencies": "It will cause circular dependency relation. Do you want to create it anyway?", 
   "GanttCircularDependenciesErr": "It is not possible to create circular dependency relation", 
   "ErrComplete": "The complete value must be in range 0 - 100!", 
   "ErrDuration": "The duration value is incorrect!", 
   "ErrEnd": "The end date cannot be less than start date!", 
   "ErrDependency": "The dependency value is incorrect!", 
   "ErrCorrect": "It is not possible to correct the dependencies!", 
   "ErrCorrectSome": "Not all dependencies were corrected due constraints!", 
   "IncorrectDependencies": "<em><b>%d</b> incorrect dependencies</em>", 
   "IncorrectDependency": "<em><b>1</b> incorrect dependency</em>", 
   "CorrectDependencies": "All dependencies are correct", 
   "DisabledDependencies": "<s>Dependency checking disabled</s>", 
   "GanttCheckExclude": "The object starts on holiday, do you want to move it to the right?", 
   "GanttMinStart": "The task must start after <b>%d</b>", 
   "GanttMaxStart": "The task must start before <b>%d</b>", 
   "GanttMinEnd": "The task must finish after <b>%d</b>", 
   "GanttMaxEnd": "The task must finish before <b>%d</b>", 
   "DelGanttConstraint": "Delete %d constraint", 
   "DelGanttConstraints": "Delete all constraints", 
   "ChangeGanttConstraint": "Set the constraint as %d", 
   "NewGanttConstraint": "Add %d constraint here", 
   "MinStart": "early start", 
   "MaxStart": "late start", 
   "MinEnd": "early end", 
   "MaxEnd": "late end", 
   "ExactStart": "mandatory start", 
   "ExactEnd": "mandatory end", 
   "SplitGanttConstraint": "Split the %d constraint", 
   "GanttDepLagChangeEnd": "Change lag of line from <b>%d</b>", 
"V6_4": "", 
   "GanttExactStart": "The task must start on <b>%d</b>", 
   "GanttExactEnd": "The task must finish on <b>%d</b>", 
   "ExtraPrice": "Extra price", 
   "ExtraPrices": "Extra resource units", 
   "DelGanttPoint": "Delete the point", 
   "DelGanttPoints": "Delete all points", 
   "NewGanttPoint": "Add new point to selected point", 
"V6_5": "", 
   "ErrStart": "The start date cannot be higher than end date!", 
"V6_6": "", 
   "GanttCheckExcludeBack": "The object ends on holiday, do you want to move it to the left?", 
   "DelGanttBase": "Delete project start", 
   "SetGanttBase": "Set project start here", 
   "DelGanttFinish": "Delete project finish", 
   "SetGanttFinish": "Set project finish here", 
   "NewGanttMilestone": "Add new milestone here", 
"V7_0": "", 
   "ErrDateLow": "The date cannot be before <em><b>%1</b></em> due <b>%2</b> constraint", 
   "ErrDateHigh": "The date cannot be after <em><b>%1</b></em> due <b>%2</b> constraint", 
   "Baseline": "project start", 
   "Finishline": "project finish", 
   "ChartMinStart": "project minimal date", 
   "ChartMaxEnd": "project maximal date", 
   "NewGanttEndMilestone": "Add new ending milestone here", 
   "ErrCorrectDep": "Not all dependencies were corrected due errors!", 
   "DelGanttRunGroup": "Delete row group (%d boxes)", 
   "DelGanttRunGroupAll": "Delete group (%d boxes)", 
   "ValueChanged": "Value changed due constraints", 
   "ErrChangeValue": "Entered value is incorrect", 
   "CompleteChanged": "Value changed to be in range 0 - 100", 
   "DurationChanged": "Value changed to be not negative", 
   "EditGanttRunText": "Enter the task information", 
   "SetGanttMilestoneIncomplete": "Set the milestone incomplete", 
   "SetGanttMilestoneComplete": "Set the milestone complete", 
   "ErrMoveChildren": "Cannot move the task due children constraints", 
   "MoveChildrenChanged": "Value changed due children constraints", 
   "NewGanttRunStop": "Add new stop here", 
   "GanttCorrectExclude": "The object starts or ends on holiday, do you want to correct it?", 
"V9_2": "", 
   "SplitGanttFlow": "Split the real flow bar", 
"V10_0": "", 
   "ZoomMain": "Zoom to the bar", 
   "ZoomRun": "Zoom to the box", 
   "ZoomAll": "Zoom to all objects", 
   "SplitGanttRun": "Split the box", 
   "SplitGanttMain": "Split the bar", 
   "DelGanttMainPart": "Delete the bar", 
   "DelGanttMain": "Delete the task", 
   "DelGanttMainAll": "Delete all tasks", 
   "DelGanttMainBar": "Delete task", 
   "DelGanttRun": "Delete all %d boxes in row", 
   "SelectGanttRunPart": "Select the box", 
   "UnselectGanttRunPart": "Unselect the box", 
   "SelectGanttRun": "Select all boxes", 
   "UnselectGanttRun": "Unselect all boxes", 
   "DelGanttRunSelected": "Delete selected boxes (%d boxes)", 
   "Plan0": "0", 
   "GanttTextEdit": "Enter the task information", 
   "EditGanttText": "Enter the task information", 
   "GanttDepLagChange": "Change the dependency lag", 
   "DelGanttDep": "Delete the dependency", 
   "DisableGanttMain": "Disable the task", 
   "EnableGanttMain": "Enable the task", 
   "LockGanttMain": "Lock the task", 
   "UnlockGanttMain": "Unlock the task", 
   "DisableGanttRun": "Disable the task", 
   "EnableGanttRun": "Enable the task", 
   "LockGanttRun": "Lock the task", 
   "UnlockGanttRun": "Unlock the task", 
   "DisableGanttRunPart": "Disable the box", 
   "EnableGanttRunPart": "Enable the box", 
   "LockGanttRunPart": "Lock the box", 
   "UnlockGanttRunPart": "Unlock the box", 
   "SetGanttPercent": "Set completed status here", 
   "ErrLag": "The lag value is incorrect!", 
   "EmptyManual": "None", 
   "ErrCorrectNone": "Not all dependencies can be corrected due constraints!", 
   "ZoomHeader": "Zoom to <b>%d</b> %d - %d", 
   "ZoomUndo": "Zoom back to <b>%d</b>", 
   "ZoomIn": "Zoom in to <b>%d</b>", 
   "ZoomOut": "Zoom out to <b>%d</b>", 
   "ZoomFit": "Zoom to fit to actual space", 
"V11_0": "", 
   "JoinGanttRunSelected": "Join selected boxes", 
   "SplitGanttRunJoined": "Split joined boxes", 
   "JoinGanttRunAdjacent": "Join adjacent boxes", 
   "SplitGanttRunAdjacent": "Split joined adjacent boxes", 
   "ChooseGanttRunType": "Change the box", 
   "ChooseGanttRunRowType": "Change all %d boxes in row", 
   "ChooseGanttRunSelectedType": "Change selected %d boxes", 
   "ChooseGanttRunGroupType": "Change %d boxes in row group", 
   "ChooseGanttRunGroupAllType": "Change %d boxes in group", 
"V12_0": "", 
   "GanttPinchZoom": "Scale %d%", 
"V13_0": "", 
   "DelGanttRunContainerOnly": "Delete the container", 
   "DelGanttRunContainer": "Delete all %d boxes in container", 
   "EnableGanttRunContainer": "Enable all %d boxes in container", 
   "DisableGanttRunContainer": "Disable all %d boxes in container", 
   "LockGanttRunContainer": "Lock all %d boxes in  container", 
   "ChooseGanttRunContainerType": "Change all %d boxes in container", 
   "ChooseGanttRunContainer": "Change the container", 
   "AddGanttRunContainer": "Add new container for the box", 
"V13_1": "", 
   "SelectGanttRunContainer": "Select the container", 
   "UnselectGanttRunContainer": "Unselect the container", 
"V15_0": "", 
   "RemoveGanttRunPart": "Remove the box", 
   "RemoveGanttRunGroup": "Remove row group (%d boxes)", 
   "RemoveGanttRunGroupAll": "Remove group (%d boxes)", 
   "RemoveGanttRunSelected": "Remove selected boxes (%d boxes)"  
    }, 

"GanttUnits" : { 
"V10_0": "", 
   "ms": "millisecond", "ms10": "10 milliseconds", "ms100": "100 milliseconds", 
   "s": "second", "s2": "2 seconds", "s5": "5 seconds", "s10": "10 seconds", "s15": "15 seconds", "s30": "30 seconds", 
   "m": "minute", "m2": "2 minutes", "m5": "5 minutes", "m10": "10 minutes", "m15": "15 minutes", "m30": "30 minutes", 
   "h": "hour", "h2": "2 hours", "h3": "3 hours", "h6": "6 hours", "h8": "8 hours", "h12": "12 hours", 
   "d": "day", "w": "week", "w0": "week", "w1": "week", "w6": "week", 
   "M": "month", "M2": "2 months", "M3": "year quarter", "M4": "4 months", "M6": "year half", 
   "y": "year", "y2": "2 years", "y3": "3 years", "y4": "4 years", "y5": "5 years", "y10": "10 years", "y20": "20 years", "y50": "50 years"  
    }, 



// Popup dialog buttons, non HTML 

"MenuButtons" : { 
      
"V6_0": "", 
   "Ok": "OK", 
   "Clear": "Clear", 
   "Today": "Today", 
   "All": "All on", 
   "Cancel": "Cancel", 
"V6_7": "", 
   "Yesterday": "Yesterday", 
"V7_0": "", 
   "EmptyTip": "Empty date", 
"V10_0": "", 
   "Yes": "Yes", 
   "No": "No", 
   "Always": "Always", 
   "Never": "Never", 
"V12_1": "", 
   "ShowAll": "Show all", 
   "HideAll": "Hide all", 
   "Reset": "Defaults", 
"V13_0": "", 
   "Add": "Add", 
   "Discard": "Discard", 
   "Once": "Once", 
"V13_1": "", 
   "Shrink": "Shrink style size"  
    }, 



// Cell menu item names (cell Menu attribute), HTML 
// %1 is replaced by count of affected rows, only for mass actions 

"MenuCell" : { 
      
"V6_0": "", 
   "CopyRow": "Duplicate the row", 
   "CopyRowBelow": "Duplicate the row", 
   "CopyTree": "Duplicate the row tree", 
   "CopyTreeBelow": "Duplicate the row tree", 
   "CopyEmpty": "Add empty row tree above", 
   "CopyEmptyBelow": "Add empty row tree below", 
   "CopySelected1": "Copy selected row above", 
   "CopySelectedBelow1": "Copy selected row below", 
   "CopySelectedTree1": "Copy selected row tree above", 
   "CopySelectedTreeBelow1": "Copy selected row tree below", 
   "CopySelectedEmpty1": "Add selected empty row tree above", 
   "CopySelectedEmptyBelow1": "Add selected empty row tree below", 
   "CopySelectedChild1": "Copy selected row as the first child", 
   "CopySelectedTreeChild1": "Copy selected row tree as the first child", 
   "CopySelectedEmptyChild1": "Add selected empty row tree as the first child", 
   "CopySelectedChildEnd1": "Copy selected row as the last child", 
   "CopySelectedTreeChildEnd1": "Copy selected row tree as the last child", 
   "CopySelectedEmptyChildEnd1": "Add selected empty row tree as the last child", 
   "CopySelectedEnd1": "Copy selected row to the end", 
   "CopySelectedEndPage1": "Copy selected row to the end of page", 
   "CopySelectedEndGrid1": "Copy selected row to the end of grid", 
   "CopySelectedTreeEnd1": "Copy selected row tree to the end", 
   "CopySelectedTreeEndPage1": "Copy selected row tree to the end of page", 
   "CopySelectedTreeEndGrid1": "Copy selected row tree to the end of grid", 
   "CopySelectedEmptyEnd1": "Add selected empty row tree to the end", 
   "CopySelectedEmptyEndPage1": "Add selected empty row tree to the end of page", 
   "CopySelectedEmptyEndGrid1": "Add selected empty row tree to the end of grid", 
   "CopySelected": "Copy %1 selected rows above", 
   "CopySelectedBelow": "Copy %1 selected rows below", 
   "CopySelectedTree": "Copy %1 selected row trees above", 
   "CopySelectedTreeBelow": "Copy %1 selected row trees below", 
   "CopySelectedEmpty": "Add %1 selected empty row trees above", 
   "CopySelectedEmptyBelow": "Add %1 selected empty row trees below", 
   "CopySelectedChild": "Copy %1 selected rows as the first children", 
   "CopySelectedTreeChild": "Copy %1 selected row trees as the first children", 
   "CopySelectedEmptyChild": "Add %1 selected empty row trees as the first children", 
   "CopySelectedChildEnd": "Copy %1 selected rows as the last children", 
   "CopySelectedTreeChildEnd": "Copy %1 selected row trees as the last children", 
   "CopySelectedEmptyChildEnd": "Add %1 selected empty row trees as the last children", 
   "CopySelectedEnd": "Copy %1 selected rows to the end", 
   "CopySelectedEndPage": "Copy %1 selected rows to the end of page", 
   "CopySelectedEndGrid": "Copy %1 selected rows to the end of grid", 
   "CopySelectedTreeEnd": "Copy %1 selected row trees to the end", 
   "CopySelectedTreeEndPage": "Copy %1 selected row trees to the end of page", 
   "CopySelectedTreeEndGrid": "Copy %1 selected row trees to the end of grid", 
   "CopySelectedEmptyEnd": "Add %1 selected empty row trees to the end", 
   "CopySelectedEmptyEndPage": "Add %1 selected empty row trees to the end of page", 
   "CopySelectedEmptyEndGrid": "Add %1 selected empty row trees to the end of grid", 

   "AddRow": "Add new empty row above", 
   "AddChild": "Add new empty row as the first child", 
   "AddChildEnd": "Add new empty row as the last child", 
   "AddRowBelow": "Add new empty row below", 
   "AddRowEnd": "Add new empty row to the end", 
   "AddRowEndPage": "Add new empty row to the end of page", 
   "AddRowEndGrid": "Add new empty row to the end of grid", 

"V12_0": "", 
   "CopyRows1": "Copy row above", 
   "CopyRowsBelow1": "Copy row below", 
   "CopyRowsTree1": "Copy row tree above", 
   "CopyRowsTreeBelow1": "Copy row tree below", 
   "CopyRowsEmpty1": "Add empty row tree above", 
   "CopyRowsEmptyBelow1": "Add empty row tree below", 
   "CopyRows": "Copy %1 rows above", 
   "CopyRowsBelow": "Copy %1 rows below", 
   "CopyRowsTree": "Copy %1 row trees above", 
   "CopyRowsTreeBelow": "Copy %1 row trees below", 
   "CopyRowsEmpty": "Add %1 empty row trees above", 
   "CopyRowsEmptyBelow": "Add %1 empty row trees below", 

   "AddRows1": "Add new empty row above", 
   "AddRowsBelow1": "Add new empty row below", 
   "AddSelected1": "Add new empty row above", 
   "AddSelectedBelow1": "Add new empty row below", 
   "AddRows": "Add new %1 empty rows above", 
   "AddRowsBelow": "Add new %1 empty rows below", 
   "AddSelected": "Add new %1 empty rows above", 
   "AddSelectedBelow": "Add new %1 empty rows below", 

   "DeleteRow": "Delete row", 
   "UndeleteRow": "Undelete row", 
   "RemoveRow": "Remove row", 
   "DeleteRows1": "Delete row", 
   "UndeleteRows1": "Undelete row", 
   "RemoveRows1": "Remove row", 
   "DeleteSelected1": "Delete selected row", 
   "UndeleteSelected1": "Undelete selected row", 
   "RemoveSelected1": "Remove selected row", 
   "DeleteRows": "Delete %1 rows", 
   "UndeleteRows": "Undelete %1 rows", 
   "RemoveRows": "Remove %1 rows", 
   "DeleteSelected": "Delete %1 selected rows", 
   "UndeleteSelected": "Undelete %1 selected rows", 
   "RemoveSelected": "Remove %1 selected rows", 

   "CopyCol": "Duplicate the column", 
   "CopyColNext": "Duplicate the column", 
   "CopyCols1": "Copy column left", 
   "CopyColsNext1": "Copy column right", 
   "CopySelectedCols1": "Copy selected column left", 
   "CopySelectedColsNext1": "Copy selected column right", 
   "CopyCols": "Copy %1 columns left", 
   "CopyColsNext": "Copy %1 columns right", 
   "CopySelectedCols": "Copy %1 selected columns left", 
   "CopySelectedColsNext": "Copy %1 selected columns right", 

   "AddCol": "Add new empty column left", 
   "AddColNext": "Add new empty column right", 
   "AddCols1": "Add new empty column left", 
   "AddColsNext1": "Add new empty column right", 
   "AddSelectedCols1": "Add new empty column left", 
   "AddSelectedColsNext1": "Add new empty column right", 
   "AddCols": "Add new %1 empty columns left", 
   "AddColsNext": "Add new %1 empty columns right", 
   "AddSelectedCols": "Add new %1 empty columns left", 
   "AddSelectedColsNext": "Add new %1 empty columns right", 
   "AddColEnd": "Add new empty column to the end", 

   "DeleteCol": "Delete column", 
   "UndeleteCol": "Undelete column", 
   "RemoveCol": "Remove column", 
   "DeleteCols1": "Delete column", 
   "UndeleteCols1": "Undelete column", 
   "RemoveCols1": "Remove column", 
   "DeleteSelectedCols1": "Delete selected column", 
   "UndeleteSelectedCols1": "Undelete selected column", 
   "RemoveSelectedCols1": "Remove selected column", 
   "DeleteCols": "Delete %1 columns", 
   "UndeleteCols": "Undelete %1 columns", 
   "RemoveCols": "Remove %1 columns", 
   "DeleteSelectedCols": "Delete %1 selected columns", 
   "UndeleteSelectedCols": "Undelete %1 selected columns", 
   "RemoveSelectedCols": "Remove %1 selected columns", 

   "ClearSelection": "Unselect all %1 rows and columns", 
   "SelectRow": "Select row", 
   "DeselectRow": "Unselect row", 
   "SelectFocusedRows1": "Select focused row", 
   "DeselectFocusedRows1": "Unselect focused row", 
   "SelectFocusedRows": "Select %1 focused rows", 
   "DeselectFocusedRows": "Unselect %1 focused rows", 
   "SelectAll1": "Select the only row", 
   "DeselectAll1": "Unselect the only row", 
   "InvertAll1": "Invert selection the only row rows", 
   "SelectAll": "Select all %1 rows", 
   "DeselectAll": "Unselect all %1 rows", 
   "InvertAll": "Invert selection of all %1 rows", 
   "SelectCol": "Select column", 
   "DeselectCol": "Unselect column", 
   "SelectFocusedCols1": "Select focused column", 
   "DeselectFocusedCols1": "Unselect focused column", 
   "SelectFocusedCols": "Select %1 focused columns", 
   "DeselectFocusedCols": "Unselect %1 focused columns", 
   "SelectCell": "Select cell", 
   "DeselectCell": "Unselect cell", 
   "SelectRowRange1": "Select the row", 
   "DeselectRowRange1": "Unselect the row", 
   "SelectColRange1": "Select the column", 
   "DeselectColRange1": "Unselect the column", 
   "SelectCellRange1": "Select the cell", 
   "DeselectCellRange1": "Unselect the cell", 
   "SelectColCells1": "Select the only cell in column", 
   "DeselectColCells1": "Unselect the only cell in column", 
   "SelectRowCells1": "Select the only cell in row", 
   "DeselectRowCells1": "Unselect the only cell in row", 
   "SelectAllCells1": "Select the only cell", 
   "DeselectAllCells1": "Unselect the only cell", 
   "SelectAllCols1": "Select the only column", 
   "DeselectAllCols1": "Unselect the only column", 
   "SelectRowRange": "Select %1 rows in the area", 
   "DeselectRowRange": "Unselect %1 rows in the area", 
   "SelectColRange": "Select %1 columns in the area", 
   "DeselectColRange": "Unselect %1 columns in the area", 
   "SelectCellRange": "Select %1 cells in the area", 
   "DeselectCellRange": "Unselect %1 cells in the area", 
   "SelectColCells": "Select all %1 cells in column", 
   "DeselectColCells": "Unselect all %1 cells in column", 
   "SelectRowCells": "Select all %1 cells in row", 
   "DeselectRowCells": "Unselect all %1 cells in row", 
   "SelectAllCells": "Select all %1 cells", 
   "DeselectAllCells": "Unselect all %1 cells", 
   "SelectAllCols": "Select all %1 columns", 
   "DeselectAllCols": "Unselect all %1 columns", 

   "Span": "Span cells", 
   "Split": "Split spanned cells", 

   "Expand": "Expand row", 
   "Collapse": "Collapse row", 
   "ExpandAll1": "Expand the only row", 
   "CollapseAll1": "Collapse the only row", 
   "CollapseAllRoot1": "Collapse the root row", 
   "ExpandAll": "Expand all %1 rows", 
   "CollapseAll": "Collapse all %1 rows", 
   "CollapseAllRoot": "Collapse all %1 root rows", 
   "Outdent1": "Outdent row", 
   "Indent1": "Indent row", 
   "Outdent": "Outdent %1 rows", 
   "Indent": "Indent %1 rows", 

   "ExpandCell": "Expand or collapse cell", 
   "ExpandCol": "Expand column", 
   "CollapseCol": "Collapse column", 
   "ExpandRow": "Expand row", 
   "CollapseRow": "Collapse row", 
   "ExpandAllCells": "Expand all columns", 
   "CollapseAllCells": "Collapse all columns", 
   "ExpandRowCells": "Expand all columns in row", 
   "CollapseRowCells": "Collapse all columns in row", 

   "HideRows1": "Hide row", 
   "HideRows": "Hide %1 rows", 
   "ShowRowAbove": "Show hidden row above", 
   "ShowRowBelow": "Show hidden row below", 
   "ShowRows1": "Show hidden row", 
   "ShowRowsW": "Show all %1 hidden rows", 
   "ShowRows": "Show %1 hidden rows", 

   "HideCols1": "Hide column", 
   "HideCols": "Hide %1 columns", 
   "ShowColLeft": "Show hidden column on the left", 
   "ShowColRight": "Show hidden column on the right", 
   "ShowCols1": "Show hidden column", 
   "ShowColsW": "Show all %1 hidden columns", 
   "ShowCols": "Show %1 hidden columns", 

   "SearchOn": "Enable search", 
   "SearchOff": "Disable search", 

   "SortAsc": "Sort by the column ascending", 
   "SortDesc": "Sort by the column descending", 
   "SortAscOne": "Sort by the one column ascending", 
   "SortDescOne": "Sort by the one column descending", 
   "SortAscAppend": "Sort by the next column ascending", 
   "SortDescAppend": "Sort by the next column descending", 
   "NoSort": "Do not sort by the column", 
   "DefaultSort": "Restore original sorting", 
   "SortOn": "Enable sorting", 
   "SortOff": "Disable sorting", 

   "Undo": "Undo last action", 
   "UndoAll1": "Undo the action", 
   "UndoAll": "Undo all %1 actions", 
   "Redo": "Redo last undone action", 
   "RedoAll1": "Redo the undone action", 
   "RedoAll": "Redo all %1 undone actions", 
   "ClearUndo": "Clear undo buffer", 

   "Print": "Print the grid", 
   "ExportPDF": "Print the grid to PDF", 
   "Export": "Export the grid to XLSX, XLS or CSV", 
   "Repaint": "Repaint, clear unused pages", 
   "RenderPages": "Change the paging", 
   "PagingOn": "Enable paging, clear unused pages", 
   "PagingOff": "Disable paging, render all pages", 
   "ShowCfg": "Show configuration menu", 
   "ShowColumns": "Choose visible columns and rows", 
   "ShowDebug": "Show debug window", 
   "Reload": "Reload grid, cancel changes", 
   "Validate": "Check the data for errors", 
   "Save": "Save changes to server", 

   "GoUp": "Focus up", 
   "GoUpEdit": "Focus up", 
   "GoDown": "Focus down", 
   "GoDownEdit": "Focus down", 
   "GoDownAdd": "Focus down", 
   "GoDownEditAdd": "Focus down", 
   "GoLeft": "Focus left", 
   "GoLeftEdit": "Focus left", 
   "GoRight": "Focus right", 
   "GoRightEdit": "Focus right", 
   "GoFirst": "Focus first row", 
   "GoLast": "Focus last row", 
   "PageDown": "Go to next page", 
   "PageUp": "Go to previous page", 
   "PageDownFull": "Go to next page", 
   "PageUpFull": "Go to previous page", 

   "ShowDetail": "Show the row detail", 
   "RefreshDetail": "Show the row detail", 
   "ClearDetail": "Clear the detail", 

   "ShowHintStatic": "Show full cell content", 
   "GridResizeDefault": "Restore grid size", 

   "GroupBy": "Group by the column", 
   "GroupByLast": "Add the column to grouping", 
   "UngroupBy": "Ungroup by the column", 
   "GroupOn": "Enable grouping", 
   "GroupOff": "Disable grouping", 

   "Focus": "Focus cell", 
   "FocusEdit": "Focus and edit cell", 
   "FocusAndEdit": "Focus and edit cell", 
   "ChangeFocus": "Focus cell", 
   "ChangeFocusRow": "Focus row cell", 
   "ChangeFocusCol": "Focus column cell", 
   "Blur": "Remove focus", 
   "BlurFocused": "Remove focus", 
   "FocusWholeRow": "Focus all cells in row", 
   "FocusWholeCol": "Focus all cells in column", 
   "FocusWholeGrid": "Focus all cells in grid", 

   "StartEdit": "Edit focused cell", 
   "StartEditEmpty": "Edit focused cell empty", 
   "StartEditCell": "Edit the cell", 
   "StartEditCellEmpty": "Edit the cell empty", 
   "CancelEdit": "Cancel editing", 
   "AcceptEdit": "Finish editing", 
   "ShowCalendar": "Pick up date from calendar", 
   "ShowDates": "Pick up dates from table", 
   "ShowLink": "Navigate to url", 
   "Button": "Press the button", 
   "ButtonClick": "Press the right button", 
   "IconClick": "Press the left button", 
   "ShowHelp": "Show help", 
   "ShowFile": "Pick up a file", 
   "ShowDefaults": "Show predefined items", 
   "ShowDefaultsMenu": "Show predefined items", 

   "ChangeBool": "Change checkbox", 
   "CheckBool": "Check the icon", 
   "UncheckBool": "Uncheck the icon", 
   "ClearBool": "Clear the cell", 
   "ChangeRadioLeft": "Cycle radio left", 
   "ChangeRadioLeftCycle": "Cycle radio left", 
   "ChangeRadioRight": "Cycle radio right", 
   "ChangeRadioRightCycle": "Cycle radio right", 
   "CheckIcon": "Check the icon", 
   "UncheckIcon": "Uncheck the icon", 
   "SetChecked": "Change checkbox", 

   "ShowFilterMenu": "Show filter menu", 
   "ShowFilterMenuRow": "Show filter menu", 
   "FilterBy": "Filter by the cell value", 
   "FilterByMenu": "Choose filter for the cell value", 
   "FilterByMenuRow": "Choose filter for the cell value", 
   "ClearFilter": "Clear filter for the column", 
   "ClearFilters": "Clear all filters", 
   "FilterOn": "Enable filtering", 
   "FilterOff": "Disable filtering", 

   "ClearCell": "Clear", 
   "ClearValueStyle": "Clear value & style", 
   "ClearValue": "Clear value", 
   "ClearStyle": "Clear style", 

   "SetCellAbsolute": "Set the cell reference absolute", 
   "SetCellRelative": "Set the cell reference relative", 
   "SwitchCellAbsolute": "Switch cell reference", 
   "SwitchRowColAbsolute": "Switch cell reference", 
   "ChooseRowInsert": "Insert row reference", 
   "ChooseRowReplace": "Replace row reference", 
   "ChooseRowReplaceAll": "Replace row reference", 
   "ChooseColInsert": "Insert column reference", 
   "ChooseColReplace": "Replace column reference", 
   "ChooseColReplaceAll": "Replace column reference", 
   "ChooseCellInsert": "Insert cell reference", 
   "ChooseCellReplace": "Replace cell reference", 
   "ChooseCellReplaceAll": "Replace cell reference", 

   "CalcOn": "Enable calculations", 
   "CalcOff": "Disable calculations", 

   "ClearBorder": "Default border", 
   "ClearBorderOut": "Default outer border", 
   "ClearBorderIn": "Default inner border", 
   "ClearBorderTop": "Default top border", 
   "ClearBorderBottom": "Default bottom border", 
   "ClearBorderLeft": "Default left border", 
   "ClearBorderRight": "Default right border", 
   "SetBorder": "Set border", 
   "SetBorderTop": "Set top border", 
   "SetBorderBottom": "Set bottom border", 
   "SetBorderLeft": "Set left border", 
   "SetBorderRight": "Set right border", 
   "SetBorderOut": "Set outer border", 
   "SetBorderOutTop": "Set outer top border", 
   "SetBorderOutBottom": "Set outer bottom border", 
   "SetBorderOutLeft": "Set outer left border", 
   "SetBorderOutRight": "Set outer right border", 
   "SetBorderIn": "Set inner border", 
   "SetBorderInTop": "Set inner top border", 
   "SetBorderInBottom": "Set inner bottom border", 
   "SetBorderInLeft": "Set inner left border", 
   "SetBorderInRight": "Set inner right border", 
   "ChooseBorderEdge": "Choose border edge", 
   "ChooseBorderEdgeItems": "%1", 
   "ChooseBorderStyle": "Choose border style", 
   "ChooseBorderStyleItems": "%1", 
   "ChooseBorderColor": "Choose border color", 
   "ChooseBorderColorItems": "<span style='background:%2;padding-left:15px;margin-right:5px;border-radius:50px;'></span>%1", 
   "ChooseBorder": "Choose border", 

   "RotateLeft": "Rotate left", 
   "RotateRight": "Rotate right", 
   "NoRotate": "Clear rotation", 
   "VertAlignTop": "Align top", 
   "VertAlignBottom": "Align bottom", 
   "VertAlignMiddle": "Center vertically", 
   "NoVertAlign": "Default vertical alignment", 
   "AlignLeft": "Align left", 
   "AlignRight": "Align right", 
   "AlignCenter": "Center horizontally", 
   "NoAlign": "Default horizontal alignment", 
   "WrapOn": "Wrap", 
   "WrapOff": "No wrap", 
   "NoWrap": "Default wrap", 
   "NoTextStyle": "Default text style", 
   "BoldOn": "Bold", 
   "BoldOff": "No bold", 
   "ItalicOn": "Italic", 
   "ItalicOff": "No italic", 
   "UnderlineOn": "Underline", 
   "UnderlineOff": "No underline", 
   "StrikeOn": "Strike", 
   "StrikeOff": "No strike", 
   "OverlineOn": "Overline", 
   "OverlineOff": "No overline", 
   "SmallCapsOn": "Small caps", 
   "SmallCapsOff": "No small caps", 
   "SetTextColor": "Set text color", 
   "NoTextColor": "Default text color", 
   "ChooseTextColor": "Choose text color", 
   "ChooseTextColorItems": "<span style='background:%2;padding-left:15px;margin-right:5px;border-radius:50px;'></span>%1", 
   "SetColor": "Set background color", 
   "NoColor": "Default background color", 
   "ChooseColor": "Choose background color", 
   "ChooseColorItems": "<span style='background:%2;padding-left:15px;margin-right:5px;border-radius:50px;'></span>%1", 
   "SetTextSize": "Set font size", 
   "NoTextSize": "Default font size", 
   "ChooseTextSize": "Choose font size", 
   "ChooseTextSizeItems": "%1", 
   "SetTextFont": "Set font name", 
   "NoTextFont": "Default font name", 
   "ChooseTextFont": "Choose font name", 
   "ChooseTextFontItems": "%1", 
   "SetTextShadowColor": "Set shadow color", 
   "NoTextShadowColor": "Default shadow color", 
   "ChooseTextShadowColor": "Choose shadow color", 
   "ChooseTextShadowColorItems": "<span style='background:%2;padding-left:15px;margin-right:5px;border-radius:50px;'></span>%1", 
   "SetTextShadow": "Set shadow", 
   "NoTextShadow": "No shadow", 
   "ChooseTextShadow": "Choose shadow", 
   "ChooseTextShadowItems": "%1", 

   "SetEditable": "Permit editing", 
   "SetReadOnly": "Restrict editing", 
   "SetPreview": "Set as read only", 
   "ClearEditable": "Restrict editing when locked", 

   "ShowFormula": "Show formula", 
   "HideFormula": "Hide formula", 
   "DefaultFormula": "Hide formula when locked", 

   "ChooseFormat": "Choose format", 
   "SetFormat": "Set format", 

"V12_1": "", 
   "Copy": "Copy to clipboard", 
   "Exclude": "Cut to clipboard", 

"V13_0": "", 
   "Import": "Import local XLSX file to the grid", 

"V15_0": "", 
   "ShowCellLink": "Navigate to url", 
   "SetLink1": "Enter the link", 
   "SetLinkE": "Enter the link", 
   "SetLink": "Enter the %1 links", 
   "ClearLink1": "Remove the link", 
   "ClearLinkE": "Remove the link", 
   "ClearLink": "Remove the %1 links", 

   "OpenImage": "Insert local image file", 

   "UpperCase1": "To upper case", 
   "UpperCaseE": "To upper case", 
   "UpperCase": "%1 texts to upper case", 
   "LowerCase1": "To lower case", 
   "LowerCaseE": "To lower case", 
   "LowerCase": "%1 texts to lower case", 

   "IncreaseTextSizeE": "Increase font size", 
   "IncreaseTextSize": "Increase font size", 
   "DecreaseTextSizeE": "Decrease font size", 
   "DecreaseTextSize": "Decrease font size", 

   "Superscript": "Text in superscript", 
   "Subscript": "Text in subscript", 
   "Noscript": "No super/subscript", 
   "SetTextLine": "Set line decoration", 
   "NoTextLine": "Default line decoration", 
   "ChooseTextLine": "Choose line decoration", 
   "ChooseTextLineItems": "<span style='text-decoration:%1 line-through;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span>", 
   "SetPattern": "Set background pattern", 
   "NoPattern": "No background pattern", 
   "ChoosePattern": "Choose background pattern", 
   "ChoosePatternItems": "<span style='background-image:%1;padding-left:50px;line-height:16px;font-size:16px;'></span>", 
   "SetPatternColor": "Set background pattern color", 
   "NoPatternColor": "Default background pattern color", 
   "ChoosePatternColor": "Choose background pattern color", 
   "ChoosePatternColorItems": "<span style='background:%2;padding-left:15px;margin-right:5px;border-radius:50px;'></span>%1", 

   "RotateLeft30": "Rotate left by 30 degrees", 
   "RotateRight30": "Rotate right by 30 degrees", 
   "RotateLeft45": "Rotate left by 45 degrees", 
   "RotateRight45": "Rotate right by 45 degrees", 
   "RotateLeft60": "Rotate left by 60 degrees", 
   "RotateRight60": "Rotate right by 60 degrees", 
   "RotateLeft90": "Rotate left by 90 degrees", 
   "RotateRight90": "Rotate right by 90 degrees", 
   "RotateLeftVert": "Rotate left vertically", 
   "RotateRightVert": "Rotate right vertically", 

   "VertAlignTopE": "Text in superscript", 
   "SuperscriptE": "Text in superscript", 
   "VertAlignBottomE": "Text in subscript", 
   "SubscriptE": "Text in subscript", 
   "VertAlignMiddleE": "No super/subscript", 
   "NoVertAlignE": "No super/subscript", 
   "NoscriptE": "No super/subscript", 
   "BoldOnE": "Bold on/off", 
   "BoldOffE": "", 
   "ItalicOnE": "Italic on/off", 
   "ItalicOffE": "", 
   "UnderlineOnE": "Underline on/off", 
   "UnderlineOffE": "", 
   "StrikeOnE": "Strike on/off", 
   "StrikeOffE": "", 
   "SetTextLineE": "Set line decoration", 
   "NoTextLineE": "Default line decoration", 
   "ChooseTextLineE": "Choose line decoration", 
   "SetTextColorE": "Set text color", 
   "NoTextColorE": "Default text color", 
   "ChooseTextColorE": "Choose text color", 
   "SetColorE": "Set text background color", 
   "NoColorE": "Default text background color", 
   "ChooseColorE": "Choose text background color", 
   "SetTextSizeE": "Set font size", 
   "NoTextSizeE": "Default font size", 
   "ChooseTextSizeE": "Choose font size", 
   "SetTextFontE": "Set font name", 
   "NoTextFontE": "Default font name", 
   "ChooseTextFontE": "Choose font name", 
   "SetTextShadowColorE": "Set shadow color", 
   "NoTextShadowColorE": "Clear shadow color", 
   "ChooseTextShadowColorE": "Choose shadow color", 
   "ClearStyleE": "Clear all styles", 

   "ShowColTreeLevel": "Expand columns to this level", 
   "IndentCols1": "Indent column", 
   "IndentColsForce1": "Indent column", 
   "OutdentCols1": "Outdent column", 
   "OutdentColsForce1": "Outdent column", 
   "IndentCols": "Indent %1 columns", 
   "IndentColsForce": "Indent %1 columns", 
   "OutdentCols": "Outdent %1 columns", 
   "OutdentColsForce": "Outdent %1 columns", 

   "FixAbove": "Freeze previous rows above", 
   "FixBelow": "Freeze next rows below", 
   "FixPrev": "Freeze previous columns to the left", 
   "FixNext": "Freeze next columns to the right", 

   "RestoreImage": "Restore image size/position/rotation", 
   "RestoreImageSize": "Set image size to default", 
   "RestoreImageRotation": "Do not rotate image", 
   "RestoreImagePosition": "Move image to its original position", 
   "AssignImage": "Move image to its top left cell", 
   "DeleteImage": "Delete image", 
   "DuplicateImage": "Duplicate image", 
   "DragImageClear": "Dragging image will do default action", 
   "DragImageResize": "Dragging image will resize it", 
   "DragImageResizeXY": "Dragging image will resize it it in one direction", 
   "DragImageResizeFree": "Dragging image will resize it without aspect ratio", 
   "DragImageRotate": "Dragging image will rotate it", 
   "DragImageCrop": "Dragging image will crop it", 
   "DragImageMove": "Dragging image will move it", 
   "DragImageMoveXY": "Dragging image will move it in one direction", 
   "DragImageCopy": "Dragging image will copy it", 
   "DragImageCopyXY": "Dragging image will copy it in one direction", 
   "DragImageNone": "Dragging image will be restricted", 
   "EnterImageOpacity": "Enter image opacity", 
   "EnterImageName": "Enter image name", 
   "FloatImage": "Float image outside cell", 
   "TextImage": "Include image into cell text", 

   "AutoSpan": "Auto span cell", 
   "AutoRowSpan": "Auto span cell vertically", 
   "AutoColSpan": "Auto span cell horizontally", 

   "Lock": "Lock / unlock grid", 
   "Lock0": "Unlock grid", 
   "Lock1": "Lock grid structure", 
   "Lock2": "Lock grid structure & styles", 
   "Lock3": "Lock grid fully", 

   "DefineName": "Define name", 
   "DefineGlobalName": "Define global name", 
   "EditName": "Change name", 
   "DeleteName": "Delete name", 

"V16_0": "", 
   "HideSheet": "Hide sheet", 
   "ShowSheets": "Show sheet", 
   "ShowSheetsItems": "%1"  
    }, 



// Configuration menu item names, HTML 
      
"MenuCfg" : { 
         
"V2_3": "", 		
   "Caption": "TreeGrid settings", 
   "ShowDeleted": "Show deleted rows (in red)", 
   "AutoSort": "Auto sort rows after change", 
   "AutoUpdate": "Auto update changes to server", 
   "MouseHover": "Mouse hover", 
   "Hover1": "None", 
   "Hover2": "Cell only", 
   "Hover3": "Row", 
   "Hover4": "Row and column", 
   "ShowDrag": "Show dragged object", 
   "ShowPanel": "Show row's left panel", 
"V2_6": "", 
   "ShowPager": "Show pager", 
   "ShowAllPages": "Show all pages", 
"V4_4": "", 
   "CheckUpdates": "Check for updates on server every", 
   "CheckUpdates0": "Off", 
   "CheckUpdates2": "2 seconds", 
   "CheckUpdates5": "5 seconds", 
   "CheckUpdates10": "10 seconds", 
   "CheckUpdates30": "30 seconds", 
   "CheckUpdates60": "1 minute", 
   "CheckUpdates120": "2 minutes", 
   "CheckUpdates300": "5 minutes", 
   "CheckUpdates600": "10 minutes", 
"V5_0_20": "", 
   "SortClick": "Sorting click", 
   "SortClick1": "Simple, no icons", 
   "SortClick2": "Simple", 
   "SortClick3": "Directional, icons only", 
   "SortClick4": "Directional", 
"V6_3": "", 
   "GanttCorrectDependencies": "Schedule tasks", 
   "Correct1": "manually", 
   "Correct2": "auto", 
   "Correct3": "ask", 
   "GanttCheckDependencies": "Circular dependencies", 
   "Check1": "permit", 
   "Check2": "restrict", 
   "Check3": "ask", 
   "GanttHideExclude": "Show holidays in chart", 
   "GanttCheckExclude": "Starting tasks on holidays", 
   "GanttCorrectDependenciesFixed": "Auto schedule also the changed task", 
"V6_4": "", 
   "GanttBaseProof": "Can move objects before project start", 
   "GanttBasePreferred": "Project start is preferred to constraints", 
"V6_6": "", 
   "GanttMinSlack": "Minimal slack for critical task", 
   "GanttErrSlack": "Minimal slack bound for error task", 
   "GanttSeparateSlack": "Calculate critical path individually", 
"V6_7": "", 
   "Check4": "alert", 
"V7_0": "", 
   "GanttFixComplete": "Schedule also already started tasks", 
   "GanttFinishProof": "Can move objects after project finish", 
   "GanttFinishPreferred": "Project finish is preferred to constraints", 
   "Scrollbars": "Scrollbars type", 
   "Scrollbars1": "None", 
   "Scrollbars2": "Thin", 
   "Scrollbars3": "Standard", 
   "Scrollbars4": "Wide", 
   "Scroll": "Scroll by", 
   "Scroll1": "Only scrollbars", 
   "Scroll2": "One finger (no move)", 
   "Scroll3": "Two fingers (no zoom)", 
   "Scroll4": "Three fingers (no drag)", 
"V10_0": "", 
   "GanttCheck": "Incorrect manual inputs", 
   "GanttCheck1": "permit", 
   "GanttCheck2": "restrict", 
   "GanttCheck3": "restrict + alert", 
   "GanttCheck4": "correct", 
   "GanttCheck5": "correct + alert", 
   "ReversedTree": "Reversed tree (like in MS Excel)", 
   "GanttDirection": "Schedule tasks from", 
   "GanttDirection1": "project start", 
   "GanttDirection2": "project finish", 
   "GanttStrict": "Schedule tasks method", 
   "GanttStrict1": "minimal move", 
   "GanttStrict2": "strict move", 
   "GanttStrict3": "", 
   "GanttStrict4": "min. strict move", 
"V11_0": "", 
   "ShowButtons": "Show buttons", 
   "ShowButtons1": "Icons only", 
   "ShowButtons2": "Texts only", 
   "ShowButtons3": "Icons and texts", 
   "GanttCorrectOutsideBounds": "Schedule tasks outside project bounds", 
"V12_1": "", 
   "CfgCaption": "Basic settings", 
   "GanttCaption": "Gantt settings", 
"V13_0": "", 
   "Animations": "Animate actions", 
   "ShrinkStyle": "Shrink style in small space", 
   "ShrinkStyle1": "Never", 
   "ShrinkStyle2": "Always", 
   "ShrinkStyle3": "Ask", 
   "CompatibleStyles": "Compatible", 
   "Style": "Style", 
   "GanttStyle": "Gantt style", 
   "StyleSize": "Style size", 
   "Scale": "Scale", 
   "StylesCaption": "-", 
   "ShowBorder": "Show cell default border", 
   "FormulaTip": "Show formula as cell tip", 
"V13_1": "", 
   "ShrinkStyle4": "Minimal", 
"V14_0": "", 
   "LanguageCaption": "-", 
   "Language": "Language", 
"V15_0": "", 
   "ShowFormulas": "Show formulas instead of results", 
   "ShowZeros": "Show cell zero values", 
   "PageBreaks": "Show page breaks for printing", 
   "Contrast": "Contrast", 
   "ShowTree": "Show row tree", 
   "ShowTree1": "Disable", 
   "ShowTree2": "Hide", 
   "ShowTree3": "Parents above", 
   "ShowTree4": "Parents below", 
   "ColTree": "Show column tree", 
   "ColTree1": "Disable", 
   "ColTree2": "Hide", 
   "ColTree3": "Parents left", 
   "ColTree4": "Parents right", 
   "SheetCaption": "Sheet settings", 
   "GanttShowBorder": "Show cell border"  
    }, 



// Columns menu item names, HTML 

"MenuColumns" : { 

"V12_1": "", 
   "Caption": "Choose items", 
   "ColsCaption": "Choose columns", 
   "PagersCaption": "Choose pagers", 
   "SpaceCaption": "Choose toolbars", 
   "RowsCaption": "Choose rows"  
    }, 



// Print menu item names, HTML 

"MenuPrint" : { 

"V12_1": "", 
   "Caption": "Print options", 
   "PrintOptions": "Print options", 
   "PDFName": "File name", 
   "PDFFormat": "", 
   "PrintRows": "Maximum rows per page", 
   "PrintPageRoot": "Start page always by root row", 
   "PDFText": "", 
   "PDFTexts": "Image only,Selectable text,Embedded fonts", 
   "PrintExpanded": "Print all rows expanded", 
   "PrintFiltered": "Print all rows (unfiltered)", 
   "PrintSelectedRows": "Print selected rows only", 
   "PrintSelectedCols": "Print selected columns only", 
   "PrintSelectedCells": "Print selected cells only", 
   "PrintVisible": "Print visible Gantt only", 

   "PrintPageOptions": "Page size<div style='font-size:10px;color:#EA4647;white-space:normal;'>Set&nbsp;the&nbsp;same&nbsp;values&nbsp;also in&nbsp;the&nbsp;browser&nbsp;print&nbsp;dialog!</div>", 
   "PDFPageOptions": "Page size", 
   "PrintPageSize": "Page size", 
   "PrintPageSizes": "Auto,26000,26000,Letter (8.5x11in),215.9,279.4,Legal (8.5x14in),215.9,355.6,Ledger (11x17in),279.4,431.8,A0 - (841x1189),841,1189,A1 - (594x841),594,841,A2 - (420x594),420,594,A3 - (297x420),297,420,A4 - (210x297),210,297,A5 - (148x210),148,210,A6 - (105x148),105,148,A7 - (74x105),74,105,A8 - (52x74),52,74,A9 - (37x52),37,52,B0 - (1000x1414),1000,1414,B1 - (707x1000),707,1000,B2 - (500x707),500,707,B3 - (353x500),353,500,B4 - (250x353),250,353,B5 - (176x250),176,250", 
   "PrintPageOrientation": "Page orientation", 
   "PrintPageOrientations": "Portrait,Landscape", 
   "PrintMarginWidth": "Page margin width (mm)", 
   "PrintMarginHeight": "Page margin height (mm)", 
   "PDFFitPage": "Fit to one page", 
   "PDFFitPages": "None,Width,Height,Single page", 
   "PrintDPI": "DPI (PPI) ratio", 
   "PrintWidth": "Page width (px)", 
   "PrintHeight": "Page height (px)", 
   "PrintResults": "Print size is %d x %d pages", 
"V15_0": "", 
   "PrintOnlyData": "Ignore last empty cells"  
    }, 



// Export menu item names, HTML 

"MenuExport" : { 

"V12_1": "", 
   "Caption": "Export options", 
   "ExportOptions": "Export options", 
   "ExportName": "File name", 
   "ExportFormat": "File format", 
   "ExportExpanded": "Export all rows expanded", 
   "ExportFiltered": "Export all rows (unfiltered)", 
   "ExportOutline": "Export tree in Excel outline", 
   "ExportIndent": "Indent tree in main column", 
   "ExportSelectedRows": "Export selected rows only", 
   "ExportSelectedCols": "Export selected columns only", 
   "ExportSelectedCells": "Export selected cells only", 
   "ExportFixedRows": "Freeze (anchor) head rows", 
   "ExportFixedCols": "Freeze (anchor) left columns", 
   "ExportEmpty": "Export also empty cells"  
    },  



// Filter menu operator names, HTML 
      
"MenuFilter" : { 
       
   "F0": "Off", 
   "F1": "Equal", 
   "F2": "Not equal", 
   "F3": "Less than", 
   "F4": "Less than or equal", 
   "F5": "Greater than", 
   "F6": "Greater than or equal", 
   "F7": "Begins with", 
   "F8": "Does not begin with", 
   "F9": "Ends with", 
   "F10": "Does not end with", 
   "F11": "Contains", 
   "F12": "Does not contain", 
"V14_0": "", 
   "Defs": "Apply filter to", 
   "Defs1": "Filter applied to"  
    }, 



// Names of functions in editable formulas, in format JavaScriptName="LocalizedName". Since 12.0 

"FormulaFunctions" : { 

"V12_0": "", 
   "sum": "sum", 
   "sumsq": "sumsq", 
   "count": "count", 
   "counta": "counta", 
   "countblank": "countblank", 
   "max": "max", 
   "min": "min", 
   "product": "product", 
   "second": "second", 
   "minute": "minute", 
   "hour": "hour", 
   "day": "day", 
   "month": "month", 
   "year": "year", 
   "date": "date", 
   "time": "time", 
   "today": "today", 
   "now": "now", 
   "weekday": "weekday", 
   "weeknum": "weeknum", 
   "round": "round", 
   "ceil": "ceil", 
   "floor": "floor", 
   "abs": "abs", 
   "exp": "exp", 
   "log": "log", 
   "pow": "pow", 
   "sqrt": "sqrt", 
   "sin": "sin", 
   "cos": "cos", 
   "tan": "tan", 
   "asin": "asin", 
   "acos": "acos", 
   "atan": "atan", 
   "text": "text", 
"V13_0": "", 
   "if": "if", 
   "ifs": "ifs", 
   "switch": "switch", 
   "choose": "choose", 
   "concatenate": "concatenate", 
   "concat": "concat", 
   "int": "int", 
   "fix": "fix", 
   "pi": "pi", 
   "hlookup": "hlookup", 
   "vlookup": "vlookup", 
   "lookup": "lookup", 
   "match": "match", 
   "index": "index", 
   "rank": "rank", 
   "rank.eq": "rank.eq", 
   "rank.avg": "rank.avg", 
   "percentrank": "percentrank", 
   "percentrank.inc": "percentrank.inc", 
   "percentrank.exc": "percentrank.exc", 
   "percentile": "percentile", 
   "percentile.inc": "percentile.inc", 
   "percentile.exc": "percentile.exc", 
   "quartile": "quartile", 
   "quartile.inc": "quartile.inc", 
   "quartile.exc": "quartile.exc", 
   "find": "find", 
   "iferror": "iferror", 
   "ifna": "ifna", 
   "and": "and", 
   "or": "or", 
   "xor": "xor", 
   "not": "not", 
   "true": "true", 
   "false": "false", 
   "address": "address", 
   "column": "column", 
   "columns": "columns", 
   "row": "row", 
   "rows": "rows", 
   "offset": "offset", 
   "days": "days", 
   "edate": "edate", 
   "eomonth": "eomonth", 
   "timevalue": "timevalue", 
   "datevalue": "datevalue", 
   "isoweeknum": "isoweeknum", 
   "isblank": "isblank", 
   "iserror": "iserror", 
   "iserr": "iserr", 
   "isna": "isna", 
   "iseven": "iseven", 
   "isodd": "isodd", 
   "isformula": "isformula", 
   "islogical": "islogical", 
   "isnontext": "isnontext", 
   "istext": "istext", 
   "isnumber": "isnumber", 
   "isref": "isref", 
   "n": "n", 
   "t": "t", 
   "na": "na", 
   "type": "type", 
   "formulatext": "formulatext", 
   "char": "char", 
   "clean": "clean", 
   "code": "code", 
   "dollar": "dollar", 
   "exact": "exact", 
   "fixed": "fixed", 
   "left": "left", 
   "right": "right", 
   "mid": "mid", 
   "len": "len", 
   "lower": "lower", 
   "upper": "upper", 
   "numbervalue": "numbervalue", 
   "proper": "proper", 
   "replace": "replace", 
   "rept": "rept", 
   "search": "search", 
   "substitute": "substitute", 
   "textjoin": "textjoin", 
   "unicode": "unicode", 
   "unichar": "unichar", 
   "value": "value", 
   "trim": "trim", 
   "sinh": "sinh", 
   "cosh": "cosh", 
   "tanh": "tanh", 
   "asinh": "asinh", 
   "acosh": "acosh", 
   "atanh": "atanh", 
   "cot": "cot", 
   "acot": "acot", 
   "coth": "coth", 
   "acoth": "acoth", 
   "atan2": "atan2", 
   "base": "base", 
   "ceiling": "ceiling", 
   "ceiling.math": "ceiling.math", 
   "ceiling.precise": "ceiling.precise", 
   "floor.math": "floor.math", 
   "floor.precise": "floor.precise", 
   "combin": "combin", 
   "combina": "combina", 
   "sign": "sign", 
   "gcd": "gcd", 
   "lcm": "lcm", 
   "power": "power", 
   "quotient": "quotient", 
   "mod": "mod", 
   "mround": "mround", 
   "roundup": "roundup", 
   "rounddown": "rounddown", 
   "trunc": "trunc", 
   "rand": "rand", 
   "randbetween": "randbetween", 
   "sumproduct": "sumproduct", 
   "sumx2my2": "sumx2my2", 
   "sumx2py2": "sumx2py2", 
   "sumxmy2": "sumxmy2", 
   "seriessum": "seriessum", 
   "sqrtpi": "sqrtpi", 
   "degrees": "degrees", 
   "radians": "radians", 
   "sec": "sec", 
   "sech": "sech", 
   "csc": "csc", 
   "csch": "csch", 
   "ln": "ln", 
   "log10": "log10", 
   "fact": "fact", 
   "factdouble": "factdouble", 
   "multinomial": "multinomial", 
   "decimal": "decimal", 
   "mdeterm": "mdeterm", 
   "sumif": "sumif", 
   "countif": "countif", 
   "sumifs": "sumifs", 
   "countifs": "countifs", 
   "permut": "permut", 
   "permutationa": "permutationa", 
   "average": "average", 
   "averagea": "averagea", 
   "averageif": "averageif", 
   "averageifs": "averageifs", 
   "median": "median", 
   "mode": "mode", 
   "mode.sngl": "mode.sngl", 
   "geomean": "geomean", 
   "harmean": "harmean", 
   "trimmean": "trimmean", 
   "avedev": "avedev", 
   "devsq": "devsq", 
   "stdev": "stdev", 
   "stdeva": "stdeva", 
   "stdevp": "stdevp", 
   "stdevpa": "stdevpa", 
   "stdev.s": "stdev.s", 
   "stdev.p": "stdev.p", 
   "var": "var", 
   "vara": "vara", 
   "varp": "varp", 
   "varpa": "varpa", 
   "var.s": "var.s", 
   "var.p": "var.p", 
   "covar": "covar", 
   "covariance.s": "covariance.s", 
   "covariance.p": "covariance.p", 
   "forecast": "forecast", 
   "forecast.linear": "forecast.linear", 
   "intercept": "intercept", 
   "slope": "slope", 
   "steyx": "steyx", 
   "mina": "mina", 
   "minifs": "minifs", 
   "maxa": "maxa", 
   "maxifs": "maxifs", 
   "large": "large", 
   "small": "small", 
   "bin2dec": "bin2dec", 
   "bin2oct": "bin2oct", 
   "bin2hex": "bin2hex", 
   "oct2bin": "oct2bin", 
   "oct2dec": "oct2dec", 
   "oct2hex": "oct2hex", 
   "dec2bin": "dec2bin", 
   "dec2oct": "dec2oct", 
   "dec2hex": "dec2hex", 
   "hex2bin": "hex2bin", 
   "hex2oct": "hex2oct", 
   "hex2dec": "hex2dec", 
   "bitand": "bitand", 
   "bitor": "bitor", 
   "bitxor": "bitxor", 
   "bitlshift": "bitlshift", 
   "bitrshift": "bitrshift", 
   "delta": "delta", 
   "gestep": "gestep", 
   "subtotal": "subtotal", 
   "aggregate": "aggregate", 
"V15_1": "", 
   "xirr": "xirr", 
   "xnpv": "xnpv", 
   "pmt": "pmt", 
   "ipmt": "ipmt", 
   "ppmt": "ppmt", 
   "fv": "fv"  
    }, 



// Names of constants in editable formulas, in format JavaScriptName="LocalizedName". Since 12.0 

"FormulaConstants" : { 

   "Math.PI": "pi", 
   "Math.LN10": "ln10", 
   "Math.LN2": "ln2", 
   "Math.LOG10E": "log10e", 
   "Math.LOG2E": "log2e", 
   "Math.SQRT2": "sqrt2", 
   "Math.SQRT1_2": "sqrt1_2", 
   "null": "null", 
   "false": "false", 
   "true": "true"  
    }, 



// Names of operators in editable formulas, in format TreeGridName="LocalizedName". The operator count and names (TreeGridName) cannot be changed. Since 12.0 

"FormulaOperators" : { 

   "Left": "(", 
   "Right": ")", 
   "Plus": "+", 
   "Minus": "-", 
   "Multiply": "*", 
   "Divide": "/", 
   "Modulo": "", 
   "Equal": "= ==", 
   "Inequal": "<> !=", 
   "Greater": ">", 
   "Less": "<", 
   "GreaterEqual": ">=", 
   "LessEqual": "<=", 
   "Not": "", 
   "And": "&&", 
   "Or": "||", 
   "BitNot": "~", 
   "BitAnd": "", 
   "BitOr": "|", 
   "BitXor": "", 
   "BitLeft": "<<", 
   "BitRight": ">>", 
   "If": "?", "Else": ":", 
   "Quote": "\" '", 
   "Chars": "()+-*/%=!<>~&|^?:", 
"V13_0": "", 
   "Concat": "&", 
   "Power": "^", 
   "External": "!", 
   "Percent": "%"  
    }, 



// Language dependent formatting dates and numbers 
      
"Format" : { 
         
   "LongDayNames": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday", 
   "ShortDayNames": "Sun,Mon,Tue,Wed,Thu,Fri,Sat", 
   "Day2CharNames": "Su,Mo,Tu,We,Th,Fr,Sa", 
   "Day1CharNames": "S,M,T,W,T,F,S", 
   "LongMonthNames": "January,February,March,April,May,June,July,August,September,October,November,December", 
   "LongMonthNames2": "January,February,March,April,May,June,July,August,September,October,November,December", 
   "ShortMonthNames": "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec", 
   "InputMonthNames": "", 
   "DayNumbers": "1st,2nd,3rd,4th,5th,6th,7th,8th,9th,10th,11th,12th,13th,14th,15th,16th,17th,18th,19th,20th,21st,22nd,23rd,24th,25th,26th,27th,28th,29th,30th,31st", 
   "Quarters": "Q1,Q2,Q3,Q4", 
   "Halves": "H1,H2", 
   "DateSeparator": "/", 
   "InputDateSeparators": "/.-", 
   "TimeSeparator": ":", 
   "InputTimeSeparators": ":", 
   "InputDateTimeSeparators": "", 
   "AMDesignator": "AM", 
   "PMDesignator": "PM", 
   "InputAMPMDesignators": "", 
   "FirstWeekDay": "0", 
   "FirstWeekYearDay": "0", 
   "NaD": "NaN", 
   "Hirji": "0", 

   "sd": "M/d", 
   "sy": "M/d/yyyy", 
   "sw": "ddd M/d/yyyy", 
   "sm": "M/yyyy", 
   "sn": "\\wddddddd", 
   "ld": "MMMM dd", 
   "ly": "MMMM dd, yyyy", 
   "lw": "dddd, MMMM dd, yyyy", 
   "lwa": "ddd, MMMM dd, yyyy", 
   "lm": "MMMMMMM yyyy", 
   "ln": "'week' ddddddd", 
   "ad": "MMM d", 
   "ay": "MMM d, yyyy", 
   "aw": "ddd, MMM d, yyyy", 
   "awl": "dddd, MMM d, yyyy", 
   "am": "MMM yyyy", 
   "an": "'wk' ddddddd", 
   "th": "h tt", 
   "tm": "h:mm tt", 
   "ts": "h:mm:ss tt", 
   "tf": "h:mm:ss.fff tt", 
   "sth": " h tt", 
   "stm": " h:mm tt", 
   "sts": " h:mm:ss tt", 
   "stf": " HH:mm:ss.fff", 
   "lth": ", h tt", 
   "ltm": ", h:mm tt", 
   "lts": ", h:mm:ss tt", 
   "ltf": ", HH:mm:ss.fff", 
   "yq": "MMMMM yyyy", 
   "yh": "MMMMMM yyyy", 

   "m": "M/d", 
   "d": "M/d/yyyy", 
   "h": "M/d/yyyy HH:mm", 
   "H": "M/d/yyyy HH:mm:ss", 
   "j": "M/d/yyyy h:mm tt", 
   "J": "M/d/yyyy h:mm:ss tt", 
   "y": "M/yyyy", 
   "M": "MMMM d", 
   "D": "MMMM d, yyyy", 
   "l": "MMMM d, yyyy HH:mm", 
   "L": "MMMM d, yyyy HH:mm:ss", 
   "k": "MMMM d, yyyy h:mm tt", 
   "K": "MMMM d, yyyy h:mm:ss tt", 
   "Y": "MMMMMMM yyyy", 
   "t": "HH:mm", 
   "T": "HH:mm:ss", 
   "i": "h:mm tt", 
   "I": "h:mm:ss tt", 

   "f": "MMMM d, yyyy HH:mm", 
   "F": "MMMM d, yyyy HH:mm:ss", 
   "g": "M/d/yyyy HH:mm", 
   "G": "M/d/yyyy HH:mm:ss", 
   "s": "yyyy-MM-ddTHH:mm:ss", 
   "u": "yyyy-MM-dd HH:mm:ssZ", 
   "U": "d. MMMM yyyy HH:mm:ss", 
   "r": "ddd MMM d HH:mm:ss UTCzzzzz yyyy", 
   "R": "ddd MMM d HH:mm:ss UTCzzzzz yyyy", 
   "a": "dddd, dddddd MMMM yyyy", 

   "CalendarMonth": "MMMMMMM yyyy", 

   "ValueSeparator": ";", "ValueSeparatorHtml": "; ", 
   "RangeSeparator": "~", "RangeSeparatorHtml": " ~ ", 
   "RepeatSeparator": "#", 
   "CountSeparator": "*", 
   "AddSeparator": "+", 
      
   "DecimalSeparator": ".", 
   "InputDecimalSeparators": ".,", 
   "GroupSeparator": ",", 
   "GroupCount1": "3", 
   "GroupCount": "3", 
   "InputGroupSeparators": "", 
   "Percent": "%", 
   "NaN": "NaN", 
   "Currency": "$", 
   "Digits": "", 
   "FractionSeparator": "/", 

   "ng": "0.####", 
   "nf": "0.00", 
   "nc": "$,###########0.00;($,###########0.00)", 
   "ncm": "$,###########0.00;-$,###########0.00", 
   "ncmr": "$,###########0.00;[red]-$,###########0.00", 
   "ncp": "$,###########0.00;($,###########0.00)", 
   "ncpr": "$,###########0.00;[red]($,###########0.00)", 
   "np": ",0.00%", 
   "nr": "0.0000", 
   "ne": "0.000000 E+000", 
	
   "Cont": "...", 
   "ContLeft": "... ", 
   "ContRight": " ...", 
   
   "PivotSeparators": "|,|:|<b>,</b> | <em><b>+</b></em> | <em><b>=</b></em> ", 

   "FormulaPrefix": "=", 
   "FormulaRangeSeparator": ":", 
   "FormulaValueSeparator": ",", 
   "FormulaIntersectionSeparator": " ", 
   "FormulaAbsolute": "$", 
   "NaR": "#InvalidRef", 
   "TextPrefix": "'"  
    }  

},  // End of root tag Lang 
   
   
   
// Toolbar button tooltips, HTML 
   
"Toolbar" : { 
   "SaveButtonText": "Save", "SaveTip": "Submit changes to server", 
   "ReloadButtonText": "Reload", "ReloadTip": "Reload grid, cancel changes", 
   "RepaintButtonText": "Pages", "RepaintTip": "Render all pages", "RepaintTip1": "Render pages on demand", 
   "PrintButtonText": "Print", "PrintTip": "Print grid", 
   "ExportPDFButtonText": "PDF", "ExportPDFTip": "Print grid to Adobe PDF", 
   "ExportButtonText": "Export", "ExportTip": "Export grid data to your spreadsheet program", 
   "ImportButtonText": "Import", "ImportTip": "Open local MS Excel xlsx or csv file in the grid", 
   "UndoButtonText": "Undo", "UndoTip": "Undo last action", 
   "RedoButtonText": "Redo", "RedoTip": "Redo last action", 
   "AddButtonText": "Add", "AddTip": "Add new row or move or copy selected rows", 
   "AddChildButtonText": "Add in", "AddChildTip": "Add new child row or move or copy selected rows to actual cursor position", 
   "AddColButtonText": "Add col", "AddColTip": "Add new column or move or copy selected columns", 
   "JoinButtonText": "Join", "JoinTip": "Span selected cells", 
   "SplitButtonText": "Split", "SplitTip": "Split spanned cells", 
   "OutdentButtonText": "Outdent", "OutdentTip": "Outdent, move focused row below its parent", 
   "IndentButtonText": "Indent", "IndentTip": "Indent, move focused row as child of the row above", 
   "LeftButtonText": "Left", "LeftTip": "Align cell content left side", 
   "CenterButtonText": "Center", "CenterTip": "Center the cell content horizontally", 
   "RightButtonText": "Right", "RightTip": "Align cell content right side", 
   "TextIndentText": "Indent", "TextIndentTip": "Indent cell value from the align edge", 
   "TopButtonText": "Top", "TopTip": "Align cell content top side", 
   "MiddleButtonText": "Middle", "MiddleTip": "Center the cell content vertically", 
   "BottomButtonText": "Bottom", "BottomTip": "Align cell content bottom side", 
   "BoldButtonText": "Bold", "BoldTip": "Set the cell font bold", 
   "ItalicButtonText": "Italic", "ItalicTip": "Set the cell font italic", 
   "UnderlineButtonText": "Underline", "UnderlineTip": "Underline the cell text", 
   "StrikeButtonText": "Strike", "StrikeTip": "Strike the cell text", 
   "RotateLeftButtonText": "Rotate 270", "RotateLeftTip": "Rotate the cell content 270 degrees clockwise", 
   "NoRotateButtonText": "No rotate", "NoRotateTip": "Don't rotate the cell content", 
   "RotateRightButtonText": "Rotate 90", "RotateRightTip": "Rotate the cell content 90 degrees clockwise", 
   "WrapTextButtonText": "Wrap", "WrapTextTip": "Wrap the cell text vertically", 
   "SetLinkButtonText": "Add link", "SetLinkTip": "Add or clear hyperlink in the cell or for selected text in cell", 
   "AddImageButtonText": "Add image", "AddImageTip": "Insert image from local file to the cell", 
   "ClearStyleButtonText": "Erase style", "ClearStyleTip": "Erase all style settings from the cell", 
   "SizeTip": "Choose the cell font size", 
   "BorderButtonText": "Border", "BorderTip": "Change the cell border", 
   "ColorTextButtonText": "Color", "ColorTextTip": "Choose the text color", 
   "ColorShadowButtonText": "Shadow", "ColorShadowTip": "Choose the text shadow color", 
   "ColorBackgroundButtonText": "Background", "ColorBackgroundTip": "Choose cell background color", 
   "TextFormatTip": "*Value*<br>Choose the cell format", 

   "DefSort": "Default sort", "DefSortTip": "Restore original sorting", 
   "SortButtonText": "Sort", "SortTip": "Enable sorting and re-sort rows now", "SortTip1": "Disable sorting to change sort criteria faster", 
   "CalcButtonText": "Calculate", "CalcTip": "Enable calculations and re-calculate grid now", "CalcTip1": "Disable calculations to edit cell values faster", 
   "WinScrollButtonText": "No scroll", "WinScrollTip": "Disable grid scrollbars and use page scrollbars", "WinScrollTip1": "Enable grid scrollbars", 
   "ExpandAllButtonText": "Expand all", "ExpandAllTip": "Expand all rows", 
   "CollapseAllButtonText": "Collapse all", "CollapseAllTip": "Collapse all rows", 
   "ColumnsButtonText": "Columns", "ColumnsTip": "Displays menu to choose visible columns", 
   "CfgButtonText": "Config", "CfgTip": "TreeGrid user settings", 
   "LockButtonText": "Lock", "LockTip": "Grid is fully unlocked and editable", 
   "LockTip1": "Grid structure is locked, cells are unlocked", 
   "LockTip2": "Grid structure, cell styles and formulas are locked, cell values are unlocked", 
   "LockTip3": "Grid is fully locked and read only", 
   "HelpButtonText": "Help", "HelpTip": "Show help for TreeGrid control", 
   "DebugButtonText": "Debug", "DebugTip": "Shows debug window", 
   "ResizeTip": "Resize grid", 

   "CorrectButtonText": "Correct", "CorrectTipFormula": "ganttdependencyerrors(null,1)", 
   "ZoomInButtonText": "Zoom in", "ZoomInTip": "Zoom in", 
   "ZoomOutButtonText": "Zoom out", "ZoomOutTip": "Zoom out", 
   "ZoomFitButtonText": "Zoom fit", "ZoomFitTip": "Zoom to fit into page", 

   "LanguagesLabel": "<s>Language:</s>", 
   "StylesLabel": "<s>Style:</s>", 
   "GanttStylesLabel": "<s>Gantt:</s>", 
   "SizesLabel": "<s>Size:</s>", 
   "ScalesLabel": "<s>Scale:</s>", 
   "ContrastsLabel": "<s>Contrast:</s>"  
    }, 

// Row displayed when no variable rows are visible 
// To hide it define Html=""    
"Solid" : [ { "id": "NoData", "Html": "No data found"   }  ],    
   
// Right side pager caption 
"Pager" : { "Caption": "Pager"   },    
   
// Left side panel button tooltips, HTML 
"Panel" : { 
   "PanelMoveTip": "Drag row", 
   "PanelSelectTip": "Select row", 
   "PanelDeleteTip": "Delete row", 
   "PanelCopyTip": "Copy row", 
   "MenuName": "Row panel"  
    }, 
   
"Header" : { 
   "PanelPanelSelectAllTip": "Select or unselect all rows", 
   "PanelPanelDeleteAllTip": "Delete all selected rows", 
   "PanelPanelCopyAllTip": "Add new row or move or copy selected rows"  
    }, 

"Def" : [ 
   { "Name": "Panel", "MenuName": "Column panel", 
      "PanelColSelectTip": "Select column", 
      "PanelColDeleteTip": "Delete column", 
      "PanelColCopyTip": "Copy column", 
      "PanelColSelectAllTip": "Select or unselect all columns", 
      "PanelColDeleteAllTip": "Delete all selected columns", 
      "PanelColCopyAllTip": "Add new column or move or copy selected columns"  
       }  
], 
}) /* End of JSONP header */ 